/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.apis;

import com.worldpay.cert.apis.ApiHelper;
import com.worldpay.cert.apis.Server;
import com.worldpay.cert.apis.exceptions.ApiException;
import com.worldpay.cert.apis.exceptions.TransactionTypes0ErrorException;
import com.worldpay.cert.apis.http.request.HttpMethod;
import com.worldpay.cert.apis.http.response.ApiResponse;
import com.worldpay.cert.apis.models.TransactionTypeCode;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class TransactionTypeApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public TransactionTypeApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * The specific nature or purpose of a financial activity, such as purchases, withdrawals, or
     * transfers.
     * @param  vCorrelationId  Optional parameter: Correlation Id
     * @return    Returns the List of TransactionTypeCode wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<List<TransactionTypeCode>> getTransactionType(
            final UUID vCorrelationId) throws ApiException, IOException {
        return prepareGetTransactionTypeRequest(vCorrelationId).execute();
    }

    /**
     * The specific nature or purpose of a financial activity, such as purchases, withdrawals, or
     * transfers.
     * @param  vCorrelationId  Optional parameter: Correlation Id
     * @return    Returns the List of TransactionTypeCode wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<List<TransactionTypeCode>>> getTransactionTypeAsync(
            final UUID vCorrelationId) {
        try {
            return prepareGetTransactionTypeRequest(vCorrelationId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getTransactionType.
     */
    private ApiCall<ApiResponse<List<TransactionTypeCode>>, ApiException> prepareGetTransactionTypeRequest(
            final UUID vCorrelationId) {
        return new ApiCall.Builder<ApiResponse<List<TransactionTypeCode>>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/transaction-types")
                        .headerParam(param -> param.key("v-correlation-id")
                                .value(vCorrelationId).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("api_key"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        TransactionTypeCode[].class))
                        .nullify404(false)
                        .localErrorCase(ErrorCase.DEFAULT,
                                 ErrorCase.setReason("Default errors",
                                (reason, context) -> new TransactionTypes0ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}