/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis;

import com.worldpay.cert.apis.apis.SettlementBatchesApi;
import com.worldpay.cert.apis.apis.SettlementDailyTotalsApi;
import com.worldpay.cert.apis.apis.SettlementErrorsApi;
import com.worldpay.cert.apis.apis.SettlementsApi;
import com.worldpay.cert.apis.apis.TransactionStatusApi;
import com.worldpay.cert.apis.apis.TransactionTypeApi;
import com.worldpay.cert.apis.authentication.CustomHeaderAuthenticationManager;
import com.worldpay.cert.apis.authentication.CustomHeaderAuthenticationModel;
import com.worldpay.cert.apis.http.client.HttpCallback;
import com.worldpay.cert.apis.http.client.HttpClientConfiguration;
import com.worldpay.cert.apis.http.client.ReadonlyHttpClientConfiguration;
import com.worldpay.cert.apis.logging.configuration.ApiLoggingConfiguration;
import com.worldpay.cert.apis.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class ReportingSettlementResearchApiClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private SettlementsApi settlements;
    private SettlementErrorsApi settlementErrors;
    private SettlementDailyTotalsApi settlementDailyTotals;
    private SettlementBatchesApi settlementBatches;
    private TransactionTypeApi transactionType;
    private TransactionStatusApi transactionStatus;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java SDK, Version: 1.0.3, on OS {os-info}";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * CustomHeaderAuthenticationManager.
     */
    private CustomHeaderAuthenticationManager customHeaderAuthenticationManager;

    /**
     * The instance of CustomHeaderAuthenticationModel.
     */
    private CustomHeaderAuthenticationModel customHeaderAuthenticationModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private ReportingSettlementResearchApiClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig,
            CustomHeaderAuthenticationModel customHeaderAuthenticationModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.customHeaderAuthenticationModel = customHeaderAuthenticationModel;

        this.customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(
                customHeaderAuthenticationModel);
        this.authentications.put("api_key", customHeaderAuthenticationManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        settlements = new SettlementsApi(globalConfig);
        settlementErrors = new SettlementErrorsApi(globalConfig);
        settlementDailyTotals = new SettlementDailyTotalsApi(globalConfig);
        settlementBatches = new SettlementBatchesApi(globalConfig);
        transactionType = new TransactionTypeApi(globalConfig);
        transactionStatus = new TransactionStatusApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of SettlementsApi.
     * @return settlements
     */
    public SettlementsApi getSettlementsApi() {
        return settlements;
    }

    /**
     * Get the instance of SettlementErrorsApi.
     * @return settlementErrors
     */
    public SettlementErrorsApi getSettlementErrorsApi() {
        return settlementErrors;
    }

    /**
     * Get the instance of SettlementDailyTotalsApi.
     * @return settlementDailyTotals
     */
    public SettlementDailyTotalsApi getSettlementDailyTotalsApi() {
        return settlementDailyTotals;
    }

    /**
     * Get the instance of SettlementBatchesApi.
     * @return settlementBatches
     */
    public SettlementBatchesApi getSettlementBatchesApi() {
        return settlementBatches;
    }

    /**
     * Get the instance of TransactionTypeApi.
     * @return transactionType
     */
    public TransactionTypeApi getTransactionTypeApi() {
        return transactionType;
    }

    /**
     * Get the instance of TransactionStatusApi.
     * @return transactionStatus
     */
    public TransactionStatusApi getTransactionStatusApi() {
        return transactionStatus;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with CustomHeaderAuthentication.
     * @return customHeaderAuthenticationCredentials
     */
    public CustomHeaderAuthenticationCredentials getCustomHeaderAuthenticationCredentials() {
        return customHeaderAuthenticationManager;
    }

    /**
     * The auth credential model for CustomHeaderAuthentication.
     * @return the instance of CustomHeaderAuthenticationModel
     */
    public CustomHeaderAuthenticationModel getCustomHeaderAuthenticationModel() {
        return customHeaderAuthenticationModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        return environmentMapper(environment, server);
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://apis.cert.worldpay.com/merchant-reporting/settlementresearch/v1";
            }
        }
        return "https://apis.cert.worldpay.com/merchant-reporting/settlementresearch/v1";
    }

    /**
     * Converts this ReportingSettlementResearchApiClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReportingSettlementResearchApiClient [" + "environment=" + environment
                + ", httpClientConfig=" + httpClientConfig + ", loggingConfig=" + loggingConfig
                + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link ReportingSettlementResearchApiClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link ReportingSettlementResearchApiClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.customHeaderAuthenticationCredentials(getCustomHeaderAuthenticationModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link ReportingSettlementResearchApiClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private CustomHeaderAuthenticationModel customHeaderAuthenticationModel =
                new CustomHeaderAuthenticationModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for CustomHeaderAuthenticationCredentials.
         * @param customHeaderAuthenticationModel The instance of CustomHeaderAuthenticationModel.
         * @return The current instance of builder.
         */
        public Builder customHeaderAuthenticationCredentials(
                CustomHeaderAuthenticationModel customHeaderAuthenticationModel) {
            this.customHeaderAuthenticationModel = customHeaderAuthenticationModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new ReportingSettlementResearchApiClient object using the set fields.
         * @return ReportingSettlementResearchApiClient
         */
        public ReportingSettlementResearchApiClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new ReportingSettlementResearchApiClient(environment, httpClient,
                    httpClientConfig, loggingConfig, customHeaderAuthenticationModel, httpCallback);
        }
    }
}