/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for AdditionalDetails type.
 */
public class AdditionalDetails {
    private String hasAdjustmentRecords;
    private Boolean forcePost;
    private String airlineInvoiceNumber;
    private String airlineTicketNumber;
    private LocalDate airlineDepartureDate;
    private Boolean unmatchedCredit;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AdditionalDetails() {
    }

    /**
     * Initialization constructor.
     * @param  hasAdjustmentRecords  String value for hasAdjustmentRecords.
     * @param  forcePost  Boolean value for forcePost.
     * @param  airlineInvoiceNumber  String value for airlineInvoiceNumber.
     * @param  airlineTicketNumber  String value for airlineTicketNumber.
     * @param  airlineDepartureDate  LocalDate value for airlineDepartureDate.
     * @param  unmatchedCredit  Boolean value for unmatchedCredit.
     */
    public AdditionalDetails(
            String hasAdjustmentRecords,
            Boolean forcePost,
            String airlineInvoiceNumber,
            String airlineTicketNumber,
            LocalDate airlineDepartureDate,
            Boolean unmatchedCredit) {
        this.hasAdjustmentRecords = hasAdjustmentRecords;
        this.forcePost = forcePost;
        this.airlineInvoiceNumber = airlineInvoiceNumber;
        this.airlineTicketNumber = airlineTicketNumber;
        this.airlineDepartureDate = airlineDepartureDate;
        this.unmatchedCredit = unmatchedCredit;
    }

    /**
     * Getter for HasAdjustmentRecords.
     * Refers to any adjustment made in the records.
     * @return Returns the String
     */
    @JsonGetter("hasAdjustmentRecords")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHasAdjustmentRecords() {
        return hasAdjustmentRecords;
    }

    /**
     * Setter for HasAdjustmentRecords.
     * Refers to any adjustment made in the records.
     * @param hasAdjustmentRecords Value for String
     */
    @JsonSetter("hasAdjustmentRecords")
    public void setHasAdjustmentRecords(String hasAdjustmentRecords) {
        this.hasAdjustmentRecords = hasAdjustmentRecords;
    }

    /**
     * Getter for ForcePost.
     * Possible values are True or False.
     * @return Returns the Boolean
     */
    @JsonGetter("forcePost")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getForcePost() {
        return forcePost;
    }

    /**
     * Setter for ForcePost.
     * Possible values are True or False.
     * @param forcePost Value for Boolean
     */
    @JsonSetter("forcePost")
    public void setForcePost(Boolean forcePost) {
        this.forcePost = forcePost;
    }

    /**
     * Getter for AirlineInvoiceNumber.
     * Unique identifier for the airline invoice billing transactions.
     * @return Returns the String
     */
    @JsonGetter("airlineInvoiceNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAirlineInvoiceNumber() {
        return airlineInvoiceNumber;
    }

    /**
     * Setter for AirlineInvoiceNumber.
     * Unique identifier for the airline invoice billing transactions.
     * @param airlineInvoiceNumber Value for String
     */
    @JsonSetter("airlineInvoiceNumber")
    public void setAirlineInvoiceNumber(String airlineInvoiceNumber) {
        this.airlineInvoiceNumber = airlineInvoiceNumber;
    }

    /**
     * Getter for AirlineTicketNumber.
     * Unique identifier for the airline ticket billing transactions.
     * @return Returns the String
     */
    @JsonGetter("airlineTicketNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAirlineTicketNumber() {
        return airlineTicketNumber;
    }

    /**
     * Setter for AirlineTicketNumber.
     * Unique identifier for the airline ticket billing transactions.
     * @param airlineTicketNumber Value for String
     */
    @JsonSetter("airlineTicketNumber")
    public void setAirlineTicketNumber(String airlineTicketNumber) {
        this.airlineTicketNumber = airlineTicketNumber;
    }

    /**
     * Getter for AirlineDepartureDate.
     * The scheduled day a flight leaves.
     * @return Returns the LocalDate
     */
    @JsonGetter("airlineDepartureDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getAirlineDepartureDate() {
        return airlineDepartureDate;
    }

    /**
     * Setter for AirlineDepartureDate.
     * The scheduled day a flight leaves.
     * @param airlineDepartureDate Value for LocalDate
     */
    @JsonSetter("airlineDepartureDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setAirlineDepartureDate(LocalDate airlineDepartureDate) {
        this.airlineDepartureDate = airlineDepartureDate;
    }

    /**
     * Getter for UnmatchedCredit.
     * Indicates funds without corresponding transaction records in the accounts. Possible values
     * are true or false.
     * @return Returns the Boolean
     */
    @JsonGetter("unmatchedCredit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getUnmatchedCredit() {
        return unmatchedCredit;
    }

    /**
     * Setter for UnmatchedCredit.
     * Indicates funds without corresponding transaction records in the accounts. Possible values
     * are true or false.
     * @param unmatchedCredit Value for Boolean
     */
    @JsonSetter("unmatchedCredit")
    public void setUnmatchedCredit(Boolean unmatchedCredit) {
        this.unmatchedCredit = unmatchedCredit;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AdditionalDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdditionalDetails [" + "hasAdjustmentRecords=" + hasAdjustmentRecords
                + ", forcePost=" + forcePost + ", airlineInvoiceNumber=" + airlineInvoiceNumber
                + ", airlineTicketNumber=" + airlineTicketNumber + ", airlineDepartureDate="
                + airlineDepartureDate + ", unmatchedCredit=" + unmatchedCredit
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link AdditionalDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdditionalDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hasAdjustmentRecords(getHasAdjustmentRecords())
                .forcePost(getForcePost())
                .airlineInvoiceNumber(getAirlineInvoiceNumber())
                .airlineTicketNumber(getAirlineTicketNumber())
                .airlineDepartureDate(getAirlineDepartureDate())
                .unmatchedCredit(getUnmatchedCredit());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AdditionalDetails}.
     */
    public static class Builder {
        private String hasAdjustmentRecords;
        private Boolean forcePost;
        private String airlineInvoiceNumber;
        private String airlineTicketNumber;
        private LocalDate airlineDepartureDate;
        private Boolean unmatchedCredit;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for hasAdjustmentRecords.
         * @param  hasAdjustmentRecords  String value for hasAdjustmentRecords.
         * @return Builder
         */
        public Builder hasAdjustmentRecords(String hasAdjustmentRecords) {
            this.hasAdjustmentRecords = hasAdjustmentRecords;
            return this;
        }

        /**
         * Setter for forcePost.
         * @param  forcePost  Boolean value for forcePost.
         * @return Builder
         */
        public Builder forcePost(Boolean forcePost) {
            this.forcePost = forcePost;
            return this;
        }

        /**
         * Setter for airlineInvoiceNumber.
         * @param  airlineInvoiceNumber  String value for airlineInvoiceNumber.
         * @return Builder
         */
        public Builder airlineInvoiceNumber(String airlineInvoiceNumber) {
            this.airlineInvoiceNumber = airlineInvoiceNumber;
            return this;
        }

        /**
         * Setter for airlineTicketNumber.
         * @param  airlineTicketNumber  String value for airlineTicketNumber.
         * @return Builder
         */
        public Builder airlineTicketNumber(String airlineTicketNumber) {
            this.airlineTicketNumber = airlineTicketNumber;
            return this;
        }

        /**
         * Setter for airlineDepartureDate.
         * @param  airlineDepartureDate  LocalDate value for airlineDepartureDate.
         * @return Builder
         */
        public Builder airlineDepartureDate(LocalDate airlineDepartureDate) {
            this.airlineDepartureDate = airlineDepartureDate;
            return this;
        }

        /**
         * Setter for unmatchedCredit.
         * @param  unmatchedCredit  Boolean value for unmatchedCredit.
         * @return Builder
         */
        public Builder unmatchedCredit(Boolean unmatchedCredit) {
            this.unmatchedCredit = unmatchedCredit;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AdditionalDetails} object using the set fields.
         * @return {@link AdditionalDetails}
         */
        public AdditionalDetails build() {
            AdditionalDetails model =
                    new AdditionalDetails(hasAdjustmentRecords, forcePost, airlineInvoiceNumber,
                            airlineTicketNumber, airlineDepartureDate, unmatchedCredit);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
