/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for AuthorizationCurrency type.
 */
public class AuthorizationCurrency {
    private String code;
    private String shortDescription;
    private String longDescription;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AuthorizationCurrency() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     * @param  shortDescription  String value for shortDescription.
     * @param  longDescription  String value for longDescription.
     */
    public AuthorizationCurrency(
            String code,
            String shortDescription,
            String longDescription) {
        this.code = code;
        this.shortDescription = shortDescription;
        this.longDescription = longDescription;
    }

    /**
     * Getter for Code.
     * The identifier code.
     * @return Returns the String
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * The identifier code.
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for ShortDescription.
     * The short description of the code.
     * @return Returns the String
     */
    @JsonGetter("shortDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Setter for ShortDescription.
     * The short description of the code.
     * @param shortDescription Value for String
     */
    @JsonSetter("shortDescription")
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    /**
     * Getter for LongDescription.
     * The long description of the code.
     * @return Returns the String
     */
    @JsonGetter("longDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Setter for LongDescription.
     * The long description of the code.
     * @param longDescription Value for String
     */
    @JsonSetter("longDescription")
    public void setLongDescription(String longDescription) {
        this.longDescription = longDescription;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AuthorizationCurrency into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthorizationCurrency [" + "code=" + code + ", shortDescription=" + shortDescription
                + ", longDescription=" + longDescription + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link AuthorizationCurrency.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthorizationCurrency.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode())
                .shortDescription(getShortDescription())
                .longDescription(getLongDescription());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AuthorizationCurrency}.
     */
    public static class Builder {
        private String code;
        private String shortDescription;
        private String longDescription;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for shortDescription.
         * @param  shortDescription  String value for shortDescription.
         * @return Builder
         */
        public Builder shortDescription(String shortDescription) {
            this.shortDescription = shortDescription;
            return this;
        }

        /**
         * Setter for longDescription.
         * @param  longDescription  String value for longDescription.
         * @return Builder
         */
        public Builder longDescription(String longDescription) {
            this.longDescription = longDescription;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AuthorizationCurrency} object using the set fields.
         * @return {@link AuthorizationCurrency}
         */
        public AuthorizationCurrency build() {
            AuthorizationCurrency model =
                    new AuthorizationCurrency(code, shortDescription, longDescription);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
