/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for BankCardRejRealTimeTransaction type.
 */
public class BankCardRejRealTimeTransaction {
    private LocalDate processDate;
    private Integer batchNumber;
    private Double batchAmount;
    private Integer saleCount;
    private Double saleAmount;
    private Integer returnCount;
    private Double returnAmount;
    private RejectionReason rejectionReason;
    private BatchHoldStatus batchHoldStatus;
    private Hierarchy9 hierarchy;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public BankCardRejRealTimeTransaction() {
    }

    /**
     * Initialization constructor.
     * @param  processDate  LocalDate value for processDate.
     * @param  batchNumber  Integer value for batchNumber.
     * @param  batchAmount  Double value for batchAmount.
     * @param  saleCount  Integer value for saleCount.
     * @param  saleAmount  Double value for saleAmount.
     * @param  returnCount  Integer value for returnCount.
     * @param  returnAmount  Double value for returnAmount.
     * @param  rejectionReason  RejectionReason value for rejectionReason.
     * @param  batchHoldStatus  BatchHoldStatus value for batchHoldStatus.
     * @param  hierarchy  Hierarchy9 value for hierarchy.
     */
    public BankCardRejRealTimeTransaction(
            LocalDate processDate,
            Integer batchNumber,
            Double batchAmount,
            Integer saleCount,
            Double saleAmount,
            Integer returnCount,
            Double returnAmount,
            RejectionReason rejectionReason,
            BatchHoldStatus batchHoldStatus,
            Hierarchy9 hierarchy) {
        this.processDate = processDate;
        this.batchNumber = batchNumber;
        this.batchAmount = batchAmount;
        this.saleCount = saleCount;
        this.saleAmount = saleAmount;
        this.returnCount = returnCount;
        this.returnAmount = returnAmount;
        this.rejectionReason = rejectionReason;
        this.batchHoldStatus = batchHoldStatus;
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @return Returns the LocalDate
     */
    @JsonGetter("processDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getProcessDate() {
        return processDate;
    }

    /**
     * Setter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @param processDate Value for LocalDate
     */
    @JsonSetter("processDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setProcessDate(LocalDate processDate) {
        this.processDate = processDate;
    }

    /**
     * Getter for BatchNumber.
     * The unique identifier assigned to a group of transactions that were handled together as a
     * single unit.
     * @return Returns the Integer
     */
    @JsonGetter("batchNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getBatchNumber() {
        return batchNumber;
    }

    /**
     * Setter for BatchNumber.
     * The unique identifier assigned to a group of transactions that were handled together as a
     * single unit.
     * @param batchNumber Value for Integer
     */
    @JsonSetter("batchNumber")
    public void setBatchNumber(Integer batchNumber) {
        this.batchNumber = batchNumber;
    }

    /**
     * Getter for BatchAmount.
     * The total amount of all the transactions that are part of the batch file.
     * @return Returns the Double
     */
    @JsonGetter("batchAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getBatchAmount() {
        return batchAmount;
    }

    /**
     * Setter for BatchAmount.
     * The total amount of all the transactions that are part of the batch file.
     * @param batchAmount Value for Double
     */
    @JsonSetter("batchAmount")
    public void setBatchAmount(Double batchAmount) {
        this.batchAmount = batchAmount;
    }

    /**
     * Getter for SaleCount.
     * The sale count of the transaction.
     * @return Returns the Integer
     */
    @JsonGetter("saleCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * Setter for SaleCount.
     * The sale count of the transaction.
     * @param saleCount Value for Integer
     */
    @JsonSetter("saleCount")
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * Getter for SaleAmount.
     * The sale amount of the transaction.
     * @return Returns the Double
     */
    @JsonGetter("saleAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSaleAmount() {
        return saleAmount;
    }

    /**
     * Setter for SaleAmount.
     * The sale amount of the transaction.
     * @param saleAmount Value for Double
     */
    @JsonSetter("saleAmount")
    public void setSaleAmount(Double saleAmount) {
        this.saleAmount = saleAmount;
    }

    /**
     * Getter for ReturnCount.
     * The number of items sent back from a transaction.
     * @return Returns the Integer
     */
    @JsonGetter("returnCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReturnCount() {
        return returnCount;
    }

    /**
     * Setter for ReturnCount.
     * The number of items sent back from a transaction.
     * @param returnCount Value for Integer
     */
    @JsonSetter("returnCount")
    public void setReturnCount(Integer returnCount) {
        this.returnCount = returnCount;
    }

    /**
     * Getter for ReturnAmount.
     * The amount returned from a transaction.
     * @return Returns the Double
     */
    @JsonGetter("returnAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getReturnAmount() {
        return returnAmount;
    }

    /**
     * Setter for ReturnAmount.
     * The amount returned from a transaction.
     * @param returnAmount Value for Double
     */
    @JsonSetter("returnAmount")
    public void setReturnAmount(Double returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * Getter for RejectionReason.
     * @return Returns the RejectionReason
     */
    @JsonGetter("rejectionReason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RejectionReason getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Setter for RejectionReason.
     * @param rejectionReason Value for RejectionReason
     */
    @JsonSetter("rejectionReason")
    public void setRejectionReason(RejectionReason rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    /**
     * Getter for BatchHoldStatus.
     * @return Returns the BatchHoldStatus
     */
    @JsonGetter("batchHoldStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BatchHoldStatus getBatchHoldStatus() {
        return batchHoldStatus;
    }

    /**
     * Setter for BatchHoldStatus.
     * @param batchHoldStatus Value for BatchHoldStatus
     */
    @JsonSetter("batchHoldStatus")
    public void setBatchHoldStatus(BatchHoldStatus batchHoldStatus) {
        this.batchHoldStatus = batchHoldStatus;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy9
     */
    @JsonGetter("hierarchy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Hierarchy9 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy9
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy9 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this BankCardRejRealTimeTransaction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BankCardRejRealTimeTransaction [" + "processDate=" + processDate + ", batchNumber="
                + batchNumber + ", batchAmount=" + batchAmount + ", saleCount=" + saleCount
                + ", saleAmount=" + saleAmount + ", returnCount=" + returnCount + ", returnAmount="
                + returnAmount + ", rejectionReason=" + rejectionReason + ", batchHoldStatus="
                + batchHoldStatus + ", hierarchy=" + hierarchy + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link BankCardRejRealTimeTransaction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BankCardRejRealTimeTransaction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .processDate(getProcessDate())
                .batchNumber(getBatchNumber())
                .batchAmount(getBatchAmount())
                .saleCount(getSaleCount())
                .saleAmount(getSaleAmount())
                .returnCount(getReturnCount())
                .returnAmount(getReturnAmount())
                .rejectionReason(getRejectionReason())
                .batchHoldStatus(getBatchHoldStatus())
                .hierarchy(getHierarchy());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link BankCardRejRealTimeTransaction}.
     */
    public static class Builder {
        private LocalDate processDate;
        private Integer batchNumber;
        private Double batchAmount;
        private Integer saleCount;
        private Double saleAmount;
        private Integer returnCount;
        private Double returnAmount;
        private RejectionReason rejectionReason;
        private BatchHoldStatus batchHoldStatus;
        private Hierarchy9 hierarchy;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for processDate.
         * @param  processDate  LocalDate value for processDate.
         * @return Builder
         */
        public Builder processDate(LocalDate processDate) {
            this.processDate = processDate;
            return this;
        }

        /**
         * Setter for batchNumber.
         * @param  batchNumber  Integer value for batchNumber.
         * @return Builder
         */
        public Builder batchNumber(Integer batchNumber) {
            this.batchNumber = batchNumber;
            return this;
        }

        /**
         * Setter for batchAmount.
         * @param  batchAmount  Double value for batchAmount.
         * @return Builder
         */
        public Builder batchAmount(Double batchAmount) {
            this.batchAmount = batchAmount;
            return this;
        }

        /**
         * Setter for saleCount.
         * @param  saleCount  Integer value for saleCount.
         * @return Builder
         */
        public Builder saleCount(Integer saleCount) {
            this.saleCount = saleCount;
            return this;
        }

        /**
         * Setter for saleAmount.
         * @param  saleAmount  Double value for saleAmount.
         * @return Builder
         */
        public Builder saleAmount(Double saleAmount) {
            this.saleAmount = saleAmount;
            return this;
        }

        /**
         * Setter for returnCount.
         * @param  returnCount  Integer value for returnCount.
         * @return Builder
         */
        public Builder returnCount(Integer returnCount) {
            this.returnCount = returnCount;
            return this;
        }

        /**
         * Setter for returnAmount.
         * @param  returnAmount  Double value for returnAmount.
         * @return Builder
         */
        public Builder returnAmount(Double returnAmount) {
            this.returnAmount = returnAmount;
            return this;
        }

        /**
         * Setter for rejectionReason.
         * @param  rejectionReason  RejectionReason value for rejectionReason.
         * @return Builder
         */
        public Builder rejectionReason(RejectionReason rejectionReason) {
            this.rejectionReason = rejectionReason;
            return this;
        }

        /**
         * Setter for batchHoldStatus.
         * @param  batchHoldStatus  BatchHoldStatus value for batchHoldStatus.
         * @return Builder
         */
        public Builder batchHoldStatus(BatchHoldStatus batchHoldStatus) {
            this.batchHoldStatus = batchHoldStatus;
            return this;
        }

        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy9 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy9 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link BankCardRejRealTimeTransaction} object using the set fields.
         * @return {@link BankCardRejRealTimeTransaction}
         */
        public BankCardRejRealTimeTransaction build() {
            BankCardRejRealTimeTransaction model =
                    new BankCardRejRealTimeTransaction(processDate, batchNumber, batchAmount,
                            saleCount, saleAmount, returnCount, returnAmount, rejectionReason,
                            batchHoldStatus, hierarchy);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
