/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for CardDetails type.
 */
public class CardDetails {
    private String cardNumber;
    private String cardType;
    private LocalDate expirationDate;
    private CardNetwork cardNetwork;
    private Cvv2ResponseCode cvv2ResponseCode;
    private Cvv2PresenceIndicator cvv2PresenceIndicator;
    private String token;
    private String tokenId;
    private String tokenAssuranceLevel;
    private LocalDate tokenExpirationDate;
    private InternationalIndicator internationalIndicator;
    private Boolean networkRejectIndicator;
    private String networkPaymentTokenNumber;
    private CardAccountTerm cardAccountTerm;
    private String cardholderBankAcro;
    private String tokenRequestorId;
    private LocalDate bankNetDate;
    private String bankNetReferenceNumber;
    private MarketSpecificDataIndicator marketSpecificDataIndicator;
    private String dccMcpIndicator;
    private String lastFourOfPan;
    private Boolean visaReversed;
    private LocalDate visaReversedDate;
    private String mastercardWalletId;
    private MastercardTicIndicator mastercardTicIndicator;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CardDetails() {
    }

    /**
     * Initialization constructor.
     * @param  cardNumber  String value for cardNumber.
     * @param  cardType  String value for cardType.
     * @param  expirationDate  LocalDate value for expirationDate.
     * @param  cardNetwork  CardNetwork value for cardNetwork.
     * @param  cvv2ResponseCode  Cvv2ResponseCode value for cvv2ResponseCode.
     * @param  cvv2PresenceIndicator  Cvv2PresenceIndicator value for cvv2PresenceIndicator.
     * @param  token  String value for token.
     * @param  tokenId  String value for tokenId.
     * @param  tokenAssuranceLevel  String value for tokenAssuranceLevel.
     * @param  tokenExpirationDate  LocalDate value for tokenExpirationDate.
     * @param  internationalIndicator  InternationalIndicator value for internationalIndicator.
     * @param  networkRejectIndicator  Boolean value for networkRejectIndicator.
     * @param  networkPaymentTokenNumber  String value for networkPaymentTokenNumber.
     * @param  cardAccountTerm  CardAccountTerm value for cardAccountTerm.
     * @param  cardholderBankAcro  String value for cardholderBankAcro.
     * @param  tokenRequestorId  String value for tokenRequestorId.
     * @param  bankNetDate  LocalDate value for bankNetDate.
     * @param  bankNetReferenceNumber  String value for bankNetReferenceNumber.
     * @param  marketSpecificDataIndicator  MarketSpecificDataIndicator value for
     *         marketSpecificDataIndicator.
     * @param  dccMcpIndicator  String value for dccMcpIndicator.
     * @param  lastFourOfPan  String value for lastFourOfPan.
     * @param  visaReversed  Boolean value for visaReversed.
     * @param  visaReversedDate  LocalDate value for visaReversedDate.
     * @param  mastercardWalletId  String value for mastercardWalletId.
     * @param  mastercardTicIndicator  MastercardTicIndicator value for mastercardTicIndicator.
     */
    public CardDetails(
            String cardNumber,
            String cardType,
            LocalDate expirationDate,
            CardNetwork cardNetwork,
            Cvv2ResponseCode cvv2ResponseCode,
            Cvv2PresenceIndicator cvv2PresenceIndicator,
            String token,
            String tokenId,
            String tokenAssuranceLevel,
            LocalDate tokenExpirationDate,
            InternationalIndicator internationalIndicator,
            Boolean networkRejectIndicator,
            String networkPaymentTokenNumber,
            CardAccountTerm cardAccountTerm,
            String cardholderBankAcro,
            String tokenRequestorId,
            LocalDate bankNetDate,
            String bankNetReferenceNumber,
            MarketSpecificDataIndicator marketSpecificDataIndicator,
            String dccMcpIndicator,
            String lastFourOfPan,
            Boolean visaReversed,
            LocalDate visaReversedDate,
            String mastercardWalletId,
            MastercardTicIndicator mastercardTicIndicator) {
        this.cardNumber = cardNumber;
        this.cardType = cardType;
        this.expirationDate = expirationDate;
        this.cardNetwork = cardNetwork;
        this.cvv2ResponseCode = cvv2ResponseCode;
        this.cvv2PresenceIndicator = cvv2PresenceIndicator;
        this.token = token;
        this.tokenId = tokenId;
        this.tokenAssuranceLevel = tokenAssuranceLevel;
        this.tokenExpirationDate = tokenExpirationDate;
        this.internationalIndicator = internationalIndicator;
        this.networkRejectIndicator = networkRejectIndicator;
        this.networkPaymentTokenNumber = networkPaymentTokenNumber;
        this.cardAccountTerm = cardAccountTerm;
        this.cardholderBankAcro = cardholderBankAcro;
        this.tokenRequestorId = tokenRequestorId;
        this.bankNetDate = bankNetDate;
        this.bankNetReferenceNumber = bankNetReferenceNumber;
        this.marketSpecificDataIndicator = marketSpecificDataIndicator;
        this.dccMcpIndicator = dccMcpIndicator;
        this.lastFourOfPan = lastFourOfPan;
        this.visaReversed = visaReversed;
        this.visaReversedDate = visaReversedDate;
        this.mastercardWalletId = mastercardWalletId;
        this.mastercardTicIndicator = mastercardTicIndicator;
    }

    /**
     * Getter for CardNumber.
     * The number found on the card used to make a purchase, also referred to as the bank or credit
     * card number. &lt;br&gt;Searches can be done on the full card number, on the first six and last four
     * digits, or on the last four digits."
     * @return Returns the String
     */
    @JsonGetter("cardNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Setter for CardNumber.
     * The number found on the card used to make a purchase, also referred to as the bank or credit
     * card number. &lt;br&gt;Searches can be done on the full card number, on the first six and last four
     * digits, or on the last four digits."
     * @param cardNumber Value for String
     */
    @JsonSetter("cardNumber")
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * Getter for CardType.
     * The category or classification of a payment card based on the issuing network. &lt;br&gt; Possible
     * values are CREDIT, DEBIT, and GIFT.
     * @return Returns the String
     */
    @JsonGetter("cardType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardType() {
        return cardType;
    }

    /**
     * Setter for CardType.
     * The category or classification of a payment card based on the issuing network. &lt;br&gt; Possible
     * values are CREDIT, DEBIT, and GIFT.
     * @param cardType Value for String
     */
    @JsonSetter("cardType")
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * Getter for ExpirationDate.
     * The set time when a card will need to be replaced.
     * @return Returns the LocalDate
     */
    @JsonGetter("expirationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getExpirationDate() {
        return expirationDate;
    }

    /**
     * Setter for ExpirationDate.
     * The set time when a card will need to be replaced.
     * @param expirationDate Value for LocalDate
     */
    @JsonSetter("expirationDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setExpirationDate(LocalDate expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * Getter for CardNetwork.
     * @return Returns the CardNetwork
     */
    @JsonGetter("cardNetwork")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardNetwork getCardNetwork() {
        return cardNetwork;
    }

    /**
     * Setter for CardNetwork.
     * @param cardNetwork Value for CardNetwork
     */
    @JsonSetter("cardNetwork")
    public void setCardNetwork(CardNetwork cardNetwork) {
        this.cardNetwork = cardNetwork;
    }

    /**
     * Getter for Cvv2ResponseCode.
     * @return Returns the Cvv2ResponseCode
     */
    @JsonGetter("cvv2ResponseCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Cvv2ResponseCode getCvv2ResponseCode() {
        return cvv2ResponseCode;
    }

    /**
     * Setter for Cvv2ResponseCode.
     * @param cvv2ResponseCode Value for Cvv2ResponseCode
     */
    @JsonSetter("cvv2ResponseCode")
    public void setCvv2ResponseCode(Cvv2ResponseCode cvv2ResponseCode) {
        this.cvv2ResponseCode = cvv2ResponseCode;
    }

    /**
     * Getter for Cvv2PresenceIndicator.
     * @return Returns the Cvv2PresenceIndicator
     */
    @JsonGetter("cvv2PresenceIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Cvv2PresenceIndicator getCvv2PresenceIndicator() {
        return cvv2PresenceIndicator;
    }

    /**
     * Setter for Cvv2PresenceIndicator.
     * @param cvv2PresenceIndicator Value for Cvv2PresenceIndicator
     */
    @JsonSetter("cvv2PresenceIndicator")
    public void setCvv2PresenceIndicator(Cvv2PresenceIndicator cvv2PresenceIndicator) {
        this.cvv2PresenceIndicator = cvv2PresenceIndicator;
    }

    /**
     * Getter for Token.
     * The numeric value that is the same length as the card number and is used as a substitution
     * with proxy data. Max length of the token is 19 characters.
     * @return Returns the String
     */
    @JsonGetter("token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToken() {
        return token;
    }

    /**
     * Setter for Token.
     * The numeric value that is the same length as the card number and is used as a substitution
     * with proxy data. Max length of the token is 19 characters.
     * @param token Value for String
     */
    @JsonSetter("token")
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for TokenId.
     * The host-generated numeric value created during the tokenization process using a token key
     * assigned to a merchant. This value is returned to the point-of-sale when tokenization is
     * requested along with the token for utilization.
     * @return Returns the String
     */
    @JsonGetter("tokenId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTokenId() {
        return tokenId;
    }

    /**
     * Setter for TokenId.
     * The host-generated numeric value created during the tokenization process using a token key
     * assigned to a merchant. This value is returned to the point-of-sale when tokenization is
     * requested along with the token for utilization.
     * @param tokenId Value for String
     */
    @JsonSetter("tokenId")
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * Getter for TokenAssuranceLevel.
     * A request and response field. The score or confidence level that determines the expected
     * level of assurance associated with the approved token requestor and the identification and
     * verification method performed at the time of token request.
     * @return Returns the String
     */
    @JsonGetter("tokenAssuranceLevel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTokenAssuranceLevel() {
        return tokenAssuranceLevel;
    }

    /**
     * Setter for TokenAssuranceLevel.
     * A request and response field. The score or confidence level that determines the expected
     * level of assurance associated with the approved token requestor and the identification and
     * verification method performed at the time of token request.
     * @param tokenAssuranceLevel Value for String
     */
    @JsonSetter("tokenAssuranceLevel")
    public void setTokenAssuranceLevel(String tokenAssuranceLevel) {
        this.tokenAssuranceLevel = tokenAssuranceLevel;
    }

    /**
     * Getter for TokenExpirationDate.
     * The expiration date of the token in the YYYY-MM format with a fixed length of 6.
     * @return Returns the LocalDate
     */
    @JsonGetter("tokenExpirationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getTokenExpirationDate() {
        return tokenExpirationDate;
    }

    /**
     * Setter for TokenExpirationDate.
     * The expiration date of the token in the YYYY-MM format with a fixed length of 6.
     * @param tokenExpirationDate Value for LocalDate
     */
    @JsonSetter("tokenExpirationDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setTokenExpirationDate(LocalDate tokenExpirationDate) {
        this.tokenExpirationDate = tokenExpirationDate;
    }

    /**
     * Getter for InternationalIndicator.
     * @return Returns the InternationalIndicator
     */
    @JsonGetter("internationalIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InternationalIndicator getInternationalIndicator() {
        return internationalIndicator;
    }

    /**
     * Setter for InternationalIndicator.
     * @param internationalIndicator Value for InternationalIndicator
     */
    @JsonSetter("internationalIndicator")
    public void setInternationalIndicator(InternationalIndicator internationalIndicator) {
        this.internationalIndicator = internationalIndicator;
    }

    /**
     * Getter for NetworkRejectIndicator.
     * Possible values are true and false.
     * @return Returns the Boolean
     */
    @JsonGetter("networkRejectIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getNetworkRejectIndicator() {
        return networkRejectIndicator;
    }

    /**
     * Setter for NetworkRejectIndicator.
     * Possible values are true and false.
     * @param networkRejectIndicator Value for Boolean
     */
    @JsonSetter("networkRejectIndicator")
    public void setNetworkRejectIndicator(Boolean networkRejectIndicator) {
        this.networkRejectIndicator = networkRejectIndicator;
    }

    /**
     * Getter for NetworkPaymentTokenNumber.
     * Indentifier for digital payment transactions.
     * @return Returns the String
     */
    @JsonGetter("networkPaymentTokenNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNetworkPaymentTokenNumber() {
        return networkPaymentTokenNumber;
    }

    /**
     * Setter for NetworkPaymentTokenNumber.
     * Indentifier for digital payment transactions.
     * @param networkPaymentTokenNumber Value for String
     */
    @JsonSetter("networkPaymentTokenNumber")
    public void setNetworkPaymentTokenNumber(String networkPaymentTokenNumber) {
        this.networkPaymentTokenNumber = networkPaymentTokenNumber;
    }

    /**
     * Getter for CardAccountTerm.
     * @return Returns the CardAccountTerm
     */
    @JsonGetter("cardAccountTerm")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardAccountTerm getCardAccountTerm() {
        return cardAccountTerm;
    }

    /**
     * Setter for CardAccountTerm.
     * @param cardAccountTerm Value for CardAccountTerm
     */
    @JsonSetter("cardAccountTerm")
    public void setCardAccountTerm(CardAccountTerm cardAccountTerm) {
        this.cardAccountTerm = cardAccountTerm;
    }

    /**
     * Getter for CardholderBankAcro.
     * The acronym for the primary user of a payment card.
     * @return Returns the String
     */
    @JsonGetter("cardholderBankAcro")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardholderBankAcro() {
        return cardholderBankAcro;
    }

    /**
     * Setter for CardholderBankAcro.
     * The acronym for the primary user of a payment card.
     * @param cardholderBankAcro Value for String
     */
    @JsonSetter("cardholderBankAcro")
    public void setCardholderBankAcro(String cardholderBankAcro) {
        this.cardholderBankAcro = cardholderBankAcro;
    }

    /**
     * Getter for TokenRequestorId.
     * The unique identifier used to request network tokens from the card networks.
     * @return Returns the String
     */
    @JsonGetter("tokenRequestorId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTokenRequestorId() {
        return tokenRequestorId;
    }

    /**
     * Setter for TokenRequestorId.
     * The unique identifier used to request network tokens from the card networks.
     * @param tokenRequestorId Value for String
     */
    @JsonSetter("tokenRequestorId")
    public void setTokenRequestorId(String tokenRequestorId) {
        this.tokenRequestorId = tokenRequestorId;
    }

    /**
     * Getter for BankNetDate.
     * The payments network operated by Mastercard. The value is present only if the transaction is
     * Mastercard, otherwise it's null.
     * @return Returns the LocalDate
     */
    @JsonGetter("bankNetDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getBankNetDate() {
        return bankNetDate;
    }

    /**
     * Setter for BankNetDate.
     * The payments network operated by Mastercard. The value is present only if the transaction is
     * Mastercard, otherwise it's null.
     * @param bankNetDate Value for LocalDate
     */
    @JsonSetter("bankNetDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setBankNetDate(LocalDate bankNetDate) {
        this.bankNetDate = bankNetDate;
    }

    /**
     * Getter for BankNetReferenceNumber.
     * The unique identifier for transactions processed through banknet systems.
     * @return Returns the String
     */
    @JsonGetter("bankNetReferenceNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBankNetReferenceNumber() {
        return bankNetReferenceNumber;
    }

    /**
     * Setter for BankNetReferenceNumber.
     * The unique identifier for transactions processed through banknet systems.
     * @param bankNetReferenceNumber Value for String
     */
    @JsonSetter("bankNetReferenceNumber")
    public void setBankNetReferenceNumber(String bankNetReferenceNumber) {
        this.bankNetReferenceNumber = bankNetReferenceNumber;
    }

    /**
     * Getter for MarketSpecificDataIndicator.
     * @return Returns the MarketSpecificDataIndicator
     */
    @JsonGetter("marketSpecificDataIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MarketSpecificDataIndicator getMarketSpecificDataIndicator() {
        return marketSpecificDataIndicator;
    }

    /**
     * Setter for MarketSpecificDataIndicator.
     * @param marketSpecificDataIndicator Value for MarketSpecificDataIndicator
     */
    @JsonSetter("marketSpecificDataIndicator")
    public void setMarketSpecificDataIndicator(MarketSpecificDataIndicator marketSpecificDataIndicator) {
        this.marketSpecificDataIndicator = marketSpecificDataIndicator;
    }

    /**
     * Getter for DccMcpIndicator.
     * Provides dynamic currency conversion information to the merchant. Applicable for credit
     * (master credit card).
     * @return Returns the String
     */
    @JsonGetter("dccMcpIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDccMcpIndicator() {
        return dccMcpIndicator;
    }

    /**
     * Setter for DccMcpIndicator.
     * Provides dynamic currency conversion information to the merchant. Applicable for credit
     * (master credit card).
     * @param dccMcpIndicator Value for String
     */
    @JsonSetter("dccMcpIndicator")
    public void setDccMcpIndicator(String dccMcpIndicator) {
        this.dccMcpIndicator = dccMcpIndicator;
    }

    /**
     * Getter for LastFourOfPan.
     * The last four digits of the PAN on the receipt.
     * @return Returns the String
     */
    @JsonGetter("lastFourOfPAN")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastFourOfPan() {
        return lastFourOfPan;
    }

    /**
     * Setter for LastFourOfPan.
     * The last four digits of the PAN on the receipt.
     * @param lastFourOfPan Value for String
     */
    @JsonSetter("lastFourOfPAN")
    public void setLastFourOfPan(String lastFourOfPan) {
        this.lastFourOfPan = lastFourOfPan;
    }

    /**
     * Getter for VisaReversed.
     * Indicates funds without corresponding transaction records in accounts. Possible values are
     * true or false.
     * @return Returns the Boolean
     */
    @JsonGetter("visaReversed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getVisaReversed() {
        return visaReversed;
    }

    /**
     * Setter for VisaReversed.
     * Indicates funds without corresponding transaction records in accounts. Possible values are
     * true or false.
     * @param visaReversed Value for Boolean
     */
    @JsonSetter("visaReversed")
    public void setVisaReversed(Boolean visaReversed) {
        this.visaReversed = visaReversed;
    }

    /**
     * Getter for VisaReversedDate.
     * The Visa transaction's reversed authorization date.
     * @return Returns the LocalDate
     */
    @JsonGetter("visaReversedDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getVisaReversedDate() {
        return visaReversedDate;
    }

    /**
     * Setter for VisaReversedDate.
     * The Visa transaction's reversed authorization date.
     * @param visaReversedDate Value for LocalDate
     */
    @JsonSetter("visaReversedDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setVisaReversedDate(LocalDate visaReversedDate) {
        this.visaReversedDate = visaReversedDate;
    }

    /**
     * Getter for MastercardWalletId.
     * The Mastercard wallet identifier.
     * @return Returns the String
     */
    @JsonGetter("mastercardWalletId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMastercardWalletId() {
        return mastercardWalletId;
    }

    /**
     * Setter for MastercardWalletId.
     * The Mastercard wallet identifier.
     * @param mastercardWalletId Value for String
     */
    @JsonSetter("mastercardWalletId")
    public void setMastercardWalletId(String mastercardWalletId) {
        this.mastercardWalletId = mastercardWalletId;
    }

    /**
     * Getter for MastercardTicIndicator.
     * @return Returns the MastercardTicIndicator
     */
    @JsonGetter("mastercardTICIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MastercardTicIndicator getMastercardTicIndicator() {
        return mastercardTicIndicator;
    }

    /**
     * Setter for MastercardTicIndicator.
     * @param mastercardTicIndicator Value for MastercardTicIndicator
     */
    @JsonSetter("mastercardTICIndicator")
    public void setMastercardTicIndicator(MastercardTicIndicator mastercardTicIndicator) {
        this.mastercardTicIndicator = mastercardTicIndicator;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CardDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CardDetails [" + "cardNumber=" + cardNumber + ", cardType=" + cardType
                + ", expirationDate=" + expirationDate + ", cardNetwork=" + cardNetwork
                + ", cvv2ResponseCode=" + cvv2ResponseCode + ", cvv2PresenceIndicator="
                + cvv2PresenceIndicator + ", token=" + token + ", tokenId=" + tokenId
                + ", tokenAssuranceLevel=" + tokenAssuranceLevel + ", tokenExpirationDate="
                + tokenExpirationDate + ", internationalIndicator=" + internationalIndicator
                + ", networkRejectIndicator=" + networkRejectIndicator
                + ", networkPaymentTokenNumber=" + networkPaymentTokenNumber + ", cardAccountTerm="
                + cardAccountTerm + ", cardholderBankAcro=" + cardholderBankAcro
                + ", tokenRequestorId=" + tokenRequestorId + ", bankNetDate=" + bankNetDate
                + ", bankNetReferenceNumber=" + bankNetReferenceNumber
                + ", marketSpecificDataIndicator=" + marketSpecificDataIndicator
                + ", dccMcpIndicator=" + dccMcpIndicator + ", lastFourOfPan=" + lastFourOfPan
                + ", visaReversed=" + visaReversed + ", visaReversedDate=" + visaReversedDate
                + ", mastercardWalletId=" + mastercardWalletId + ", mastercardTicIndicator="
                + mastercardTicIndicator + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CardDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CardDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .cardNumber(getCardNumber())
                .cardType(getCardType())
                .expirationDate(getExpirationDate())
                .cardNetwork(getCardNetwork())
                .cvv2ResponseCode(getCvv2ResponseCode())
                .cvv2PresenceIndicator(getCvv2PresenceIndicator())
                .token(getToken())
                .tokenId(getTokenId())
                .tokenAssuranceLevel(getTokenAssuranceLevel())
                .tokenExpirationDate(getTokenExpirationDate())
                .internationalIndicator(getInternationalIndicator())
                .networkRejectIndicator(getNetworkRejectIndicator())
                .networkPaymentTokenNumber(getNetworkPaymentTokenNumber())
                .cardAccountTerm(getCardAccountTerm())
                .cardholderBankAcro(getCardholderBankAcro())
                .tokenRequestorId(getTokenRequestorId())
                .bankNetDate(getBankNetDate())
                .bankNetReferenceNumber(getBankNetReferenceNumber())
                .marketSpecificDataIndicator(getMarketSpecificDataIndicator())
                .dccMcpIndicator(getDccMcpIndicator())
                .lastFourOfPan(getLastFourOfPan())
                .visaReversed(getVisaReversed())
                .visaReversedDate(getVisaReversedDate())
                .mastercardWalletId(getMastercardWalletId())
                .mastercardTicIndicator(getMastercardTicIndicator());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CardDetails}.
     */
    public static class Builder {
        private String cardNumber;
        private String cardType;
        private LocalDate expirationDate;
        private CardNetwork cardNetwork;
        private Cvv2ResponseCode cvv2ResponseCode;
        private Cvv2PresenceIndicator cvv2PresenceIndicator;
        private String token;
        private String tokenId;
        private String tokenAssuranceLevel;
        private LocalDate tokenExpirationDate;
        private InternationalIndicator internationalIndicator;
        private Boolean networkRejectIndicator;
        private String networkPaymentTokenNumber;
        private CardAccountTerm cardAccountTerm;
        private String cardholderBankAcro;
        private String tokenRequestorId;
        private LocalDate bankNetDate;
        private String bankNetReferenceNumber;
        private MarketSpecificDataIndicator marketSpecificDataIndicator;
        private String dccMcpIndicator;
        private String lastFourOfPan;
        private Boolean visaReversed;
        private LocalDate visaReversedDate;
        private String mastercardWalletId;
        private MastercardTicIndicator mastercardTicIndicator;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for cardNumber.
         * @param  cardNumber  String value for cardNumber.
         * @return Builder
         */
        public Builder cardNumber(String cardNumber) {
            this.cardNumber = cardNumber;
            return this;
        }

        /**
         * Setter for cardType.
         * @param  cardType  String value for cardType.
         * @return Builder
         */
        public Builder cardType(String cardType) {
            this.cardType = cardType;
            return this;
        }

        /**
         * Setter for expirationDate.
         * @param  expirationDate  LocalDate value for expirationDate.
         * @return Builder
         */
        public Builder expirationDate(LocalDate expirationDate) {
            this.expirationDate = expirationDate;
            return this;
        }

        /**
         * Setter for cardNetwork.
         * @param  cardNetwork  CardNetwork value for cardNetwork.
         * @return Builder
         */
        public Builder cardNetwork(CardNetwork cardNetwork) {
            this.cardNetwork = cardNetwork;
            return this;
        }

        /**
         * Setter for cvv2ResponseCode.
         * @param  cvv2ResponseCode  Cvv2ResponseCode value for cvv2ResponseCode.
         * @return Builder
         */
        public Builder cvv2ResponseCode(Cvv2ResponseCode cvv2ResponseCode) {
            this.cvv2ResponseCode = cvv2ResponseCode;
            return this;
        }

        /**
         * Setter for cvv2PresenceIndicator.
         * @param  cvv2PresenceIndicator  Cvv2PresenceIndicator value for cvv2PresenceIndicator.
         * @return Builder
         */
        public Builder cvv2PresenceIndicator(Cvv2PresenceIndicator cvv2PresenceIndicator) {
            this.cvv2PresenceIndicator = cvv2PresenceIndicator;
            return this;
        }

        /**
         * Setter for token.
         * @param  token  String value for token.
         * @return Builder
         */
        public Builder token(String token) {
            this.token = token;
            return this;
        }

        /**
         * Setter for tokenId.
         * @param  tokenId  String value for tokenId.
         * @return Builder
         */
        public Builder tokenId(String tokenId) {
            this.tokenId = tokenId;
            return this;
        }

        /**
         * Setter for tokenAssuranceLevel.
         * @param  tokenAssuranceLevel  String value for tokenAssuranceLevel.
         * @return Builder
         */
        public Builder tokenAssuranceLevel(String tokenAssuranceLevel) {
            this.tokenAssuranceLevel = tokenAssuranceLevel;
            return this;
        }

        /**
         * Setter for tokenExpirationDate.
         * @param  tokenExpirationDate  LocalDate value for tokenExpirationDate.
         * @return Builder
         */
        public Builder tokenExpirationDate(LocalDate tokenExpirationDate) {
            this.tokenExpirationDate = tokenExpirationDate;
            return this;
        }

        /**
         * Setter for internationalIndicator.
         * @param  internationalIndicator  InternationalIndicator value for internationalIndicator.
         * @return Builder
         */
        public Builder internationalIndicator(InternationalIndicator internationalIndicator) {
            this.internationalIndicator = internationalIndicator;
            return this;
        }

        /**
         * Setter for networkRejectIndicator.
         * @param  networkRejectIndicator  Boolean value for networkRejectIndicator.
         * @return Builder
         */
        public Builder networkRejectIndicator(Boolean networkRejectIndicator) {
            this.networkRejectIndicator = networkRejectIndicator;
            return this;
        }

        /**
         * Setter for networkPaymentTokenNumber.
         * @param  networkPaymentTokenNumber  String value for networkPaymentTokenNumber.
         * @return Builder
         */
        public Builder networkPaymentTokenNumber(String networkPaymentTokenNumber) {
            this.networkPaymentTokenNumber = networkPaymentTokenNumber;
            return this;
        }

        /**
         * Setter for cardAccountTerm.
         * @param  cardAccountTerm  CardAccountTerm value for cardAccountTerm.
         * @return Builder
         */
        public Builder cardAccountTerm(CardAccountTerm cardAccountTerm) {
            this.cardAccountTerm = cardAccountTerm;
            return this;
        }

        /**
         * Setter for cardholderBankAcro.
         * @param  cardholderBankAcro  String value for cardholderBankAcro.
         * @return Builder
         */
        public Builder cardholderBankAcro(String cardholderBankAcro) {
            this.cardholderBankAcro = cardholderBankAcro;
            return this;
        }

        /**
         * Setter for tokenRequestorId.
         * @param  tokenRequestorId  String value for tokenRequestorId.
         * @return Builder
         */
        public Builder tokenRequestorId(String tokenRequestorId) {
            this.tokenRequestorId = tokenRequestorId;
            return this;
        }

        /**
         * Setter for bankNetDate.
         * @param  bankNetDate  LocalDate value for bankNetDate.
         * @return Builder
         */
        public Builder bankNetDate(LocalDate bankNetDate) {
            this.bankNetDate = bankNetDate;
            return this;
        }

        /**
         * Setter for bankNetReferenceNumber.
         * @param  bankNetReferenceNumber  String value for bankNetReferenceNumber.
         * @return Builder
         */
        public Builder bankNetReferenceNumber(String bankNetReferenceNumber) {
            this.bankNetReferenceNumber = bankNetReferenceNumber;
            return this;
        }

        /**
         * Setter for marketSpecificDataIndicator.
         * @param  marketSpecificDataIndicator  MarketSpecificDataIndicator value for
         *         marketSpecificDataIndicator.
         * @return Builder
         */
        public Builder marketSpecificDataIndicator(
                MarketSpecificDataIndicator marketSpecificDataIndicator) {
            this.marketSpecificDataIndicator = marketSpecificDataIndicator;
            return this;
        }

        /**
         * Setter for dccMcpIndicator.
         * @param  dccMcpIndicator  String value for dccMcpIndicator.
         * @return Builder
         */
        public Builder dccMcpIndicator(String dccMcpIndicator) {
            this.dccMcpIndicator = dccMcpIndicator;
            return this;
        }

        /**
         * Setter for lastFourOfPan.
         * @param  lastFourOfPan  String value for lastFourOfPan.
         * @return Builder
         */
        public Builder lastFourOfPan(String lastFourOfPan) {
            this.lastFourOfPan = lastFourOfPan;
            return this;
        }

        /**
         * Setter for visaReversed.
         * @param  visaReversed  Boolean value for visaReversed.
         * @return Builder
         */
        public Builder visaReversed(Boolean visaReversed) {
            this.visaReversed = visaReversed;
            return this;
        }

        /**
         * Setter for visaReversedDate.
         * @param  visaReversedDate  LocalDate value for visaReversedDate.
         * @return Builder
         */
        public Builder visaReversedDate(LocalDate visaReversedDate) {
            this.visaReversedDate = visaReversedDate;
            return this;
        }

        /**
         * Setter for mastercardWalletId.
         * @param  mastercardWalletId  String value for mastercardWalletId.
         * @return Builder
         */
        public Builder mastercardWalletId(String mastercardWalletId) {
            this.mastercardWalletId = mastercardWalletId;
            return this;
        }

        /**
         * Setter for mastercardTicIndicator.
         * @param  mastercardTicIndicator  MastercardTicIndicator value for mastercardTicIndicator.
         * @return Builder
         */
        public Builder mastercardTicIndicator(MastercardTicIndicator mastercardTicIndicator) {
            this.mastercardTicIndicator = mastercardTicIndicator;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CardDetails} object using the set fields.
         * @return {@link CardDetails}
         */
        public CardDetails build() {
            CardDetails model =
                    new CardDetails(cardNumber, cardType, expirationDate, cardNetwork,
                            cvv2ResponseCode, cvv2PresenceIndicator, token, tokenId,
                            tokenAssuranceLevel, tokenExpirationDate, internationalIndicator,
                            networkRejectIndicator, networkPaymentTokenNumber, cardAccountTerm,
                            cardholderBankAcro, tokenRequestorId, bankNetDate,
                            bankNetReferenceNumber, marketSpecificDataIndicator, dccMcpIndicator,
                            lastFourOfPan, visaReversed, visaReversedDate, mastercardWalletId,
                            mastercardTicIndicator);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
