/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for CreditTransactionDetails type.
 */
public class CreditTransactionDetails {
    private String transactionId;
    private LocalDate processDate;
    private LocalDateTime transactionDateTime;
    private Double authorizationAmount;
    private Double approvedAmount;
    private String authorizationCode;
    private AuthorizationCurrency authorizationCurrency;
    private AuthorizationSource authorizationSource;
    private TransactionType transactionType;
    private TransactionStatus transactionStatus;
    private EntryMode entryMode;
    private AvsResponseCode avsResponseCode;
    private CardholderId cardholderId;
    private String sequenceNumber;
    private String authorizationIdentifier;
    private String customerIdentifier;
    private String merchantOrderIdentifier;
    private String campaign;
    private String affiliate;
    private String merchantGroupingIdentifier;
    private String reportGroup;
    private Aci aci;
    private MailPhoneIndicator mailPhoneIndicator;
    private OriginType originType;
    private String validationCode;
    private String posRegisterNumber;
    private String terminalNumber;
    private String referenceNumber;
    private String draftLocator;
    private TerminalCapability terminalCapability;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CreditTransactionDetails() {
    }

    /**
     * Initialization constructor.
     * @param  transactionId  String value for transactionId.
     * @param  processDate  LocalDate value for processDate.
     * @param  transactionDateTime  LocalDateTime value for transactionDateTime.
     * @param  authorizationAmount  Double value for authorizationAmount.
     * @param  approvedAmount  Double value for approvedAmount.
     * @param  authorizationCode  String value for authorizationCode.
     * @param  authorizationCurrency  AuthorizationCurrency value for authorizationCurrency.
     * @param  authorizationSource  AuthorizationSource value for authorizationSource.
     * @param  transactionType  TransactionType value for transactionType.
     * @param  transactionStatus  TransactionStatus value for transactionStatus.
     * @param  entryMode  EntryMode value for entryMode.
     * @param  avsResponseCode  AvsResponseCode value for avsResponseCode.
     * @param  cardholderId  CardholderId value for cardholderId.
     * @param  sequenceNumber  String value for sequenceNumber.
     * @param  authorizationIdentifier  String value for authorizationIdentifier.
     * @param  customerIdentifier  String value for customerIdentifier.
     * @param  merchantOrderIdentifier  String value for merchantOrderIdentifier.
     * @param  campaign  String value for campaign.
     * @param  affiliate  String value for affiliate.
     * @param  merchantGroupingIdentifier  String value for merchantGroupingIdentifier.
     * @param  reportGroup  String value for reportGroup.
     * @param  aci  Aci value for aci.
     * @param  mailPhoneIndicator  MailPhoneIndicator value for mailPhoneIndicator.
     * @param  originType  OriginType value for originType.
     * @param  validationCode  String value for validationCode.
     * @param  posRegisterNumber  String value for posRegisterNumber.
     * @param  terminalNumber  String value for terminalNumber.
     * @param  referenceNumber  String value for referenceNumber.
     * @param  draftLocator  String value for draftLocator.
     * @param  terminalCapability  TerminalCapability value for terminalCapability.
     */
    public CreditTransactionDetails(
            String transactionId,
            LocalDate processDate,
            LocalDateTime transactionDateTime,
            Double authorizationAmount,
            Double approvedAmount,
            String authorizationCode,
            AuthorizationCurrency authorizationCurrency,
            AuthorizationSource authorizationSource,
            TransactionType transactionType,
            TransactionStatus transactionStatus,
            EntryMode entryMode,
            AvsResponseCode avsResponseCode,
            CardholderId cardholderId,
            String sequenceNumber,
            String authorizationIdentifier,
            String customerIdentifier,
            String merchantOrderIdentifier,
            String campaign,
            String affiliate,
            String merchantGroupingIdentifier,
            String reportGroup,
            Aci aci,
            MailPhoneIndicator mailPhoneIndicator,
            OriginType originType,
            String validationCode,
            String posRegisterNumber,
            String terminalNumber,
            String referenceNumber,
            String draftLocator,
            TerminalCapability terminalCapability) {
        this.transactionId = transactionId;
        this.processDate = processDate;
        this.transactionDateTime = transactionDateTime;
        this.authorizationAmount = authorizationAmount;
        this.approvedAmount = approvedAmount;
        this.authorizationCode = authorizationCode;
        this.authorizationCurrency = authorizationCurrency;
        this.authorizationSource = authorizationSource;
        this.transactionType = transactionType;
        this.transactionStatus = transactionStatus;
        this.entryMode = entryMode;
        this.avsResponseCode = avsResponseCode;
        this.cardholderId = cardholderId;
        this.sequenceNumber = sequenceNumber;
        this.authorizationIdentifier = authorizationIdentifier;
        this.customerIdentifier = customerIdentifier;
        this.merchantOrderIdentifier = merchantOrderIdentifier;
        this.campaign = campaign;
        this.affiliate = affiliate;
        this.merchantGroupingIdentifier = merchantGroupingIdentifier;
        this.reportGroup = reportGroup;
        this.aci = aci;
        this.mailPhoneIndicator = mailPhoneIndicator;
        this.originType = originType;
        this.validationCode = validationCode;
        this.posRegisterNumber = posRegisterNumber;
        this.terminalNumber = terminalNumber;
        this.referenceNumber = referenceNumber;
        this.draftLocator = draftLocator;
        this.terminalCapability = terminalCapability;
    }

    /**
     * Getter for TransactionId.
     * The unique 12-19 digit identifier that is generated with every card transaction and from the
     * electronic transfer of funds.
     * @return Returns the String
     */
    @JsonGetter("transactionId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * The unique 12-19 digit identifier that is generated with every card transaction and from the
     * electronic transfer of funds.
     * @param transactionId Value for String
     */
    @JsonSetter("transactionId")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for ProcessDate.
     * Refers to the date when the transaction has been processed for settlement between the two
     * parties.
     * @return Returns the LocalDate
     */
    @JsonGetter("processDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getProcessDate() {
        return processDate;
    }

    /**
     * Setter for ProcessDate.
     * Refers to the date when the transaction has been processed for settlement between the two
     * parties.
     * @param processDate Value for LocalDate
     */
    @JsonSetter("processDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setProcessDate(LocalDate processDate) {
        this.processDate = processDate;
    }

    /**
     * Getter for TransactionDateTime.
     * Refers to the date and time when the bank has settled the transaction (deposits or withdraws
     * funds).
     * @return Returns the LocalDateTime
     */
    @JsonGetter("transactionDateTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTransactionDateTime() {
        return transactionDateTime;
    }

    /**
     * Setter for TransactionDateTime.
     * Refers to the date and time when the bank has settled the transaction (deposits or withdraws
     * funds).
     * @param transactionDateTime Value for LocalDateTime
     */
    @JsonSetter("transactionDateTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTransactionDateTime(LocalDateTime transactionDateTime) {
        this.transactionDateTime = transactionDateTime;
    }

    /**
     * Getter for AuthorizationAmount.
     * The approved amount of money to be charged.
     * @return Returns the Double
     */
    @JsonGetter("authorizationAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAuthorizationAmount() {
        return authorizationAmount;
    }

    /**
     * Setter for AuthorizationAmount.
     * The approved amount of money to be charged.
     * @param authorizationAmount Value for Double
     */
    @JsonSetter("authorizationAmount")
    public void setAuthorizationAmount(Double authorizationAmount) {
        this.authorizationAmount = authorizationAmount;
    }

    /**
     * Getter for ApprovedAmount.
     * The agreed upon sum for a transaction after authorization and processing steps.
     * @return Returns the Double
     */
    @JsonGetter("approvedAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getApprovedAmount() {
        return approvedAmount;
    }

    /**
     * Setter for ApprovedAmount.
     * The agreed upon sum for a transaction after authorization and processing steps.
     * @param approvedAmount Value for Double
     */
    @JsonSetter("approvedAmount")
    public void setApprovedAmount(Double approvedAmount) {
        this.approvedAmount = approvedAmount;
    }

    /**
     * Getter for AuthorizationCode.
     * The six number code from the issuing bank to the vendor that authorizes the sale.
     * @return Returns the String
     */
    @JsonGetter("authorizationCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Setter for AuthorizationCode.
     * The six number code from the issuing bank to the vendor that authorizes the sale.
     * @param authorizationCode Value for String
     */
    @JsonSetter("authorizationCode")
    public void setAuthorizationCode(String authorizationCode) {
        this.authorizationCode = authorizationCode;
    }

    /**
     * Getter for AuthorizationCurrency.
     * @return Returns the AuthorizationCurrency
     */
    @JsonGetter("authorizationCurrency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuthorizationCurrency getAuthorizationCurrency() {
        return authorizationCurrency;
    }

    /**
     * Setter for AuthorizationCurrency.
     * @param authorizationCurrency Value for AuthorizationCurrency
     */
    @JsonSetter("authorizationCurrency")
    public void setAuthorizationCurrency(AuthorizationCurrency authorizationCurrency) {
        this.authorizationCurrency = authorizationCurrency;
    }

    /**
     * Getter for AuthorizationSource.
     * @return Returns the AuthorizationSource
     */
    @JsonGetter("authorizationSource")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuthorizationSource getAuthorizationSource() {
        return authorizationSource;
    }

    /**
     * Setter for AuthorizationSource.
     * @param authorizationSource Value for AuthorizationSource
     */
    @JsonSetter("authorizationSource")
    public void setAuthorizationSource(AuthorizationSource authorizationSource) {
        this.authorizationSource = authorizationSource;
    }

    /**
     * Getter for TransactionType.
     * @return Returns the TransactionType
     */
    @JsonGetter("transactionType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Setter for TransactionType.
     * @param transactionType Value for TransactionType
     */
    @JsonSetter("transactionType")
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * Getter for TransactionStatus.
     * @return Returns the TransactionStatus
     */
    @JsonGetter("transactionStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionStatus getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Setter for TransactionStatus.
     * @param transactionStatus Value for TransactionStatus
     */
    @JsonSetter("transactionStatus")
    public void setTransactionStatus(TransactionStatus transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    /**
     * Getter for EntryMode.
     * @return Returns the EntryMode
     */
    @JsonGetter("entryMode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EntryMode getEntryMode() {
        return entryMode;
    }

    /**
     * Setter for EntryMode.
     * @param entryMode Value for EntryMode
     */
    @JsonSetter("entryMode")
    public void setEntryMode(EntryMode entryMode) {
        this.entryMode = entryMode;
    }

    /**
     * Getter for AvsResponseCode.
     * @return Returns the AvsResponseCode
     */
    @JsonGetter("avsResponseCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AvsResponseCode getAvsResponseCode() {
        return avsResponseCode;
    }

    /**
     * Setter for AvsResponseCode.
     * @param avsResponseCode Value for AvsResponseCode
     */
    @JsonSetter("avsResponseCode")
    public void setAvsResponseCode(AvsResponseCode avsResponseCode) {
        this.avsResponseCode = avsResponseCode;
    }

    /**
     * Getter for CardholderId.
     * @return Returns the CardholderId
     */
    @JsonGetter("cardholderId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardholderId getCardholderId() {
        return cardholderId;
    }

    /**
     * Setter for CardholderId.
     * @param cardholderId Value for CardholderId
     */
    @JsonSetter("cardholderId")
    public void setCardholderId(CardholderId cardholderId) {
        this.cardholderId = cardholderId;
    }

    /**
     * Getter for SequenceNumber.
     * Te unique order identifier indicating the transaction or event sequence.
     * @return Returns the String
     */
    @JsonGetter("sequenceNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Setter for SequenceNumber.
     * Te unique order identifier indicating the transaction or event sequence.
     * @param sequenceNumber Value for String
     */
    @JsonSetter("sequenceNumber")
    public void setSequenceNumber(String sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * Getter for AuthorizationIdentifier.
     * The ecommerce authorization identifier.
     * @return Returns the String
     */
    @JsonGetter("authorizationIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthorizationIdentifier() {
        return authorizationIdentifier;
    }

    /**
     * Setter for AuthorizationIdentifier.
     * The ecommerce authorization identifier.
     * @param authorizationIdentifier Value for String
     */
    @JsonSetter("authorizationIdentifier")
    public void setAuthorizationIdentifier(String authorizationIdentifier) {
        this.authorizationIdentifier = authorizationIdentifier;
    }

    /**
     * Getter for CustomerIdentifier.
     * The unique identifier of the purchaser associated with the transaction.
     * @return Returns the String
     */
    @JsonGetter("customerIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCustomerIdentifier() {
        return customerIdentifier;
    }

    /**
     * Setter for CustomerIdentifier.
     * The unique identifier of the purchaser associated with the transaction.
     * @param customerIdentifier Value for String
     */
    @JsonSetter("customerIdentifier")
    public void setCustomerIdentifier(String customerIdentifier) {
        this.customerIdentifier = customerIdentifier;
    }

    /**
     * Getter for MerchantOrderIdentifier.
     * The merchant-designated identifier for this transaction.
     * @return Returns the String
     */
    @JsonGetter("merchantOrderIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantOrderIdentifier() {
        return merchantOrderIdentifier;
    }

    /**
     * Setter for MerchantOrderIdentifier.
     * The merchant-designated identifier for this transaction.
     * @param merchantOrderIdentifier Value for String
     */
    @JsonSetter("merchantOrderIdentifier")
    public void setMerchantOrderIdentifier(String merchantOrderIdentifier) {
        this.merchantOrderIdentifier = merchantOrderIdentifier;
    }

    /**
     * Getter for Campaign.
     * The merchant-specified identifier used to track transactions associated with specific
     * marketing campaigns.
     * @return Returns the String
     */
    @JsonGetter("campaign")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCampaign() {
        return campaign;
    }

    /**
     * Setter for Campaign.
     * The merchant-specified identifier used to track transactions associated with specific
     * marketing campaigns.
     * @param campaign Value for String
     */
    @JsonSetter("campaign")
    public void setCampaign(String campaign) {
        this.campaign = campaign;
    }

    /**
     * Getter for Affiliate.
     * The merchant-specified identifier used to track transactions associated with your affiliate
     * organizations.
     * @return Returns the String
     */
    @JsonGetter("affiliate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAffiliate() {
        return affiliate;
    }

    /**
     * Setter for Affiliate.
     * The merchant-specified identifier used to track transactions associated with your affiliate
     * organizations.
     * @param affiliate Value for String
     */
    @JsonSetter("affiliate")
    public void setAffiliate(String affiliate) {
        this.affiliate = affiliate;
    }

    /**
     * Getter for MerchantGroupingIdentifier.
     * The merchant-specified identifier for grouping transactions by an additional transaction
     * level id outside of affiliate or campaign.
     * @return Returns the String
     */
    @JsonGetter("merchantGroupingIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantGroupingIdentifier() {
        return merchantGroupingIdentifier;
    }

    /**
     * Setter for MerchantGroupingIdentifier.
     * The merchant-specified identifier for grouping transactions by an additional transaction
     * level id outside of affiliate or campaign.
     * @param merchantGroupingIdentifier Value for String
     */
    @JsonSetter("merchantGroupingIdentifier")
    public void setMerchantGroupingIdentifier(String merchantGroupingIdentifier) {
        this.merchantGroupingIdentifier = merchantGroupingIdentifier;
    }

    /**
     * Getter for ReportGroup.
     * The reporting group category to which the transaction belongs.
     * @return Returns the String
     */
    @JsonGetter("reportGroup")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReportGroup() {
        return reportGroup;
    }

    /**
     * Setter for ReportGroup.
     * The reporting group category to which the transaction belongs.
     * @param reportGroup Value for String
     */
    @JsonSetter("reportGroup")
    public void setReportGroup(String reportGroup) {
        this.reportGroup = reportGroup;
    }

    /**
     * Getter for Aci.
     * @return Returns the Aci
     */
    @JsonGetter("aci")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Aci getAci() {
        return aci;
    }

    /**
     * Setter for Aci.
     * @param aci Value for Aci
     */
    @JsonSetter("aci")
    public void setAci(Aci aci) {
        this.aci = aci;
    }

    /**
     * Getter for MailPhoneIndicator.
     * @return Returns the MailPhoneIndicator
     */
    @JsonGetter("mailPhoneIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MailPhoneIndicator getMailPhoneIndicator() {
        return mailPhoneIndicator;
    }

    /**
     * Setter for MailPhoneIndicator.
     * @param mailPhoneIndicator Value for MailPhoneIndicator
     */
    @JsonSetter("mailPhoneIndicator")
    public void setMailPhoneIndicator(MailPhoneIndicator mailPhoneIndicator) {
        this.mailPhoneIndicator = mailPhoneIndicator;
    }

    /**
     * Getter for OriginType.
     * @return Returns the OriginType
     */
    @JsonGetter("originType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OriginType getOriginType() {
        return originType;
    }

    /**
     * Setter for OriginType.
     * @param originType Value for OriginType
     */
    @JsonSetter("originType")
    public void setOriginType(OriginType originType) {
        this.originType = originType;
    }

    /**
     * Getter for ValidationCode.
     * The validation code for Visa card network transactions.
     * @return Returns the String
     */
    @JsonGetter("validationCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getValidationCode() {
        return validationCode;
    }

    /**
     * Setter for ValidationCode.
     * The validation code for Visa card network transactions.
     * @param validationCode Value for String
     */
    @JsonSetter("validationCode")
    public void setValidationCode(String validationCode) {
        this.validationCode = validationCode;
    }

    /**
     * Getter for PosRegisterNumber.
     * The unique identifier assigned to a point-of-sale terminal for tracking transactions and
     * managing sales data.
     * @return Returns the String
     */
    @JsonGetter("posRegisterNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPosRegisterNumber() {
        return posRegisterNumber;
    }

    /**
     * Setter for PosRegisterNumber.
     * The unique identifier assigned to a point-of-sale terminal for tracking transactions and
     * managing sales data.
     * @param posRegisterNumber Value for String
     */
    @JsonSetter("posRegisterNumber")
    public void setPosRegisterNumber(String posRegisterNumber) {
        this.posRegisterNumber = posRegisterNumber;
    }

    /**
     * Getter for TerminalNumber.
     * The eight-digit sequence of characters used by financial institutions to monitor which
     * terminal is used to process a transaction.
     * @return Returns the String
     */
    @JsonGetter("terminalNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTerminalNumber() {
        return terminalNumber;
    }

    /**
     * Setter for TerminalNumber.
     * The eight-digit sequence of characters used by financial institutions to monitor which
     * terminal is used to process a transaction.
     * @param terminalNumber Value for String
     */
    @JsonSetter("terminalNumber")
    public void setTerminalNumber(String terminalNumber) {
        this.terminalNumber = terminalNumber;
    }

    /**
     * Getter for ReferenceNumber.
     * The key to uniquely identify a card transaction based on the ISO 8583 standard.
     * @return Returns the String
     */
    @JsonGetter("referenceNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Setter for ReferenceNumber.
     * The key to uniquely identify a card transaction based on the ISO 8583 standard.
     * @param referenceNumber Value for String
     */
    @JsonSetter("referenceNumber")
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    /**
     * Getter for DraftLocator.
     * The merchant reference or draft locator number.
     * @return Returns the String
     */
    @JsonGetter("draftLocator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDraftLocator() {
        return draftLocator;
    }

    /**
     * Setter for DraftLocator.
     * The merchant reference or draft locator number.
     * @param draftLocator Value for String
     */
    @JsonSetter("draftLocator")
    public void setDraftLocator(String draftLocator) {
        this.draftLocator = draftLocator;
    }

    /**
     * Getter for TerminalCapability.
     * @return Returns the TerminalCapability
     */
    @JsonGetter("terminalCapability")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TerminalCapability getTerminalCapability() {
        return terminalCapability;
    }

    /**
     * Setter for TerminalCapability.
     * @param terminalCapability Value for TerminalCapability
     */
    @JsonSetter("terminalCapability")
    public void setTerminalCapability(TerminalCapability terminalCapability) {
        this.terminalCapability = terminalCapability;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CreditTransactionDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreditTransactionDetails [" + "transactionId=" + transactionId + ", processDate="
                + processDate + ", transactionDateTime=" + transactionDateTime
                + ", authorizationAmount=" + authorizationAmount + ", approvedAmount="
                + approvedAmount + ", authorizationCode=" + authorizationCode
                + ", authorizationCurrency=" + authorizationCurrency + ", authorizationSource="
                + authorizationSource + ", transactionType=" + transactionType
                + ", transactionStatus=" + transactionStatus + ", entryMode=" + entryMode
                + ", avsResponseCode=" + avsResponseCode + ", cardholderId=" + cardholderId
                + ", sequenceNumber=" + sequenceNumber + ", authorizationIdentifier="
                + authorizationIdentifier + ", customerIdentifier=" + customerIdentifier
                + ", merchantOrderIdentifier=" + merchantOrderIdentifier + ", campaign=" + campaign
                + ", affiliate=" + affiliate + ", merchantGroupingIdentifier="
                + merchantGroupingIdentifier + ", reportGroup=" + reportGroup + ", aci=" + aci
                + ", mailPhoneIndicator=" + mailPhoneIndicator + ", originType=" + originType
                + ", validationCode=" + validationCode + ", posRegisterNumber=" + posRegisterNumber
                + ", terminalNumber=" + terminalNumber + ", referenceNumber=" + referenceNumber
                + ", draftLocator=" + draftLocator + ", terminalCapability=" + terminalCapability
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CreditTransactionDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreditTransactionDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .transactionId(getTransactionId())
                .processDate(getProcessDate())
                .transactionDateTime(getTransactionDateTime())
                .authorizationAmount(getAuthorizationAmount())
                .approvedAmount(getApprovedAmount())
                .authorizationCode(getAuthorizationCode())
                .authorizationCurrency(getAuthorizationCurrency())
                .authorizationSource(getAuthorizationSource())
                .transactionType(getTransactionType())
                .transactionStatus(getTransactionStatus())
                .entryMode(getEntryMode())
                .avsResponseCode(getAvsResponseCode())
                .cardholderId(getCardholderId())
                .sequenceNumber(getSequenceNumber())
                .authorizationIdentifier(getAuthorizationIdentifier())
                .customerIdentifier(getCustomerIdentifier())
                .merchantOrderIdentifier(getMerchantOrderIdentifier())
                .campaign(getCampaign())
                .affiliate(getAffiliate())
                .merchantGroupingIdentifier(getMerchantGroupingIdentifier())
                .reportGroup(getReportGroup())
                .aci(getAci())
                .mailPhoneIndicator(getMailPhoneIndicator())
                .originType(getOriginType())
                .validationCode(getValidationCode())
                .posRegisterNumber(getPosRegisterNumber())
                .terminalNumber(getTerminalNumber())
                .referenceNumber(getReferenceNumber())
                .draftLocator(getDraftLocator())
                .terminalCapability(getTerminalCapability());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CreditTransactionDetails}.
     */
    public static class Builder {
        private String transactionId;
        private LocalDate processDate;
        private LocalDateTime transactionDateTime;
        private Double authorizationAmount;
        private Double approvedAmount;
        private String authorizationCode;
        private AuthorizationCurrency authorizationCurrency;
        private AuthorizationSource authorizationSource;
        private TransactionType transactionType;
        private TransactionStatus transactionStatus;
        private EntryMode entryMode;
        private AvsResponseCode avsResponseCode;
        private CardholderId cardholderId;
        private String sequenceNumber;
        private String authorizationIdentifier;
        private String customerIdentifier;
        private String merchantOrderIdentifier;
        private String campaign;
        private String affiliate;
        private String merchantGroupingIdentifier;
        private String reportGroup;
        private Aci aci;
        private MailPhoneIndicator mailPhoneIndicator;
        private OriginType originType;
        private String validationCode;
        private String posRegisterNumber;
        private String terminalNumber;
        private String referenceNumber;
        private String draftLocator;
        private TerminalCapability terminalCapability;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Setter for processDate.
         * @param  processDate  LocalDate value for processDate.
         * @return Builder
         */
        public Builder processDate(LocalDate processDate) {
            this.processDate = processDate;
            return this;
        }

        /**
         * Setter for transactionDateTime.
         * @param  transactionDateTime  LocalDateTime value for transactionDateTime.
         * @return Builder
         */
        public Builder transactionDateTime(LocalDateTime transactionDateTime) {
            this.transactionDateTime = transactionDateTime;
            return this;
        }

        /**
         * Setter for authorizationAmount.
         * @param  authorizationAmount  Double value for authorizationAmount.
         * @return Builder
         */
        public Builder authorizationAmount(Double authorizationAmount) {
            this.authorizationAmount = authorizationAmount;
            return this;
        }

        /**
         * Setter for approvedAmount.
         * @param  approvedAmount  Double value for approvedAmount.
         * @return Builder
         */
        public Builder approvedAmount(Double approvedAmount) {
            this.approvedAmount = approvedAmount;
            return this;
        }

        /**
         * Setter for authorizationCode.
         * @param  authorizationCode  String value for authorizationCode.
         * @return Builder
         */
        public Builder authorizationCode(String authorizationCode) {
            this.authorizationCode = authorizationCode;
            return this;
        }

        /**
         * Setter for authorizationCurrency.
         * @param  authorizationCurrency  AuthorizationCurrency value for authorizationCurrency.
         * @return Builder
         */
        public Builder authorizationCurrency(AuthorizationCurrency authorizationCurrency) {
            this.authorizationCurrency = authorizationCurrency;
            return this;
        }

        /**
         * Setter for authorizationSource.
         * @param  authorizationSource  AuthorizationSource value for authorizationSource.
         * @return Builder
         */
        public Builder authorizationSource(AuthorizationSource authorizationSource) {
            this.authorizationSource = authorizationSource;
            return this;
        }

        /**
         * Setter for transactionType.
         * @param  transactionType  TransactionType value for transactionType.
         * @return Builder
         */
        public Builder transactionType(TransactionType transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        /**
         * Setter for transactionStatus.
         * @param  transactionStatus  TransactionStatus value for transactionStatus.
         * @return Builder
         */
        public Builder transactionStatus(TransactionStatus transactionStatus) {
            this.transactionStatus = transactionStatus;
            return this;
        }

        /**
         * Setter for entryMode.
         * @param  entryMode  EntryMode value for entryMode.
         * @return Builder
         */
        public Builder entryMode(EntryMode entryMode) {
            this.entryMode = entryMode;
            return this;
        }

        /**
         * Setter for avsResponseCode.
         * @param  avsResponseCode  AvsResponseCode value for avsResponseCode.
         * @return Builder
         */
        public Builder avsResponseCode(AvsResponseCode avsResponseCode) {
            this.avsResponseCode = avsResponseCode;
            return this;
        }

        /**
         * Setter for cardholderId.
         * @param  cardholderId  CardholderId value for cardholderId.
         * @return Builder
         */
        public Builder cardholderId(CardholderId cardholderId) {
            this.cardholderId = cardholderId;
            return this;
        }

        /**
         * Setter for sequenceNumber.
         * @param  sequenceNumber  String value for sequenceNumber.
         * @return Builder
         */
        public Builder sequenceNumber(String sequenceNumber) {
            this.sequenceNumber = sequenceNumber;
            return this;
        }

        /**
         * Setter for authorizationIdentifier.
         * @param  authorizationIdentifier  String value for authorizationIdentifier.
         * @return Builder
         */
        public Builder authorizationIdentifier(String authorizationIdentifier) {
            this.authorizationIdentifier = authorizationIdentifier;
            return this;
        }

        /**
         * Setter for customerIdentifier.
         * @param  customerIdentifier  String value for customerIdentifier.
         * @return Builder
         */
        public Builder customerIdentifier(String customerIdentifier) {
            this.customerIdentifier = customerIdentifier;
            return this;
        }

        /**
         * Setter for merchantOrderIdentifier.
         * @param  merchantOrderIdentifier  String value for merchantOrderIdentifier.
         * @return Builder
         */
        public Builder merchantOrderIdentifier(String merchantOrderIdentifier) {
            this.merchantOrderIdentifier = merchantOrderIdentifier;
            return this;
        }

        /**
         * Setter for campaign.
         * @param  campaign  String value for campaign.
         * @return Builder
         */
        public Builder campaign(String campaign) {
            this.campaign = campaign;
            return this;
        }

        /**
         * Setter for affiliate.
         * @param  affiliate  String value for affiliate.
         * @return Builder
         */
        public Builder affiliate(String affiliate) {
            this.affiliate = affiliate;
            return this;
        }

        /**
         * Setter for merchantGroupingIdentifier.
         * @param  merchantGroupingIdentifier  String value for merchantGroupingIdentifier.
         * @return Builder
         */
        public Builder merchantGroupingIdentifier(String merchantGroupingIdentifier) {
            this.merchantGroupingIdentifier = merchantGroupingIdentifier;
            return this;
        }

        /**
         * Setter for reportGroup.
         * @param  reportGroup  String value for reportGroup.
         * @return Builder
         */
        public Builder reportGroup(String reportGroup) {
            this.reportGroup = reportGroup;
            return this;
        }

        /**
         * Setter for aci.
         * @param  aci  Aci value for aci.
         * @return Builder
         */
        public Builder aci(Aci aci) {
            this.aci = aci;
            return this;
        }

        /**
         * Setter for mailPhoneIndicator.
         * @param  mailPhoneIndicator  MailPhoneIndicator value for mailPhoneIndicator.
         * @return Builder
         */
        public Builder mailPhoneIndicator(MailPhoneIndicator mailPhoneIndicator) {
            this.mailPhoneIndicator = mailPhoneIndicator;
            return this;
        }

        /**
         * Setter for originType.
         * @param  originType  OriginType value for originType.
         * @return Builder
         */
        public Builder originType(OriginType originType) {
            this.originType = originType;
            return this;
        }

        /**
         * Setter for validationCode.
         * @param  validationCode  String value for validationCode.
         * @return Builder
         */
        public Builder validationCode(String validationCode) {
            this.validationCode = validationCode;
            return this;
        }

        /**
         * Setter for posRegisterNumber.
         * @param  posRegisterNumber  String value for posRegisterNumber.
         * @return Builder
         */
        public Builder posRegisterNumber(String posRegisterNumber) {
            this.posRegisterNumber = posRegisterNumber;
            return this;
        }

        /**
         * Setter for terminalNumber.
         * @param  terminalNumber  String value for terminalNumber.
         * @return Builder
         */
        public Builder terminalNumber(String terminalNumber) {
            this.terminalNumber = terminalNumber;
            return this;
        }

        /**
         * Setter for referenceNumber.
         * @param  referenceNumber  String value for referenceNumber.
         * @return Builder
         */
        public Builder referenceNumber(String referenceNumber) {
            this.referenceNumber = referenceNumber;
            return this;
        }

        /**
         * Setter for draftLocator.
         * @param  draftLocator  String value for draftLocator.
         * @return Builder
         */
        public Builder draftLocator(String draftLocator) {
            this.draftLocator = draftLocator;
            return this;
        }

        /**
         * Setter for terminalCapability.
         * @param  terminalCapability  TerminalCapability value for terminalCapability.
         * @return Builder
         */
        public Builder terminalCapability(TerminalCapability terminalCapability) {
            this.terminalCapability = terminalCapability;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CreditTransactionDetails} object using the set fields.
         * @return {@link CreditTransactionDetails}
         */
        public CreditTransactionDetails build() {
            CreditTransactionDetails model =
                    new CreditTransactionDetails(transactionId, processDate, transactionDateTime,
                            authorizationAmount, approvedAmount, authorizationCode,
                            authorizationCurrency, authorizationSource, transactionType,
                            transactionStatus, entryMode, avsResponseCode, cardholderId,
                            sequenceNumber, authorizationIdentifier, customerIdentifier,
                            merchantOrderIdentifier, campaign, affiliate,
                            merchantGroupingIdentifier, reportGroup, aci, mailPhoneIndicator,
                            originType, validationCode, posRegisterNumber, terminalNumber,
                            referenceNumber, draftLocator, terminalCapability);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
