/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CreditMerchantHierarchyDetails type.
 */
public class CreditMerchantHierarchyDetails {
    private Hierarchy10 hierarchy;
    private String alternateMerchantId;
    private String alternateStoreNumber;
    private String merchantName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CreditMerchantHierarchyDetails() {
    }

    /**
     * Initialization constructor.
     * @param  hierarchy  Hierarchy10 value for hierarchy.
     * @param  alternateMerchantId  String value for alternateMerchantId.
     * @param  alternateStoreNumber  String value for alternateStoreNumber.
     * @param  merchantName  String value for merchantName.
     */
    public CreditMerchantHierarchyDetails(
            Hierarchy10 hierarchy,
            String alternateMerchantId,
            String alternateStoreNumber,
            String merchantName) {
        this.hierarchy = hierarchy;
        this.alternateMerchantId = alternateMerchantId;
        this.alternateStoreNumber = alternateStoreNumber;
        this.merchantName = merchantName;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy10
     */
    @JsonGetter("hierarchy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Hierarchy10 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy10
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy10 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for AlternateMerchantId.
     * An alternate 12-16 digit unique identifier assigned to each merchant.
     * @return Returns the String
     */
    @JsonGetter("alternateMerchantId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAlternateMerchantId() {
        return alternateMerchantId;
    }

    /**
     * Setter for AlternateMerchantId.
     * An alternate 12-16 digit unique identifier assigned to each merchant.
     * @param alternateMerchantId Value for String
     */
    @JsonSetter("alternateMerchantId")
    public void setAlternateMerchantId(String alternateMerchantId) {
        this.alternateMerchantId = alternateMerchantId;
    }

    /**
     * Getter for AlternateStoreNumber.
     * Alternate store number is a secondary ID used to uniquely identify a store within a
     * merchant's hierarchy.
     * @return Returns the String
     */
    @JsonGetter("alternateStoreNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAlternateStoreNumber() {
        return alternateStoreNumber;
    }

    /**
     * Setter for AlternateStoreNumber.
     * Alternate store number is a secondary ID used to uniquely identify a store within a
     * merchant's hierarchy.
     * @param alternateStoreNumber Value for String
     */
    @JsonSetter("alternateStoreNumber")
    public void setAlternateStoreNumber(String alternateStoreNumber) {
        this.alternateStoreNumber = alternateStoreNumber;
    }

    /**
     * Getter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @return Returns the String
     */
    @JsonGetter("merchantName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Setter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @param merchantName Value for String
     */
    @JsonSetter("merchantName")
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CreditMerchantHierarchyDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreditMerchantHierarchyDetails [" + "hierarchy=" + hierarchy
                + ", alternateMerchantId=" + alternateMerchantId + ", alternateStoreNumber="
                + alternateStoreNumber + ", merchantName=" + merchantName
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CreditMerchantHierarchyDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreditMerchantHierarchyDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hierarchy(getHierarchy())
                .alternateMerchantId(getAlternateMerchantId())
                .alternateStoreNumber(getAlternateStoreNumber())
                .merchantName(getMerchantName());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CreditMerchantHierarchyDetails}.
     */
    public static class Builder {
        private Hierarchy10 hierarchy;
        private String alternateMerchantId;
        private String alternateStoreNumber;
        private String merchantName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy10 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy10 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for alternateMerchantId.
         * @param  alternateMerchantId  String value for alternateMerchantId.
         * @return Builder
         */
        public Builder alternateMerchantId(String alternateMerchantId) {
            this.alternateMerchantId = alternateMerchantId;
            return this;
        }

        /**
         * Setter for alternateStoreNumber.
         * @param  alternateStoreNumber  String value for alternateStoreNumber.
         * @return Builder
         */
        public Builder alternateStoreNumber(String alternateStoreNumber) {
            this.alternateStoreNumber = alternateStoreNumber;
            return this;
        }

        /**
         * Setter for merchantName.
         * @param  merchantName  String value for merchantName.
         * @return Builder
         */
        public Builder merchantName(String merchantName) {
            this.merchantName = merchantName;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CreditMerchantHierarchyDetails} object using the set fields.
         * @return {@link CreditMerchantHierarchyDetails}
         */
        public CreditMerchantHierarchyDetails build() {
            CreditMerchantHierarchyDetails model =
                    new CreditMerchantHierarchyDetails(hierarchy, alternateMerchantId,
                            alternateStoreNumber, merchantName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
