/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CustomerFields type.
 */
public class CustomerFields {
    private String field1;
    private String field2;
    private String field3;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CustomerFields() {
    }

    /**
     * Initialization constructor.
     * @param  field1  String value for field1.
     * @param  field2  String value for field2.
     * @param  field3  String value for field3.
     */
    public CustomerFields(
            String field1,
            String field2,
            String field3) {
        this.field1 = field1;
        this.field2 = field2;
        this.field3 = field3;
    }

    /**
     * Getter for Field1.
     * Field one for the customer details.
     * @return Returns the String
     */
    @JsonGetter("field1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getField1() {
        return field1;
    }

    /**
     * Setter for Field1.
     * Field one for the customer details.
     * @param field1 Value for String
     */
    @JsonSetter("field1")
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * Getter for Field2.
     * Field two for the customer details.
     * @return Returns the String
     */
    @JsonGetter("field2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getField2() {
        return field2;
    }

    /**
     * Setter for Field2.
     * Field two for the customer details.
     * @param field2 Value for String
     */
    @JsonSetter("field2")
    public void setField2(String field2) {
        this.field2 = field2;
    }

    /**
     * Getter for Field3.
     * Field three for the customer details.
     * @return Returns the String
     */
    @JsonGetter("field3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getField3() {
        return field3;
    }

    /**
     * Setter for Field3.
     * Field three for the customer details.
     * @param field3 Value for String
     */
    @JsonSetter("field3")
    public void setField3(String field3) {
        this.field3 = field3;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CustomerFields into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomerFields [" + "field1=" + field1 + ", field2=" + field2 + ", field3=" + field3
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CustomerFields.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CustomerFields.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .field1(getField1())
                .field2(getField2())
                .field3(getField3());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CustomerFields}.
     */
    public static class Builder {
        private String field1;
        private String field2;
        private String field3;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for field1.
         * @param  field1  String value for field1.
         * @return Builder
         */
        public Builder field1(String field1) {
            this.field1 = field1;
            return this;
        }

        /**
         * Setter for field2.
         * @param  field2  String value for field2.
         * @return Builder
         */
        public Builder field2(String field2) {
            this.field2 = field2;
            return this;
        }

        /**
         * Setter for field3.
         * @param  field3  String value for field3.
         * @return Builder
         */
        public Builder field3(String field3) {
            this.field3 = field3;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CustomerFields} object using the set fields.
         * @return {@link CustomerFields}
         */
        public CustomerFields build() {
            CustomerFields model =
                    new CustomerFields(field1, field2, field3);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
