/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for EmvDetails type.
 */
public class EmvDetails {
    private Boolean transaction;
    private Boolean offlineTransaction;
    private Boolean cardCapable;
    private Boolean termCapable;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public EmvDetails() {
    }

    /**
     * Initialization constructor.
     * @param  transaction  Boolean value for transaction.
     * @param  offlineTransaction  Boolean value for offlineTransaction.
     * @param  cardCapable  Boolean value for cardCapable.
     * @param  termCapable  Boolean value for termCapable.
     */
    public EmvDetails(
            Boolean transaction,
            Boolean offlineTransaction,
            Boolean cardCapable,
            Boolean termCapable) {
        this.transaction = transaction;
        this.offlineTransaction = offlineTransaction;
        this.cardCapable = cardCapable;
        this.termCapable = termCapable;
    }

    /**
     * Getter for Transaction.
     * True means the transaction is EMV. &lt;br&gt; False means the transaction is EMV fallback.
     * @return Returns the Boolean
     */
    @JsonGetter("transaction")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getTransaction() {
        return transaction;
    }

    /**
     * Setter for Transaction.
     * True means the transaction is EMV. &lt;br&gt; False means the transaction is EMV fallback.
     * @param transaction Value for Boolean
     */
    @JsonSetter("transaction")
    public void setTransaction(Boolean transaction) {
        this.transaction = transaction;
    }

    /**
     * Getter for OfflineTransaction.
     * True means the transaction didn't go out to the network for authorization. &lt;br&gt; False means
     * the transaction did go out to the network for authorization.
     * @return Returns the Boolean
     */
    @JsonGetter("offlineTransaction")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getOfflineTransaction() {
        return offlineTransaction;
    }

    /**
     * Setter for OfflineTransaction.
     * True means the transaction didn't go out to the network for authorization. &lt;br&gt; False means
     * the transaction did go out to the network for authorization.
     * @param offlineTransaction Value for Boolean
     */
    @JsonSetter("offlineTransaction")
    public void setOfflineTransaction(Boolean offlineTransaction) {
        this.offlineTransaction = offlineTransaction;
    }

    /**
     * Getter for CardCapable.
     * True means the card is an EMV capable card. &lt;br&gt; False means the card is not an EMV capable
     * card.
     * @return Returns the Boolean
     */
    @JsonGetter("cardCapable")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCardCapable() {
        return cardCapable;
    }

    /**
     * Setter for CardCapable.
     * True means the card is an EMV capable card. &lt;br&gt; False means the card is not an EMV capable
     * card.
     * @param cardCapable Value for Boolean
     */
    @JsonSetter("cardCapable")
    public void setCardCapable(Boolean cardCapable) {
        this.cardCapable = cardCapable;
    }

    /**
     * Getter for TermCapable.
     * True means the terminal is EMV capable. &lt;br&gt; False means the terminal is not EMV capable.
     * @return Returns the Boolean
     */
    @JsonGetter("termCapable")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getTermCapable() {
        return termCapable;
    }

    /**
     * Setter for TermCapable.
     * True means the terminal is EMV capable. &lt;br&gt; False means the terminal is not EMV capable.
     * @param termCapable Value for Boolean
     */
    @JsonSetter("termCapable")
    public void setTermCapable(Boolean termCapable) {
        this.termCapable = termCapable;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this EmvDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EmvDetails [" + "transaction=" + transaction + ", offlineTransaction="
                + offlineTransaction + ", cardCapable=" + cardCapable + ", termCapable="
                + termCapable + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link EmvDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EmvDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .transaction(getTransaction())
                .offlineTransaction(getOfflineTransaction())
                .cardCapable(getCardCapable())
                .termCapable(getTermCapable());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link EmvDetails}.
     */
    public static class Builder {
        private Boolean transaction;
        private Boolean offlineTransaction;
        private Boolean cardCapable;
        private Boolean termCapable;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for transaction.
         * @param  transaction  Boolean value for transaction.
         * @return Builder
         */
        public Builder transaction(Boolean transaction) {
            this.transaction = transaction;
            return this;
        }

        /**
         * Setter for offlineTransaction.
         * @param  offlineTransaction  Boolean value for offlineTransaction.
         * @return Builder
         */
        public Builder offlineTransaction(Boolean offlineTransaction) {
            this.offlineTransaction = offlineTransaction;
            return this;
        }

        /**
         * Setter for cardCapable.
         * @param  cardCapable  Boolean value for cardCapable.
         * @return Builder
         */
        public Builder cardCapable(Boolean cardCapable) {
            this.cardCapable = cardCapable;
            return this;
        }

        /**
         * Setter for termCapable.
         * @param  termCapable  Boolean value for termCapable.
         * @return Builder
         */
        public Builder termCapable(Boolean termCapable) {
            this.termCapable = termCapable;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link EmvDetails} object using the set fields.
         * @return {@link EmvDetails}
         */
        public EmvDetails build() {
            EmvDetails model =
                    new EmvDetails(transaction, offlineTransaction, cardCapable, termCapable);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
