/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * FieldName1 to be used.
 */
public enum FieldName1 {
    BATCH_NUMBER,

    TRANSACTION_DATE,

    PROCESS_DATE,

    CARD_TYPE,

    CHAIN_CODE,

    MERCHANT_NAME,

    MERCHANT_ID,

    AUTHORIZATION_AMOUNT,

    SALES_COUNT,

    RETURNS_COUNT,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, FieldName1> valueMap = new TreeMap<>();
    private String value;

    static {
        BATCH_NUMBER.value = "BATCH_NUMBER";
        TRANSACTION_DATE.value = "TRANSACTION_DATE";
        PROCESS_DATE.value = "PROCESS_DATE";
        CARD_TYPE.value = "CARD_TYPE";
        CHAIN_CODE.value = "CHAIN_CODE";
        MERCHANT_NAME.value = "MERCHANT_NAME";
        MERCHANT_ID.value = "MERCHANT_ID";
        AUTHORIZATION_AMOUNT.value = "AUTHORIZATION_AMOUNT";
        SALES_COUNT.value = "SALES_COUNT";
        RETURNS_COUNT.value = "RETURNS_COUNT";
        _UNKNOWN.value = null;

        valueMap.put("BATCH_NUMBER", BATCH_NUMBER);
        valueMap.put("TRANSACTION_DATE", TRANSACTION_DATE);
        valueMap.put("PROCESS_DATE", PROCESS_DATE);
        valueMap.put("CARD_TYPE", CARD_TYPE);
        valueMap.put("CHAIN_CODE", CHAIN_CODE);
        valueMap.put("MERCHANT_NAME", MERCHANT_NAME);
        valueMap.put("MERCHANT_ID", MERCHANT_ID);
        valueMap.put("AUTHORIZATION_AMOUNT", AUTHORIZATION_AMOUNT);
        valueMap.put("SALES_COUNT", SALES_COUNT);
        valueMap.put("RETURNS_COUNT", RETURNS_COUNT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static FieldName1 constructFromString(String toConvert) throws IOException {
        FieldName1 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static FieldName1 fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of FieldName1 values to list of string values.
     * @param toConvert The list of FieldName1 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<FieldName1> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (FieldName1 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 