/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for FraudFields type.
 */
public class FraudFields {
    private FraudScore fraudScore;
    private FraudResponseCode fraudResponseCode;
    private FraudRuleResult fraudRuleResult;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FraudFields() {
    }

    /**
     * Initialization constructor.
     * @param  fraudScore  FraudScore value for fraudScore.
     * @param  fraudResponseCode  FraudResponseCode value for fraudResponseCode.
     * @param  fraudRuleResult  FraudRuleResult value for fraudRuleResult.
     */
    public FraudFields(
            FraudScore fraudScore,
            FraudResponseCode fraudResponseCode,
            FraudRuleResult fraudRuleResult) {
        this.fraudScore = fraudScore;
        this.fraudResponseCode = fraudResponseCode;
        this.fraudRuleResult = fraudRuleResult;
    }

    /**
     * Getter for FraudScore.
     * @return Returns the FraudScore
     */
    @JsonGetter("fraudScore")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudScore getFraudScore() {
        return fraudScore;
    }

    /**
     * Setter for FraudScore.
     * @param fraudScore Value for FraudScore
     */
    @JsonSetter("fraudScore")
    public void setFraudScore(FraudScore fraudScore) {
        this.fraudScore = fraudScore;
    }

    /**
     * Getter for FraudResponseCode.
     * @return Returns the FraudResponseCode
     */
    @JsonGetter("fraudResponseCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudResponseCode getFraudResponseCode() {
        return fraudResponseCode;
    }

    /**
     * Setter for FraudResponseCode.
     * @param fraudResponseCode Value for FraudResponseCode
     */
    @JsonSetter("fraudResponseCode")
    public void setFraudResponseCode(FraudResponseCode fraudResponseCode) {
        this.fraudResponseCode = fraudResponseCode;
    }

    /**
     * Getter for FraudRuleResult.
     * @return Returns the FraudRuleResult
     */
    @JsonGetter("fraudRuleResult")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudRuleResult getFraudRuleResult() {
        return fraudRuleResult;
    }

    /**
     * Setter for FraudRuleResult.
     * @param fraudRuleResult Value for FraudRuleResult
     */
    @JsonSetter("fraudRuleResult")
    public void setFraudRuleResult(FraudRuleResult fraudRuleResult) {
        this.fraudRuleResult = fraudRuleResult;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FraudFields into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FraudFields [" + "fraudScore=" + fraudScore + ", fraudResponseCode="
                + fraudResponseCode + ", fraudRuleResult=" + fraudRuleResult
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FraudFields.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FraudFields.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fraudScore(getFraudScore())
                .fraudResponseCode(getFraudResponseCode())
                .fraudRuleResult(getFraudRuleResult());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FraudFields}.
     */
    public static class Builder {
        private FraudScore fraudScore;
        private FraudResponseCode fraudResponseCode;
        private FraudRuleResult fraudRuleResult;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for fraudScore.
         * @param  fraudScore  FraudScore value for fraudScore.
         * @return Builder
         */
        public Builder fraudScore(FraudScore fraudScore) {
            this.fraudScore = fraudScore;
            return this;
        }

        /**
         * Setter for fraudResponseCode.
         * @param  fraudResponseCode  FraudResponseCode value for fraudResponseCode.
         * @return Builder
         */
        public Builder fraudResponseCode(FraudResponseCode fraudResponseCode) {
            this.fraudResponseCode = fraudResponseCode;
            return this;
        }

        /**
         * Setter for fraudRuleResult.
         * @param  fraudRuleResult  FraudRuleResult value for fraudRuleResult.
         * @return Builder
         */
        public Builder fraudRuleResult(FraudRuleResult fraudRuleResult) {
            this.fraudRuleResult = fraudRuleResult;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FraudFields} object using the set fields.
         * @return {@link FraudFields}
         */
        public FraudFields build() {
            FraudFields model =
                    new FraudFields(fraudScore, fraudResponseCode, fraudRuleResult);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
