/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for FundedNetSettle2 type.
 */
public class FundedNetSettle2 {
    private Double processorAmount;
    private Integer processorCount;
    private Double otherAmount;
    private Integer otherCount;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FundedNetSettle2() {
    }

    /**
     * Initialization constructor.
     * @param  processorAmount  Double value for processorAmount.
     * @param  processorCount  Integer value for processorCount.
     * @param  otherAmount  Double value for otherAmount.
     * @param  otherCount  Integer value for otherCount.
     */
    public FundedNetSettle2(
            Double processorAmount,
            Integer processorCount,
            Double otherAmount,
            Integer otherCount) {
        this.processorAmount = processorAmount;
        this.processorCount = processorCount;
        this.otherAmount = otherAmount;
        this.otherCount = otherCount;
    }

    /**
     * Getter for ProcessorAmount.
     * The final funds transferred to merchant accounts after processing fees deductions.
     * @return Returns the Double
     */
    @JsonGetter("processorAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getProcessorAmount() {
        return processorAmount;
    }

    /**
     * Setter for ProcessorAmount.
     * The final funds transferred to merchant accounts after processing fees deductions.
     * @param processorAmount Value for Double
     */
    @JsonSetter("processorAmount")
    public void setProcessorAmount(Double processorAmount) {
        this.processorAmount = processorAmount;
    }

    /**
     * Getter for ProcessorCount.
     * The payment method based on processing capacity for settlements.
     * @return Returns the Integer
     */
    @JsonGetter("processorCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getProcessorCount() {
        return processorCount;
    }

    /**
     * Setter for ProcessorCount.
     * The payment method based on processing capacity for settlements.
     * @param processorCount Value for Integer
     */
    @JsonSetter("processorCount")
    public void setProcessorCount(Integer processorCount) {
        this.processorCount = processorCount;
    }

    /**
     * Getter for OtherAmount.
     * The final transaction balance after deducting external funding sources.
     * @return Returns the Double
     */
    @JsonGetter("otherAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getOtherAmount() {
        return otherAmount;
    }

    /**
     * Setter for OtherAmount.
     * The final transaction balance after deducting external funding sources.
     * @param otherAmount Value for Double
     */
    @JsonSetter("otherAmount")
    public void setOtherAmount(Double otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * Getter for OtherCount.
     * The amount of financial transactions settled through external sources.
     * @return Returns the Integer
     */
    @JsonGetter("otherCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getOtherCount() {
        return otherCount;
    }

    /**
     * Setter for OtherCount.
     * The amount of financial transactions settled through external sources.
     * @param otherCount Value for Integer
     */
    @JsonSetter("otherCount")
    public void setOtherCount(Integer otherCount) {
        this.otherCount = otherCount;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FundedNetSettle2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FundedNetSettle2 [" + "processorAmount=" + processorAmount + ", processorCount="
                + processorCount + ", otherAmount=" + otherAmount + ", otherCount=" + otherCount
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FundedNetSettle2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FundedNetSettle2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .processorAmount(getProcessorAmount())
                .processorCount(getProcessorCount())
                .otherAmount(getOtherAmount())
                .otherCount(getOtherCount());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FundedNetSettle2}.
     */
    public static class Builder {
        private Double processorAmount;
        private Integer processorCount;
        private Double otherAmount;
        private Integer otherCount;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for processorAmount.
         * @param  processorAmount  Double value for processorAmount.
         * @return Builder
         */
        public Builder processorAmount(Double processorAmount) {
            this.processorAmount = processorAmount;
            return this;
        }

        /**
         * Setter for processorCount.
         * @param  processorCount  Integer value for processorCount.
         * @return Builder
         */
        public Builder processorCount(Integer processorCount) {
            this.processorCount = processorCount;
            return this;
        }

        /**
         * Setter for otherAmount.
         * @param  otherAmount  Double value for otherAmount.
         * @return Builder
         */
        public Builder otherAmount(Double otherAmount) {
            this.otherAmount = otherAmount;
            return this;
        }

        /**
         * Setter for otherCount.
         * @param  otherCount  Integer value for otherCount.
         * @return Builder
         */
        public Builder otherCount(Integer otherCount) {
            this.otherCount = otherCount;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FundedNetSettle2} object using the set fields.
         * @return {@link FundedNetSettle2}
         */
        public FundedNetSettle2 build() {
            FundedNetSettle2 model =
                    new FundedNetSettle2(processorAmount, processorCount, otherAmount, otherCount);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
