/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Hierarchy type.
 */
public class Hierarchy {
    private Level level;
    private List<String> values;
    private String chainCode;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Hierarchy() {
    }

    /**
     * Initialization constructor.
     * @param  level  Level value for level.
     * @param  values  List of String value for values.
     * @param  chainCode  String value for chainCode.
     */
    public Hierarchy(
            Level level,
            List<String> values,
            String chainCode) {
        this.level = level;
        this.values = values;
        this.chainCode = chainCode;
    }

    /**
     * Getter for Level.
     * @return Returns the Level
     */
    @JsonGetter("level")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Level getLevel() {
        return level;
    }

    /**
     * Setter for Level.
     * @param level Value for Level
     */
    @JsonSetter("level")
    public void setLevel(Level level) {
        this.level = level;
    }

    /**
     * Getter for Values.
     * The values of the hierarchy levels.
     * @return Returns the List of String
     */
    @JsonGetter("values")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getValues() {
        return values;
    }

    /**
     * Setter for Values.
     * The values of the hierarchy levels.
     * @param values Value for List of String
     */
    @JsonSetter("values")
    public void setValues(List<String> values) {
        this.values = values;
    }

    /**
     * Getter for ChainCode.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related
     * roll-up values under a common identifier for settlement, billing, and reporting. Chain Code
     * is the primary identifier for merchants boarded in MDB (Merchant Database) system. &lt;br&gt; Chain
     * Code is mandatory when the level is store or division.
     * @return Returns the String
     */
    @JsonGetter("chainCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChainCode() {
        return chainCode;
    }

    /**
     * Setter for ChainCode.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related
     * roll-up values under a common identifier for settlement, billing, and reporting. Chain Code
     * is the primary identifier for merchants boarded in MDB (Merchant Database) system. &lt;br&gt; Chain
     * Code is mandatory when the level is store or division.
     * @param chainCode Value for String
     */
    @JsonSetter("chainCode")
    public void setChainCode(String chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Hierarchy into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Hierarchy [" + "level=" + level + ", values=" + values + ", chainCode=" + chainCode
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Hierarchy.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Hierarchy.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .level(getLevel())
                .values(getValues())
                .chainCode(getChainCode());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Hierarchy}.
     */
    public static class Builder {
        private Level level;
        private List<String> values;
        private String chainCode;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for level.
         * @param  level  Level value for level.
         * @return Builder
         */
        public Builder level(Level level) {
            this.level = level;
            return this;
        }

        /**
         * Setter for values.
         * @param  values  List of String value for values.
         * @return Builder
         */
        public Builder values(List<String> values) {
            this.values = values;
            return this;
        }

        /**
         * Setter for chainCode.
         * @param  chainCode  String value for chainCode.
         * @return Builder
         */
        public Builder chainCode(String chainCode) {
            this.chainCode = chainCode;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Hierarchy} object using the set fields.
         * @return {@link Hierarchy}
         */
        public Hierarchy build() {
            Hierarchy model =
                    new Hierarchy(level, values, chainCode);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
