/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Hierarchy4 type.
 */
public class Hierarchy4 {
    private String storeNumber;
    private String merchantId;
    private String chainName;
    private String merchantName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Hierarchy4() {
    }

    /**
     * Initialization constructor.
     * @param  storeNumber  String value for storeNumber.
     * @param  merchantId  String value for merchantId.
     * @param  chainName  String value for chainName.
     * @param  merchantName  String value for merchantName.
     */
    public Hierarchy4(
            String storeNumber,
            String merchantId,
            String chainName,
            String merchantName) {
        this.storeNumber = storeNumber;
        this.merchantId = merchantId;
        this.chainName = chainName;
        this.merchantName = merchantName;
    }

    /**
     * Getter for StoreNumber.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers
     * (MIDs) used in a single merchant location. The Store/Locations are used to link multiple
     * merchant numbers assigned to different terminals and/or business lines (MCC’s). A Store
     * Number is nine digits and unique to a particular Chain.
     * @return Returns the String
     */
    @JsonGetter("storeNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * Setter for StoreNumber.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers
     * (MIDs) used in a single merchant location. The Store/Locations are used to link multiple
     * merchant numbers assigned to different terminals and/or business lines (MCC’s). A Store
     * Number is nine digits and unique to a particular Chain.
     * @param storeNumber Value for String
     */
    @JsonSetter("storeNumber")
    public void setStoreNumber(String storeNumber) {
        this.storeNumber = storeNumber;
    }

    /**
     * Getter for MerchantId.
     * The identifier code associated with a given merchant under a Store-level hierarchy.
     * @return Returns the String
     */
    @JsonGetter("merchantId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Setter for MerchantId.
     * The identifier code associated with a given merchant under a Store-level hierarchy.
     * @param merchantId Value for String
     */
    @JsonSetter("merchantId")
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * Getter for ChainName.
     * The name associated with a given merchant under a chain-level hierarchy.
     * @return Returns the String
     */
    @JsonGetter("chainName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChainName() {
        return chainName;
    }

    /**
     * Setter for ChainName.
     * The name associated with a given merchant under a chain-level hierarchy.
     * @param chainName Value for String
     */
    @JsonSetter("chainName")
    public void setChainName(String chainName) {
        this.chainName = chainName;
    }

    /**
     * Getter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @return Returns the String
     */
    @JsonGetter("merchantName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Setter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @param merchantName Value for String
     */
    @JsonSetter("merchantName")
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Hierarchy4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Hierarchy4 [" + "storeNumber=" + storeNumber + ", merchantId=" + merchantId
                + ", chainName=" + chainName + ", merchantName=" + merchantName
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Hierarchy4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Hierarchy4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .storeNumber(getStoreNumber())
                .merchantId(getMerchantId())
                .chainName(getChainName())
                .merchantName(getMerchantName());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Hierarchy4}.
     */
    public static class Builder {
        private String storeNumber;
        private String merchantId;
        private String chainName;
        private String merchantName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for storeNumber.
         * @param  storeNumber  String value for storeNumber.
         * @return Builder
         */
        public Builder storeNumber(String storeNumber) {
            this.storeNumber = storeNumber;
            return this;
        }

        /**
         * Setter for merchantId.
         * @param  merchantId  String value for merchantId.
         * @return Builder
         */
        public Builder merchantId(String merchantId) {
            this.merchantId = merchantId;
            return this;
        }

        /**
         * Setter for chainName.
         * @param  chainName  String value for chainName.
         * @return Builder
         */
        public Builder chainName(String chainName) {
            this.chainName = chainName;
            return this;
        }

        /**
         * Setter for merchantName.
         * @param  merchantName  String value for merchantName.
         * @return Builder
         */
        public Builder merchantName(String merchantName) {
            this.merchantName = merchantName;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Hierarchy4} object using the set fields.
         * @return {@link Hierarchy4}
         */
        public Hierarchy4 build() {
            Hierarchy4 model =
                    new Hierarchy4(storeNumber, merchantId, chainName, merchantName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
