/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Level1 to be used.
 */
public enum Level1 {
    MERCHANT,

    STORE,

    DIVISION,

    CHAIN,

    SUPER_CHAIN,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, Level1> valueMap = new TreeMap<>();
    private String value;

    static {
        MERCHANT.value = "MERCHANT";
        STORE.value = "STORE";
        DIVISION.value = "DIVISION";
        CHAIN.value = "CHAIN";
        SUPER_CHAIN.value = "SUPER_CHAIN";
        _UNKNOWN.value = null;

        valueMap.put("MERCHANT", MERCHANT);
        valueMap.put("STORE", STORE);
        valueMap.put("DIVISION", DIVISION);
        valueMap.put("CHAIN", CHAIN);
        valueMap.put("SUPER_CHAIN", SUPER_CHAIN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Level1 constructFromString(String toConvert) throws IOException {
        Level1 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Level1 fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of Level1 values to list of string values.
     * @param toConvert The list of Level1 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Level1> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Level1 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 