/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for MerchantInfo type.
 */
public class MerchantInfo {
    private String chainCode;
    private String divisionNumber;
    private String storeNumber;
    private String merchantId;
    private String alternateMerchantId;
    private String merchantName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public MerchantInfo() {
    }

    /**
     * Initialization constructor.
     * @param  chainCode  String value for chainCode.
     * @param  divisionNumber  String value for divisionNumber.
     * @param  storeNumber  String value for storeNumber.
     * @param  merchantId  String value for merchantId.
     * @param  alternateMerchantId  String value for alternateMerchantId.
     * @param  merchantName  String value for merchantName.
     */
    public MerchantInfo(
            String chainCode,
            String divisionNumber,
            String storeNumber,
            String merchantId,
            String alternateMerchantId,
            String merchantName) {
        this.chainCode = chainCode;
        this.divisionNumber = divisionNumber;
        this.storeNumber = storeNumber;
        this.merchantId = merchantId;
        this.alternateMerchantId = alternateMerchantId;
        this.merchantName = merchantName;
    }

    /**
     * Getter for ChainCode.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related
     * roll-up values under a common identifier for settlement, billing, and reporting. Chain Code
     * is the primary identifier for merchants boarded in MDB (Merchant Database) system.
     * @return Returns the String
     */
    @JsonGetter("chainCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChainCode() {
        return chainCode;
    }

    /**
     * Setter for ChainCode.
     * The level of the merchant hierarchy that groups merchant identifiers (MIDs) and any related
     * roll-up values under a common identifier for settlement, billing, and reporting. Chain Code
     * is the primary identifier for merchants boarded in MDB (Merchant Database) system.
     * @param chainCode Value for String
     */
    @JsonSetter("chainCode")
    public void setChainCode(String chainCode) {
        this.chainCode = chainCode;
    }

    /**
     * Getter for DivisionNumber.
     * The hierarchy level that enables merchants to roll-up child entities for Stores/Locations
     * into different groups under a Chain. The Division Code is an optional hierarchy level, but if
     * created, is required for all child entities under the Division Number."
     * @return Returns the String
     */
    @JsonGetter("divisionNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDivisionNumber() {
        return divisionNumber;
    }

    /**
     * Setter for DivisionNumber.
     * The hierarchy level that enables merchants to roll-up child entities for Stores/Locations
     * into different groups under a Chain. The Division Code is an optional hierarchy level, but if
     * created, is required for all child entities under the Division Number."
     * @param divisionNumber Value for String
     */
    @JsonSetter("divisionNumber")
    public void setDivisionNumber(String divisionNumber) {
        this.divisionNumber = divisionNumber;
    }

    /**
     * Getter for StoreNumber.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers
     * (MIDs) used in a single merchant location. The Store/Locations are used to link multiple
     * merchant numbers assigned to different terminals and/or business lines (MCC’s).
     * @return Returns the String
     */
    @JsonGetter("storeNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * Setter for StoreNumber.
     * The lowest roll-up level in the hierarchy system, grouping multiple merchant account numbers
     * (MIDs) used in a single merchant location. The Store/Locations are used to link multiple
     * merchant numbers assigned to different terminals and/or business lines (MCC’s).
     * @param storeNumber Value for String
     */
    @JsonSetter("storeNumber")
    public void setStoreNumber(String storeNumber) {
        this.storeNumber = storeNumber;
    }

    /**
     * Getter for MerchantId.
     * The identifier code associated with a given merchant under a Store-level hierarchy.
     * @return Returns the String
     */
    @JsonGetter("merchantId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Setter for MerchantId.
     * The identifier code associated with a given merchant under a Store-level hierarchy.
     * @param merchantId Value for String
     */
    @JsonSetter("merchantId")
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * Getter for AlternateMerchantId.
     * The lowest level in the Merchant Hierarchy structure.
     * @return Returns the String
     */
    @JsonGetter("alternateMerchantId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAlternateMerchantId() {
        return alternateMerchantId;
    }

    /**
     * Setter for AlternateMerchantId.
     * The lowest level in the Merchant Hierarchy structure.
     * @param alternateMerchantId Value for String
     */
    @JsonSetter("alternateMerchantId")
    public void setAlternateMerchantId(String alternateMerchantId) {
        this.alternateMerchantId = alternateMerchantId;
    }

    /**
     * Getter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @return Returns the String
     */
    @JsonGetter("merchantName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Setter for MerchantName.
     * The name of a business or registered name of the company or entity operating the business.
     * @param merchantName Value for String
     */
    @JsonSetter("merchantName")
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this MerchantInfo into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MerchantInfo [" + "chainCode=" + chainCode + ", divisionNumber=" + divisionNumber
                + ", storeNumber=" + storeNumber + ", merchantId=" + merchantId
                + ", alternateMerchantId=" + alternateMerchantId + ", merchantName=" + merchantName
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link MerchantInfo.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MerchantInfo.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .chainCode(getChainCode())
                .divisionNumber(getDivisionNumber())
                .storeNumber(getStoreNumber())
                .merchantId(getMerchantId())
                .alternateMerchantId(getAlternateMerchantId())
                .merchantName(getMerchantName());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link MerchantInfo}.
     */
    public static class Builder {
        private String chainCode;
        private String divisionNumber;
        private String storeNumber;
        private String merchantId;
        private String alternateMerchantId;
        private String merchantName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for chainCode.
         * @param  chainCode  String value for chainCode.
         * @return Builder
         */
        public Builder chainCode(String chainCode) {
            this.chainCode = chainCode;
            return this;
        }

        /**
         * Setter for divisionNumber.
         * @param  divisionNumber  String value for divisionNumber.
         * @return Builder
         */
        public Builder divisionNumber(String divisionNumber) {
            this.divisionNumber = divisionNumber;
            return this;
        }

        /**
         * Setter for storeNumber.
         * @param  storeNumber  String value for storeNumber.
         * @return Builder
         */
        public Builder storeNumber(String storeNumber) {
            this.storeNumber = storeNumber;
            return this;
        }

        /**
         * Setter for merchantId.
         * @param  merchantId  String value for merchantId.
         * @return Builder
         */
        public Builder merchantId(String merchantId) {
            this.merchantId = merchantId;
            return this;
        }

        /**
         * Setter for alternateMerchantId.
         * @param  alternateMerchantId  String value for alternateMerchantId.
         * @return Builder
         */
        public Builder alternateMerchantId(String alternateMerchantId) {
            this.alternateMerchantId = alternateMerchantId;
            return this;
        }

        /**
         * Setter for merchantName.
         * @param  merchantName  String value for merchantName.
         * @return Builder
         */
        public Builder merchantName(String merchantName) {
            this.merchantName = merchantName;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link MerchantInfo} object using the set fields.
         * @return {@link MerchantInfo}
         */
        public MerchantInfo build() {
            MerchantInfo model =
                    new MerchantInfo(chainCode, divisionNumber, storeNumber, merchantId,
                            alternateMerchantId, merchantName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
