/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for OrderByForSettledDailyTotals type.
 */
public class OrderByForSettledDailyTotals {
    private FieldName1 fieldName;
    private OrderBy orderBy;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public OrderByForSettledDailyTotals() {
    }

    /**
     * Initialization constructor.
     * @param  fieldName  FieldName1 value for fieldName.
     * @param  orderBy  OrderBy value for orderBy.
     */
    public OrderByForSettledDailyTotals(
            FieldName1 fieldName,
            OrderBy orderBy) {
        this.fieldName = fieldName;
        this.orderBy = orderBy;
    }

    /**
     * Getter for FieldName.
     * @return Returns the FieldName1
     */
    @JsonGetter("fieldName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FieldName1 getFieldName() {
        return fieldName;
    }

    /**
     * Setter for FieldName.
     * @param fieldName Value for FieldName1
     */
    @JsonSetter("fieldName")
    public void setFieldName(FieldName1 fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * Getter for OrderBy.
     * @return Returns the OrderBy
     */
    @JsonGetter("orderBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OrderBy getOrderBy() {
        return orderBy;
    }

    /**
     * Setter for OrderBy.
     * @param orderBy Value for OrderBy
     */
    @JsonSetter("orderBy")
    public void setOrderBy(OrderBy orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this OrderByForSettledDailyTotals into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrderByForSettledDailyTotals [" + "fieldName=" + fieldName + ", orderBy=" + orderBy
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link OrderByForSettledDailyTotals.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrderByForSettledDailyTotals.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fieldName(getFieldName())
                .orderBy(getOrderBy());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link OrderByForSettledDailyTotals}.
     */
    public static class Builder {
        private FieldName1 fieldName;
        private OrderBy orderBy;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for fieldName.
         * @param  fieldName  FieldName1 value for fieldName.
         * @return Builder
         */
        public Builder fieldName(FieldName1 fieldName) {
            this.fieldName = fieldName;
            return this;
        }

        /**
         * Setter for orderBy.
         * @param  orderBy  OrderBy value for orderBy.
         * @return Builder
         */
        public Builder orderBy(OrderBy orderBy) {
            this.orderBy = orderBy;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link OrderByForSettledDailyTotals} object using the set fields.
         * @return {@link OrderByForSettledDailyTotals}
         */
        public OrderByForSettledDailyTotals build() {
            OrderByForSettledDailyTotals model =
                    new OrderByForSettledDailyTotals(fieldName, orderBy);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
