/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for OtherServices type.
 */
public class OtherServices {
    private LevelIndicator levelIndicator;
    private String reAuthorizationAttemptsCount;
    private SignatureCapabilitiesIndicator signatureCapabilitiesIndicator;
    private SignatureCompression signatureCompression;
    private String signatureEncryptKey;
    private String signatureEncryptMethod;
    private SignaturePen signaturePen;
    private StandInIndicator standInIndicator;
    private StandInLevel standInLevel;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public OtherServices() {
    }

    /**
     * Initialization constructor.
     * @param  levelIndicator  LevelIndicator value for levelIndicator.
     * @param  reAuthorizationAttemptsCount  String value for reAuthorizationAttemptsCount.
     * @param  signatureCapabilitiesIndicator  SignatureCapabilitiesIndicator value for
     *         signatureCapabilitiesIndicator.
     * @param  signatureCompression  SignatureCompression value for signatureCompression.
     * @param  signatureEncryptKey  String value for signatureEncryptKey.
     * @param  signatureEncryptMethod  String value for signatureEncryptMethod.
     * @param  signaturePen  SignaturePen value for signaturePen.
     * @param  standInIndicator  StandInIndicator value for standInIndicator.
     * @param  standInLevel  StandInLevel value for standInLevel.
     */
    public OtherServices(
            LevelIndicator levelIndicator,
            String reAuthorizationAttemptsCount,
            SignatureCapabilitiesIndicator signatureCapabilitiesIndicator,
            SignatureCompression signatureCompression,
            String signatureEncryptKey,
            String signatureEncryptMethod,
            SignaturePen signaturePen,
            StandInIndicator standInIndicator,
            StandInLevel standInLevel) {
        this.levelIndicator = levelIndicator;
        this.reAuthorizationAttemptsCount = reAuthorizationAttemptsCount;
        this.signatureCapabilitiesIndicator = signatureCapabilitiesIndicator;
        this.signatureCompression = signatureCompression;
        this.signatureEncryptKey = signatureEncryptKey;
        this.signatureEncryptMethod = signatureEncryptMethod;
        this.signaturePen = signaturePen;
        this.standInIndicator = standInIndicator;
        this.standInLevel = standInLevel;
    }

    /**
     * Getter for LevelIndicator.
     * @return Returns the LevelIndicator
     */
    @JsonGetter("levelIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LevelIndicator getLevelIndicator() {
        return levelIndicator;
    }

    /**
     * Setter for LevelIndicator.
     * @param levelIndicator Value for LevelIndicator
     */
    @JsonSetter("levelIndicator")
    public void setLevelIndicator(LevelIndicator levelIndicator) {
        this.levelIndicator = levelIndicator;
    }

    /**
     * Getter for ReAuthorizationAttemptsCount.
     * The number of times reauthorization has been attempted.
     * @return Returns the String
     */
    @JsonGetter("reAuthorizationAttemptsCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReAuthorizationAttemptsCount() {
        return reAuthorizationAttemptsCount;
    }

    /**
     * Setter for ReAuthorizationAttemptsCount.
     * The number of times reauthorization has been attempted.
     * @param reAuthorizationAttemptsCount Value for String
     */
    @JsonSetter("reAuthorizationAttemptsCount")
    public void setReAuthorizationAttemptsCount(String reAuthorizationAttemptsCount) {
        this.reAuthorizationAttemptsCount = reAuthorizationAttemptsCount;
    }

    /**
     * Getter for SignatureCapabilitiesIndicator.
     * @return Returns the SignatureCapabilitiesIndicator
     */
    @JsonGetter("signatureCapabilitiesIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SignatureCapabilitiesIndicator getSignatureCapabilitiesIndicator() {
        return signatureCapabilitiesIndicator;
    }

    /**
     * Setter for SignatureCapabilitiesIndicator.
     * @param signatureCapabilitiesIndicator Value for SignatureCapabilitiesIndicator
     */
    @JsonSetter("signatureCapabilitiesIndicator")
    public void setSignatureCapabilitiesIndicator(SignatureCapabilitiesIndicator signatureCapabilitiesIndicator) {
        this.signatureCapabilitiesIndicator = signatureCapabilitiesIndicator;
    }

    /**
     * Getter for SignatureCompression.
     * @return Returns the SignatureCompression
     */
    @JsonGetter("signatureCompression")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SignatureCompression getSignatureCompression() {
        return signatureCompression;
    }

    /**
     * Setter for SignatureCompression.
     * @param signatureCompression Value for SignatureCompression
     */
    @JsonSetter("signatureCompression")
    public void setSignatureCompression(SignatureCompression signatureCompression) {
        this.signatureCompression = signatureCompression;
    }

    /**
     * Getter for SignatureEncryptKey.
     * Indicates the encryption key of the signature.
     * @return Returns the String
     */
    @JsonGetter("signatureEncryptKey")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSignatureEncryptKey() {
        return signatureEncryptKey;
    }

    /**
     * Setter for SignatureEncryptKey.
     * Indicates the encryption key of the signature.
     * @param signatureEncryptKey Value for String
     */
    @JsonSetter("signatureEncryptKey")
    public void setSignatureEncryptKey(String signatureEncryptKey) {
        this.signatureEncryptKey = signatureEncryptKey;
    }

    /**
     * Getter for SignatureEncryptMethod.
     * Used to verify the encryption method.
     * @return Returns the String
     */
    @JsonGetter("signatureEncryptMethod")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSignatureEncryptMethod() {
        return signatureEncryptMethod;
    }

    /**
     * Setter for SignatureEncryptMethod.
     * Used to verify the encryption method.
     * @param signatureEncryptMethod Value for String
     */
    @JsonSetter("signatureEncryptMethod")
    public void setSignatureEncryptMethod(String signatureEncryptMethod) {
        this.signatureEncryptMethod = signatureEncryptMethod;
    }

    /**
     * Getter for SignaturePen.
     * @return Returns the SignaturePen
     */
    @JsonGetter("signaturePen")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SignaturePen getSignaturePen() {
        return signaturePen;
    }

    /**
     * Setter for SignaturePen.
     * @param signaturePen Value for SignaturePen
     */
    @JsonSetter("signaturePen")
    public void setSignaturePen(SignaturePen signaturePen) {
        this.signaturePen = signaturePen;
    }

    /**
     * Getter for StandInIndicator.
     * @return Returns the StandInIndicator
     */
    @JsonGetter("standInIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public StandInIndicator getStandInIndicator() {
        return standInIndicator;
    }

    /**
     * Setter for StandInIndicator.
     * @param standInIndicator Value for StandInIndicator
     */
    @JsonSetter("standInIndicator")
    public void setStandInIndicator(StandInIndicator standInIndicator) {
        this.standInIndicator = standInIndicator;
    }

    /**
     * Getter for StandInLevel.
     * @return Returns the StandInLevel
     */
    @JsonGetter("standInLevel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public StandInLevel getStandInLevel() {
        return standInLevel;
    }

    /**
     * Setter for StandInLevel.
     * @param standInLevel Value for StandInLevel
     */
    @JsonSetter("standInLevel")
    public void setStandInLevel(StandInLevel standInLevel) {
        this.standInLevel = standInLevel;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this OtherServices into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OtherServices [" + "levelIndicator=" + levelIndicator
                + ", reAuthorizationAttemptsCount=" + reAuthorizationAttemptsCount
                + ", signatureCapabilitiesIndicator=" + signatureCapabilitiesIndicator
                + ", signatureCompression=" + signatureCompression + ", signatureEncryptKey="
                + signatureEncryptKey + ", signatureEncryptMethod=" + signatureEncryptMethod
                + ", signaturePen=" + signaturePen + ", standInIndicator=" + standInIndicator
                + ", standInLevel=" + standInLevel + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link OtherServices.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OtherServices.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .levelIndicator(getLevelIndicator())
                .reAuthorizationAttemptsCount(getReAuthorizationAttemptsCount())
                .signatureCapabilitiesIndicator(getSignatureCapabilitiesIndicator())
                .signatureCompression(getSignatureCompression())
                .signatureEncryptKey(getSignatureEncryptKey())
                .signatureEncryptMethod(getSignatureEncryptMethod())
                .signaturePen(getSignaturePen())
                .standInIndicator(getStandInIndicator())
                .standInLevel(getStandInLevel());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link OtherServices}.
     */
    public static class Builder {
        private LevelIndicator levelIndicator;
        private String reAuthorizationAttemptsCount;
        private SignatureCapabilitiesIndicator signatureCapabilitiesIndicator;
        private SignatureCompression signatureCompression;
        private String signatureEncryptKey;
        private String signatureEncryptMethod;
        private SignaturePen signaturePen;
        private StandInIndicator standInIndicator;
        private StandInLevel standInLevel;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for levelIndicator.
         * @param  levelIndicator  LevelIndicator value for levelIndicator.
         * @return Builder
         */
        public Builder levelIndicator(LevelIndicator levelIndicator) {
            this.levelIndicator = levelIndicator;
            return this;
        }

        /**
         * Setter for reAuthorizationAttemptsCount.
         * @param  reAuthorizationAttemptsCount  String value for reAuthorizationAttemptsCount.
         * @return Builder
         */
        public Builder reAuthorizationAttemptsCount(String reAuthorizationAttemptsCount) {
            this.reAuthorizationAttemptsCount = reAuthorizationAttemptsCount;
            return this;
        }

        /**
         * Setter for signatureCapabilitiesIndicator.
         * @param  signatureCapabilitiesIndicator  SignatureCapabilitiesIndicator value for
         *         signatureCapabilitiesIndicator.
         * @return Builder
         */
        public Builder signatureCapabilitiesIndicator(
                SignatureCapabilitiesIndicator signatureCapabilitiesIndicator) {
            this.signatureCapabilitiesIndicator = signatureCapabilitiesIndicator;
            return this;
        }

        /**
         * Setter for signatureCompression.
         * @param  signatureCompression  SignatureCompression value for signatureCompression.
         * @return Builder
         */
        public Builder signatureCompression(SignatureCompression signatureCompression) {
            this.signatureCompression = signatureCompression;
            return this;
        }

        /**
         * Setter for signatureEncryptKey.
         * @param  signatureEncryptKey  String value for signatureEncryptKey.
         * @return Builder
         */
        public Builder signatureEncryptKey(String signatureEncryptKey) {
            this.signatureEncryptKey = signatureEncryptKey;
            return this;
        }

        /**
         * Setter for signatureEncryptMethod.
         * @param  signatureEncryptMethod  String value for signatureEncryptMethod.
         * @return Builder
         */
        public Builder signatureEncryptMethod(String signatureEncryptMethod) {
            this.signatureEncryptMethod = signatureEncryptMethod;
            return this;
        }

        /**
         * Setter for signaturePen.
         * @param  signaturePen  SignaturePen value for signaturePen.
         * @return Builder
         */
        public Builder signaturePen(SignaturePen signaturePen) {
            this.signaturePen = signaturePen;
            return this;
        }

        /**
         * Setter for standInIndicator.
         * @param  standInIndicator  StandInIndicator value for standInIndicator.
         * @return Builder
         */
        public Builder standInIndicator(StandInIndicator standInIndicator) {
            this.standInIndicator = standInIndicator;
            return this;
        }

        /**
         * Setter for standInLevel.
         * @param  standInLevel  StandInLevel value for standInLevel.
         * @return Builder
         */
        public Builder standInLevel(StandInLevel standInLevel) {
            this.standInLevel = standInLevel;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link OtherServices} object using the set fields.
         * @return {@link OtherServices}
         */
        public OtherServices build() {
            OtherServices model =
                    new OtherServices(levelIndicator, reAuthorizationAttemptsCount,
                            signatureCapabilitiesIndicator, signatureCompression,
                            signatureEncryptKey, signatureEncryptMethod, signaturePen,
                            standInIndicator, standInLevel);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
