/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for SearchSettleDailyTotalsRequest type.
 */
public class SearchSettleDailyTotalsRequest {
    private Pagination pagination;
    private SortResultsBy1 sortResultsBy;
    private Hierarchy1 hierarchy;
    private DateType dateType;
    private DateRange1 dateRange;
    private List<CardTypes1> cardTypes;
    private Boolean terminalData;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SearchSettleDailyTotalsRequest() {
    }

    /**
     * Initialization constructor.
     * @param  hierarchy  Hierarchy1 value for hierarchy.
     * @param  dateType  DateType value for dateType.
     * @param  dateRange  DateRange1 value for dateRange.
     * @param  pagination  Pagination value for pagination.
     * @param  sortResultsBy  SortResultsBy1 value for sortResultsBy.
     * @param  cardTypes  List of CardTypes1 value for cardTypes.
     * @param  terminalData  Boolean value for terminalData.
     */
    public SearchSettleDailyTotalsRequest(
            Hierarchy1 hierarchy,
            DateType dateType,
            DateRange1 dateRange,
            Pagination pagination,
            SortResultsBy1 sortResultsBy,
            List<CardTypes1> cardTypes,
            Boolean terminalData) {
        this.pagination = pagination;
        this.sortResultsBy = sortResultsBy;
        this.hierarchy = hierarchy;
        this.dateType = dateType;
        this.dateRange = dateRange;
        this.cardTypes = cardTypes;
        this.terminalData = terminalData;
    }

    /**
     * Getter for Pagination.
     * @return Returns the Pagination
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * @param pagination Value for Pagination
     */
    @JsonSetter("pagination")
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Getter for SortResultsBy.
     * @return Returns the SortResultsBy1
     */
    @JsonGetter("sortResultsBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SortResultsBy1 getSortResultsBy() {
        return sortResultsBy;
    }

    /**
     * Setter for SortResultsBy.
     * @param sortResultsBy Value for SortResultsBy1
     */
    @JsonSetter("sortResultsBy")
    public void setSortResultsBy(SortResultsBy1 sortResultsBy) {
        this.sortResultsBy = sortResultsBy;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy1
     */
    @JsonGetter("hierarchy")
    public Hierarchy1 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy1
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy1 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for DateType.
     * @return Returns the DateType
     */
    @JsonGetter("dateType")
    public DateType getDateType() {
        return dateType;
    }

    /**
     * Setter for DateType.
     * @param dateType Value for DateType
     */
    @JsonSetter("dateType")
    public void setDateType(DateType dateType) {
        this.dateType = dateType;
    }

    /**
     * Getter for DateRange.
     * @return Returns the DateRange1
     */
    @JsonGetter("dateRange")
    public DateRange1 getDateRange() {
        return dateRange;
    }

    /**
     * Setter for DateRange.
     * @param dateRange Value for DateRange1
     */
    @JsonSetter("dateRange")
    public void setDateRange(DateRange1 dateRange) {
        this.dateRange = dateRange;
    }

    /**
     * Getter for CardTypes.
     * The category or classification of a payment card based on the issuing network. Possible
     * values are CREDIT, DEBIT, GIFT, and EBT.
     * @return Returns the List of CardTypes1
     */
    @JsonGetter("cardTypes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CardTypes1> getCardTypes() {
        return cardTypes;
    }

    /**
     * Setter for CardTypes.
     * The category or classification of a payment card based on the issuing network. Possible
     * values are CREDIT, DEBIT, GIFT, and EBT.
     * @param cardTypes Value for List of CardTypes1
     */
    @JsonSetter("cardTypes")
    public void setCardTypes(List<CardTypes1> cardTypes) {
        this.cardTypes = cardTypes;
    }

    /**
     * Getter for TerminalData.
     * Display the terminal data.
     * @return Returns the Boolean
     */
    @JsonGetter("terminalData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getTerminalData() {
        return terminalData;
    }

    /**
     * Setter for TerminalData.
     * Display the terminal data.
     * @param terminalData Value for Boolean
     */
    @JsonSetter("terminalData")
    public void setTerminalData(Boolean terminalData) {
        this.terminalData = terminalData;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SearchSettleDailyTotalsRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SearchSettleDailyTotalsRequest [" + "hierarchy=" + hierarchy + ", dateType="
                + dateType + ", dateRange=" + dateRange + ", pagination=" + pagination
                + ", sortResultsBy=" + sortResultsBy + ", cardTypes=" + cardTypes
                + ", terminalData=" + terminalData + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SearchSettleDailyTotalsRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SearchSettleDailyTotalsRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(hierarchy, dateType, dateRange)
                .pagination(getPagination())
                .sortResultsBy(getSortResultsBy())
                .cardTypes(getCardTypes())
                .terminalData(getTerminalData());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SearchSettleDailyTotalsRequest}.
     */
    public static class Builder {
        private Hierarchy1 hierarchy;
        private DateType dateType;
        private DateRange1 dateRange;
        private Pagination pagination;
        private SortResultsBy1 sortResultsBy;
        private List<CardTypes1> cardTypes;
        private Boolean terminalData;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  hierarchy  Hierarchy1 value for hierarchy.
         * @param  dateType  DateType value for dateType.
         * @param  dateRange  DateRange1 value for dateRange.
         */
        public Builder(Hierarchy1 hierarchy, DateType dateType, DateRange1 dateRange) {
            this.hierarchy = hierarchy;
            this.dateType = dateType;
            this.dateRange = dateRange;
        }

        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy1 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy1 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for dateType.
         * @param  dateType  DateType value for dateType.
         * @return Builder
         */
        public Builder dateType(DateType dateType) {
            this.dateType = dateType;
            return this;
        }

        /**
         * Setter for dateRange.
         * @param  dateRange  DateRange1 value for dateRange.
         * @return Builder
         */
        public Builder dateRange(DateRange1 dateRange) {
            this.dateRange = dateRange;
            return this;
        }

        /**
         * Setter for pagination.
         * @param  pagination  Pagination value for pagination.
         * @return Builder
         */
        public Builder pagination(Pagination pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Setter for sortResultsBy.
         * @param  sortResultsBy  SortResultsBy1 value for sortResultsBy.
         * @return Builder
         */
        public Builder sortResultsBy(SortResultsBy1 sortResultsBy) {
            this.sortResultsBy = sortResultsBy;
            return this;
        }

        /**
         * Setter for cardTypes.
         * @param  cardTypes  List of CardTypes1 value for cardTypes.
         * @return Builder
         */
        public Builder cardTypes(List<CardTypes1> cardTypes) {
            this.cardTypes = cardTypes;
            return this;
        }

        /**
         * Setter for terminalData.
         * @param  terminalData  Boolean value for terminalData.
         * @return Builder
         */
        public Builder terminalData(Boolean terminalData) {
            this.terminalData = terminalData;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SearchSettleDailyTotalsRequest} object using the set fields.
         * @return {@link SearchSettleDailyTotalsRequest}
         */
        public SearchSettleDailyTotalsRequest build() {
            SearchSettleDailyTotalsRequest model =
                    new SearchSettleDailyTotalsRequest(hierarchy, dateType, dateRange, pagination,
                            sortResultsBy, cardTypes, terminalData);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
