/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SearchRequesttransactionAmountRange type.
 */
public class SearchRequesttransactionAmountRange {
    private Double fromAmount;
    private Double toAmount;
    private String authorizationCurrencyCode;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SearchRequesttransactionAmountRange() {
    }

    /**
     * Initialization constructor.
     * @param  fromAmount  Double value for fromAmount.
     * @param  toAmount  Double value for toAmount.
     * @param  authorizationCurrencyCode  String value for authorizationCurrencyCode.
     */
    public SearchRequesttransactionAmountRange(
            Double fromAmount,
            Double toAmount,
            String authorizationCurrencyCode) {
        this.fromAmount = fromAmount;
        this.toAmount = toAmount;
        this.authorizationCurrencyCode = authorizationCurrencyCode;
    }

    /**
     * Getter for FromAmount.
     * The lowest transaction value in the search range.
     * @return Returns the Double
     */
    @JsonGetter("fromAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getFromAmount() {
        return fromAmount;
    }

    /**
     * Setter for FromAmount.
     * The lowest transaction value in the search range.
     * @param fromAmount Value for Double
     */
    @JsonSetter("fromAmount")
    public void setFromAmount(Double fromAmount) {
        this.fromAmount = fromAmount;
    }

    /**
     * Getter for ToAmount.
     * The highest transaction value in the search range.
     * @return Returns the Double
     */
    @JsonGetter("toAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getToAmount() {
        return toAmount;
    }

    /**
     * Setter for ToAmount.
     * The highest transaction value in the search range.
     * @param toAmount Value for Double
     */
    @JsonSetter("toAmount")
    public void setToAmount(Double toAmount) {
        this.toAmount = toAmount;
    }

    /**
     * Getter for AuthorizationCurrencyCode.
     * The alpha codes and numeric codes for the representation of currencies and provides
     * information about the relationships between individual currencies and their minor units. ISO
     * Standard country code for United States. &lt;br&gt; Applicable for credit and gift cards.
     * @return Returns the String
     */
    @JsonGetter("authorizationCurrencyCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthorizationCurrencyCode() {
        return authorizationCurrencyCode;
    }

    /**
     * Setter for AuthorizationCurrencyCode.
     * The alpha codes and numeric codes for the representation of currencies and provides
     * information about the relationships between individual currencies and their minor units. ISO
     * Standard country code for United States. &lt;br&gt; Applicable for credit and gift cards.
     * @param authorizationCurrencyCode Value for String
     */
    @JsonSetter("authorizationCurrencyCode")
    public void setAuthorizationCurrencyCode(String authorizationCurrencyCode) {
        this.authorizationCurrencyCode = authorizationCurrencyCode;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SearchRequesttransactionAmountRange into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SearchRequesttransactionAmountRange [" + "fromAmount=" + fromAmount + ", toAmount="
                + toAmount + ", authorizationCurrencyCode=" + authorizationCurrencyCode
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SearchRequesttransactionAmountRange.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SearchRequesttransactionAmountRange.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fromAmount(getFromAmount())
                .toAmount(getToAmount())
                .authorizationCurrencyCode(getAuthorizationCurrencyCode());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SearchRequesttransactionAmountRange}.
     */
    public static class Builder {
        private Double fromAmount;
        private Double toAmount;
        private String authorizationCurrencyCode;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for fromAmount.
         * @param  fromAmount  Double value for fromAmount.
         * @return Builder
         */
        public Builder fromAmount(Double fromAmount) {
            this.fromAmount = fromAmount;
            return this;
        }

        /**
         * Setter for toAmount.
         * @param  toAmount  Double value for toAmount.
         * @return Builder
         */
        public Builder toAmount(Double toAmount) {
            this.toAmount = toAmount;
            return this;
        }

        /**
         * Setter for authorizationCurrencyCode.
         * @param  authorizationCurrencyCode  String value for authorizationCurrencyCode.
         * @return Builder
         */
        public Builder authorizationCurrencyCode(String authorizationCurrencyCode) {
            this.authorizationCurrencyCode = authorizationCurrencyCode;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SearchRequesttransactionAmountRange} object using the set fields.
         * @return {@link SearchRequesttransactionAmountRange}
         */
        public SearchRequesttransactionAmountRange build() {
            SearchRequesttransactionAmountRange model =
                    new SearchRequesttransactionAmountRange(fromAmount, toAmount,
                            authorizationCurrencyCode);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
