/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SearchAuthTransactions type.
 */
public class SearchAuthTransactions {
    private TransactionDetails2 transactionDetails;
    private CardDetails2 cardDetails;
    private LocationDetails2 locationDetails;
    private InterchangeDetails interchangeDetails;
    private PremiumPayback premiumPayback;
    private OtherServices2 otherServices;
    private EmvDetails2 emvDetails;
    private FraudSightDetails2 fraudSightDetails;
    private SignifyDetails signifyDetails;
    private AdditionalDetails additionalDetails;
    private CustomerFields2 customerFields;
    private PaymentGatewayDetails1 paymentGatewayDetails;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SearchAuthTransactions() {
    }

    /**
     * Initialization constructor.
     * @param  transactionDetails  TransactionDetails2 value for transactionDetails.
     * @param  cardDetails  CardDetails2 value for cardDetails.
     * @param  locationDetails  LocationDetails2 value for locationDetails.
     * @param  interchangeDetails  InterchangeDetails value for interchangeDetails.
     * @param  premiumPayback  PremiumPayback value for premiumPayback.
     * @param  otherServices  OtherServices2 value for otherServices.
     * @param  emvDetails  EmvDetails2 value for emvDetails.
     * @param  fraudSightDetails  FraudSightDetails2 value for fraudSightDetails.
     * @param  signifyDetails  SignifyDetails value for signifyDetails.
     * @param  additionalDetails  AdditionalDetails value for additionalDetails.
     * @param  customerFields  CustomerFields2 value for customerFields.
     * @param  paymentGatewayDetails  PaymentGatewayDetails1 value for paymentGatewayDetails.
     */
    public SearchAuthTransactions(
            TransactionDetails2 transactionDetails,
            CardDetails2 cardDetails,
            LocationDetails2 locationDetails,
            InterchangeDetails interchangeDetails,
            PremiumPayback premiumPayback,
            OtherServices2 otherServices,
            EmvDetails2 emvDetails,
            FraudSightDetails2 fraudSightDetails,
            SignifyDetails signifyDetails,
            AdditionalDetails additionalDetails,
            CustomerFields2 customerFields,
            PaymentGatewayDetails1 paymentGatewayDetails) {
        this.transactionDetails = transactionDetails;
        this.cardDetails = cardDetails;
        this.locationDetails = locationDetails;
        this.interchangeDetails = interchangeDetails;
        this.premiumPayback = premiumPayback;
        this.otherServices = otherServices;
        this.emvDetails = emvDetails;
        this.fraudSightDetails = fraudSightDetails;
        this.signifyDetails = signifyDetails;
        this.additionalDetails = additionalDetails;
        this.customerFields = customerFields;
        this.paymentGatewayDetails = paymentGatewayDetails;
    }

    /**
     * Getter for TransactionDetails.
     * @return Returns the TransactionDetails2
     */
    @JsonGetter("transactionDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionDetails2 getTransactionDetails() {
        return transactionDetails;
    }

    /**
     * Setter for TransactionDetails.
     * @param transactionDetails Value for TransactionDetails2
     */
    @JsonSetter("transactionDetails")
    public void setTransactionDetails(TransactionDetails2 transactionDetails) {
        this.transactionDetails = transactionDetails;
    }

    /**
     * Getter for CardDetails.
     * @return Returns the CardDetails2
     */
    @JsonGetter("cardDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardDetails2 getCardDetails() {
        return cardDetails;
    }

    /**
     * Setter for CardDetails.
     * @param cardDetails Value for CardDetails2
     */
    @JsonSetter("cardDetails")
    public void setCardDetails(CardDetails2 cardDetails) {
        this.cardDetails = cardDetails;
    }

    /**
     * Getter for LocationDetails.
     * @return Returns the LocationDetails2
     */
    @JsonGetter("locationDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LocationDetails2 getLocationDetails() {
        return locationDetails;
    }

    /**
     * Setter for LocationDetails.
     * @param locationDetails Value for LocationDetails2
     */
    @JsonSetter("locationDetails")
    public void setLocationDetails(LocationDetails2 locationDetails) {
        this.locationDetails = locationDetails;
    }

    /**
     * Getter for InterchangeDetails.
     * @return Returns the InterchangeDetails
     */
    @JsonGetter("interchangeDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InterchangeDetails getInterchangeDetails() {
        return interchangeDetails;
    }

    /**
     * Setter for InterchangeDetails.
     * @param interchangeDetails Value for InterchangeDetails
     */
    @JsonSetter("interchangeDetails")
    public void setInterchangeDetails(InterchangeDetails interchangeDetails) {
        this.interchangeDetails = interchangeDetails;
    }

    /**
     * Getter for PremiumPayback.
     * @return Returns the PremiumPayback
     */
    @JsonGetter("premiumPayback")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PremiumPayback getPremiumPayback() {
        return premiumPayback;
    }

    /**
     * Setter for PremiumPayback.
     * @param premiumPayback Value for PremiumPayback
     */
    @JsonSetter("premiumPayback")
    public void setPremiumPayback(PremiumPayback premiumPayback) {
        this.premiumPayback = premiumPayback;
    }

    /**
     * Getter for OtherServices.
     * @return Returns the OtherServices2
     */
    @JsonGetter("otherServices")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OtherServices2 getOtherServices() {
        return otherServices;
    }

    /**
     * Setter for OtherServices.
     * @param otherServices Value for OtherServices2
     */
    @JsonSetter("otherServices")
    public void setOtherServices(OtherServices2 otherServices) {
        this.otherServices = otherServices;
    }

    /**
     * Getter for EmvDetails.
     * @return Returns the EmvDetails2
     */
    @JsonGetter("emvDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EmvDetails2 getEmvDetails() {
        return emvDetails;
    }

    /**
     * Setter for EmvDetails.
     * @param emvDetails Value for EmvDetails2
     */
    @JsonSetter("emvDetails")
    public void setEmvDetails(EmvDetails2 emvDetails) {
        this.emvDetails = emvDetails;
    }

    /**
     * Getter for FraudSightDetails.
     * @return Returns the FraudSightDetails2
     */
    @JsonGetter("fraudSightDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudSightDetails2 getFraudSightDetails() {
        return fraudSightDetails;
    }

    /**
     * Setter for FraudSightDetails.
     * @param fraudSightDetails Value for FraudSightDetails2
     */
    @JsonSetter("fraudSightDetails")
    public void setFraudSightDetails(FraudSightDetails2 fraudSightDetails) {
        this.fraudSightDetails = fraudSightDetails;
    }

    /**
     * Getter for SignifyDetails.
     * @return Returns the SignifyDetails
     */
    @JsonGetter("signifyDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SignifyDetails getSignifyDetails() {
        return signifyDetails;
    }

    /**
     * Setter for SignifyDetails.
     * @param signifyDetails Value for SignifyDetails
     */
    @JsonSetter("signifyDetails")
    public void setSignifyDetails(SignifyDetails signifyDetails) {
        this.signifyDetails = signifyDetails;
    }

    /**
     * Getter for AdditionalDetails.
     * @return Returns the AdditionalDetails
     */
    @JsonGetter("additionalDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AdditionalDetails getAdditionalDetails() {
        return additionalDetails;
    }

    /**
     * Setter for AdditionalDetails.
     * @param additionalDetails Value for AdditionalDetails
     */
    @JsonSetter("additionalDetails")
    public void setAdditionalDetails(AdditionalDetails additionalDetails) {
        this.additionalDetails = additionalDetails;
    }

    /**
     * Getter for CustomerFields.
     * @return Returns the CustomerFields2
     */
    @JsonGetter("customerFields")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CustomerFields2 getCustomerFields() {
        return customerFields;
    }

    /**
     * Setter for CustomerFields.
     * @param customerFields Value for CustomerFields2
     */
    @JsonSetter("customerFields")
    public void setCustomerFields(CustomerFields2 customerFields) {
        this.customerFields = customerFields;
    }

    /**
     * Getter for PaymentGatewayDetails.
     * @return Returns the PaymentGatewayDetails1
     */
    @JsonGetter("paymentGatewayDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaymentGatewayDetails1 getPaymentGatewayDetails() {
        return paymentGatewayDetails;
    }

    /**
     * Setter for PaymentGatewayDetails.
     * @param paymentGatewayDetails Value for PaymentGatewayDetails1
     */
    @JsonSetter("paymentGatewayDetails")
    public void setPaymentGatewayDetails(PaymentGatewayDetails1 paymentGatewayDetails) {
        this.paymentGatewayDetails = paymentGatewayDetails;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SearchAuthTransactions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SearchAuthTransactions [" + "transactionDetails=" + transactionDetails
                + ", cardDetails=" + cardDetails + ", locationDetails=" + locationDetails
                + ", interchangeDetails=" + interchangeDetails + ", premiumPayback="
                + premiumPayback + ", otherServices=" + otherServices + ", emvDetails=" + emvDetails
                + ", fraudSightDetails=" + fraudSightDetails + ", signifyDetails=" + signifyDetails
                + ", additionalDetails=" + additionalDetails + ", customerFields=" + customerFields
                + ", paymentGatewayDetails=" + paymentGatewayDetails + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SearchAuthTransactions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SearchAuthTransactions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .transactionDetails(getTransactionDetails())
                .cardDetails(getCardDetails())
                .locationDetails(getLocationDetails())
                .interchangeDetails(getInterchangeDetails())
                .premiumPayback(getPremiumPayback())
                .otherServices(getOtherServices())
                .emvDetails(getEmvDetails())
                .fraudSightDetails(getFraudSightDetails())
                .signifyDetails(getSignifyDetails())
                .additionalDetails(getAdditionalDetails())
                .customerFields(getCustomerFields())
                .paymentGatewayDetails(getPaymentGatewayDetails());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SearchAuthTransactions}.
     */
    public static class Builder {
        private TransactionDetails2 transactionDetails;
        private CardDetails2 cardDetails;
        private LocationDetails2 locationDetails;
        private InterchangeDetails interchangeDetails;
        private PremiumPayback premiumPayback;
        private OtherServices2 otherServices;
        private EmvDetails2 emvDetails;
        private FraudSightDetails2 fraudSightDetails;
        private SignifyDetails signifyDetails;
        private AdditionalDetails additionalDetails;
        private CustomerFields2 customerFields;
        private PaymentGatewayDetails1 paymentGatewayDetails;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for transactionDetails.
         * @param  transactionDetails  TransactionDetails2 value for transactionDetails.
         * @return Builder
         */
        public Builder transactionDetails(TransactionDetails2 transactionDetails) {
            this.transactionDetails = transactionDetails;
            return this;
        }

        /**
         * Setter for cardDetails.
         * @param  cardDetails  CardDetails2 value for cardDetails.
         * @return Builder
         */
        public Builder cardDetails(CardDetails2 cardDetails) {
            this.cardDetails = cardDetails;
            return this;
        }

        /**
         * Setter for locationDetails.
         * @param  locationDetails  LocationDetails2 value for locationDetails.
         * @return Builder
         */
        public Builder locationDetails(LocationDetails2 locationDetails) {
            this.locationDetails = locationDetails;
            return this;
        }

        /**
         * Setter for interchangeDetails.
         * @param  interchangeDetails  InterchangeDetails value for interchangeDetails.
         * @return Builder
         */
        public Builder interchangeDetails(InterchangeDetails interchangeDetails) {
            this.interchangeDetails = interchangeDetails;
            return this;
        }

        /**
         * Setter for premiumPayback.
         * @param  premiumPayback  PremiumPayback value for premiumPayback.
         * @return Builder
         */
        public Builder premiumPayback(PremiumPayback premiumPayback) {
            this.premiumPayback = premiumPayback;
            return this;
        }

        /**
         * Setter for otherServices.
         * @param  otherServices  OtherServices2 value for otherServices.
         * @return Builder
         */
        public Builder otherServices(OtherServices2 otherServices) {
            this.otherServices = otherServices;
            return this;
        }

        /**
         * Setter for emvDetails.
         * @param  emvDetails  EmvDetails2 value for emvDetails.
         * @return Builder
         */
        public Builder emvDetails(EmvDetails2 emvDetails) {
            this.emvDetails = emvDetails;
            return this;
        }

        /**
         * Setter for fraudSightDetails.
         * @param  fraudSightDetails  FraudSightDetails2 value for fraudSightDetails.
         * @return Builder
         */
        public Builder fraudSightDetails(FraudSightDetails2 fraudSightDetails) {
            this.fraudSightDetails = fraudSightDetails;
            return this;
        }

        /**
         * Setter for signifyDetails.
         * @param  signifyDetails  SignifyDetails value for signifyDetails.
         * @return Builder
         */
        public Builder signifyDetails(SignifyDetails signifyDetails) {
            this.signifyDetails = signifyDetails;
            return this;
        }

        /**
         * Setter for additionalDetails.
         * @param  additionalDetails  AdditionalDetails value for additionalDetails.
         * @return Builder
         */
        public Builder additionalDetails(AdditionalDetails additionalDetails) {
            this.additionalDetails = additionalDetails;
            return this;
        }

        /**
         * Setter for customerFields.
         * @param  customerFields  CustomerFields2 value for customerFields.
         * @return Builder
         */
        public Builder customerFields(CustomerFields2 customerFields) {
            this.customerFields = customerFields;
            return this;
        }

        /**
         * Setter for paymentGatewayDetails.
         * @param  paymentGatewayDetails  PaymentGatewayDetails1 value for paymentGatewayDetails.
         * @return Builder
         */
        public Builder paymentGatewayDetails(PaymentGatewayDetails1 paymentGatewayDetails) {
            this.paymentGatewayDetails = paymentGatewayDetails;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SearchAuthTransactions} object using the set fields.
         * @return {@link SearchAuthTransactions}
         */
        public SearchAuthTransactions build() {
            SearchAuthTransactions model =
                    new SearchAuthTransactions(transactionDetails, cardDetails, locationDetails,
                            interchangeDetails, premiumPayback, otherServices, emvDetails,
                            fraudSightDetails, signifyDetails, additionalDetails, customerFields,
                            paymentGatewayDetails);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
