/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for SettlementBatchesTransactionStore type.
 */
public class SettlementBatchesTransactionStore {
    private Hierarchy4 hierarchy;
    private LocalDate processDate;
    private Integer numberOfBatches;
    private String batchCardType;
    private Double saleCount;
    private Double saleAmount;
    private Double returnCount;
    private Double returnAmount;
    private Double cashAdvanceCount;
    private Double cashAdvanceAmount;
    private Double netCount;
    private Double netAmount;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementBatchesTransactionStore() {
    }

    /**
     * Initialization constructor.
     * @param  hierarchy  Hierarchy4 value for hierarchy.
     * @param  processDate  LocalDate value for processDate.
     * @param  numberOfBatches  Integer value for numberOfBatches.
     * @param  batchCardType  String value for batchCardType.
     * @param  saleCount  Double value for saleCount.
     * @param  saleAmount  Double value for saleAmount.
     * @param  returnCount  Double value for returnCount.
     * @param  returnAmount  Double value for returnAmount.
     * @param  cashAdvanceCount  Double value for cashAdvanceCount.
     * @param  cashAdvanceAmount  Double value for cashAdvanceAmount.
     * @param  netCount  Double value for netCount.
     * @param  netAmount  Double value for netAmount.
     */
    public SettlementBatchesTransactionStore(
            Hierarchy4 hierarchy,
            LocalDate processDate,
            Integer numberOfBatches,
            String batchCardType,
            Double saleCount,
            Double saleAmount,
            Double returnCount,
            Double returnAmount,
            Double cashAdvanceCount,
            Double cashAdvanceAmount,
            Double netCount,
            Double netAmount) {
        this.hierarchy = hierarchy;
        this.processDate = processDate;
        this.numberOfBatches = numberOfBatches;
        this.batchCardType = batchCardType;
        this.saleCount = saleCount;
        this.saleAmount = saleAmount;
        this.returnCount = returnCount;
        this.returnAmount = returnAmount;
        this.cashAdvanceCount = cashAdvanceCount;
        this.cashAdvanceAmount = cashAdvanceAmount;
        this.netCount = netCount;
        this.netAmount = netAmount;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy4
     */
    @JsonGetter("hierarchy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Hierarchy4 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy4
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy4 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @return Returns the LocalDate
     */
    @JsonGetter("processDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getProcessDate() {
        return processDate;
    }

    /**
     * Setter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @param processDate Value for LocalDate
     */
    @JsonSetter("processDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setProcessDate(LocalDate processDate) {
        this.processDate = processDate;
    }

    /**
     * Getter for NumberOfBatches.
     * Refers to a group of processed transaction records.
     * @return Returns the Integer
     */
    @JsonGetter("numberOfBatches")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumberOfBatches() {
        return numberOfBatches;
    }

    /**
     * Setter for NumberOfBatches.
     * Refers to a group of processed transaction records.
     * @param numberOfBatches Value for Integer
     */
    @JsonSetter("numberOfBatches")
    public void setNumberOfBatches(Integer numberOfBatches) {
        this.numberOfBatches = numberOfBatches;
    }

    /**
     * Getter for BatchCardType.
     * The category or classification of a payment card based on the issuing network. Types are
     * CREDIT,DEBIT, and EBT.
     * @return Returns the String
     */
    @JsonGetter("batchCardType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBatchCardType() {
        return batchCardType;
    }

    /**
     * Setter for BatchCardType.
     * The category or classification of a payment card based on the issuing network. Types are
     * CREDIT,DEBIT, and EBT.
     * @param batchCardType Value for String
     */
    @JsonSetter("batchCardType")
    public void setBatchCardType(String batchCardType) {
        this.batchCardType = batchCardType;
    }

    /**
     * Getter for SaleCount.
     * Indicates the number of items sold within a specific batch quantity.
     * @return Returns the Double
     */
    @JsonGetter("saleCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSaleCount() {
        return saleCount;
    }

    /**
     * Setter for SaleCount.
     * Indicates the number of items sold within a specific batch quantity.
     * @param saleCount Value for Double
     */
    @JsonSetter("saleCount")
    public void setSaleCount(Double saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * Getter for SaleAmount.
     * Total revenue generated from selling items within a specific batch.
     * @return Returns the Double
     */
    @JsonGetter("saleAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSaleAmount() {
        return saleAmount;
    }

    /**
     * Setter for SaleAmount.
     * Total revenue generated from selling items within a specific batch.
     * @param saleAmount Value for Double
     */
    @JsonSetter("saleAmount")
    public void setSaleAmount(Double saleAmount) {
        this.saleAmount = saleAmount;
    }

    /**
     * Getter for ReturnCount.
     * Indicates the number of items sent back within a batch.
     * @return Returns the Double
     */
    @JsonGetter("returnCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getReturnCount() {
        return returnCount;
    }

    /**
     * Setter for ReturnCount.
     * Indicates the number of items sent back within a batch.
     * @param returnCount Value for Double
     */
    @JsonSetter("returnCount")
    public void setReturnCount(Double returnCount) {
        this.returnCount = returnCount;
    }

    /**
     * Getter for ReturnAmount.
     * Indicates amount refunded within a batch.
     * @return Returns the Double
     */
    @JsonGetter("returnAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getReturnAmount() {
        return returnAmount;
    }

    /**
     * Setter for ReturnAmount.
     * Indicates amount refunded within a batch.
     * @param returnAmount Value for Double
     */
    @JsonSetter("returnAmount")
    public void setReturnAmount(Double returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * Getter for CashAdvanceCount.
     * The total number of cash advances that were issued.
     * @return Returns the Double
     */
    @JsonGetter("cashAdvanceCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getCashAdvanceCount() {
        return cashAdvanceCount;
    }

    /**
     * Setter for CashAdvanceCount.
     * The total number of cash advances that were issued.
     * @param cashAdvanceCount Value for Double
     */
    @JsonSetter("cashAdvanceCount")
    public void setCashAdvanceCount(Double cashAdvanceCount) {
        this.cashAdvanceCount = cashAdvanceCount;
    }

    /**
     * Getter for CashAdvanceAmount.
     * The sum of the borrowed funds.
     * @return Returns the Double
     */
    @JsonGetter("cashAdvanceAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getCashAdvanceAmount() {
        return cashAdvanceAmount;
    }

    /**
     * Setter for CashAdvanceAmount.
     * The sum of the borrowed funds.
     * @param cashAdvanceAmount Value for Double
     */
    @JsonSetter("cashAdvanceAmount")
    public void setCashAdvanceAmount(Double cashAdvanceAmount) {
        this.cashAdvanceAmount = cashAdvanceAmount;
    }

    /**
     * Getter for NetCount.
     * The total remaining amount after deductions.
     * @return Returns the Double
     */
    @JsonGetter("netCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getNetCount() {
        return netCount;
    }

    /**
     * Setter for NetCount.
     * The total remaining amount after deductions.
     * @param netCount Value for Double
     */
    @JsonSetter("netCount")
    public void setNetCount(Double netCount) {
        this.netCount = netCount;
    }

    /**
     * Getter for NetAmount.
     * The count minus deductions.
     * @return Returns the Double
     */
    @JsonGetter("netAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getNetAmount() {
        return netAmount;
    }

    /**
     * Setter for NetAmount.
     * The count minus deductions.
     * @param netAmount Value for Double
     */
    @JsonSetter("netAmount")
    public void setNetAmount(Double netAmount) {
        this.netAmount = netAmount;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementBatchesTransactionStore into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementBatchesTransactionStore [" + "hierarchy=" + hierarchy + ", processDate="
                + processDate + ", numberOfBatches=" + numberOfBatches + ", batchCardType="
                + batchCardType + ", saleCount=" + saleCount + ", saleAmount=" + saleAmount
                + ", returnCount=" + returnCount + ", returnAmount=" + returnAmount
                + ", cashAdvanceCount=" + cashAdvanceCount + ", cashAdvanceAmount="
                + cashAdvanceAmount + ", netCount=" + netCount + ", netAmount=" + netAmount
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementBatchesTransactionStore.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementBatchesTransactionStore.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hierarchy(getHierarchy())
                .processDate(getProcessDate())
                .numberOfBatches(getNumberOfBatches())
                .batchCardType(getBatchCardType())
                .saleCount(getSaleCount())
                .saleAmount(getSaleAmount())
                .returnCount(getReturnCount())
                .returnAmount(getReturnAmount())
                .cashAdvanceCount(getCashAdvanceCount())
                .cashAdvanceAmount(getCashAdvanceAmount())
                .netCount(getNetCount())
                .netAmount(getNetAmount());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementBatchesTransactionStore}.
     */
    public static class Builder {
        private Hierarchy4 hierarchy;
        private LocalDate processDate;
        private Integer numberOfBatches;
        private String batchCardType;
        private Double saleCount;
        private Double saleAmount;
        private Double returnCount;
        private Double returnAmount;
        private Double cashAdvanceCount;
        private Double cashAdvanceAmount;
        private Double netCount;
        private Double netAmount;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy4 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy4 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for processDate.
         * @param  processDate  LocalDate value for processDate.
         * @return Builder
         */
        public Builder processDate(LocalDate processDate) {
            this.processDate = processDate;
            return this;
        }

        /**
         * Setter for numberOfBatches.
         * @param  numberOfBatches  Integer value for numberOfBatches.
         * @return Builder
         */
        public Builder numberOfBatches(Integer numberOfBatches) {
            this.numberOfBatches = numberOfBatches;
            return this;
        }

        /**
         * Setter for batchCardType.
         * @param  batchCardType  String value for batchCardType.
         * @return Builder
         */
        public Builder batchCardType(String batchCardType) {
            this.batchCardType = batchCardType;
            return this;
        }

        /**
         * Setter for saleCount.
         * @param  saleCount  Double value for saleCount.
         * @return Builder
         */
        public Builder saleCount(Double saleCount) {
            this.saleCount = saleCount;
            return this;
        }

        /**
         * Setter for saleAmount.
         * @param  saleAmount  Double value for saleAmount.
         * @return Builder
         */
        public Builder saleAmount(Double saleAmount) {
            this.saleAmount = saleAmount;
            return this;
        }

        /**
         * Setter for returnCount.
         * @param  returnCount  Double value for returnCount.
         * @return Builder
         */
        public Builder returnCount(Double returnCount) {
            this.returnCount = returnCount;
            return this;
        }

        /**
         * Setter for returnAmount.
         * @param  returnAmount  Double value for returnAmount.
         * @return Builder
         */
        public Builder returnAmount(Double returnAmount) {
            this.returnAmount = returnAmount;
            return this;
        }

        /**
         * Setter for cashAdvanceCount.
         * @param  cashAdvanceCount  Double value for cashAdvanceCount.
         * @return Builder
         */
        public Builder cashAdvanceCount(Double cashAdvanceCount) {
            this.cashAdvanceCount = cashAdvanceCount;
            return this;
        }

        /**
         * Setter for cashAdvanceAmount.
         * @param  cashAdvanceAmount  Double value for cashAdvanceAmount.
         * @return Builder
         */
        public Builder cashAdvanceAmount(Double cashAdvanceAmount) {
            this.cashAdvanceAmount = cashAdvanceAmount;
            return this;
        }

        /**
         * Setter for netCount.
         * @param  netCount  Double value for netCount.
         * @return Builder
         */
        public Builder netCount(Double netCount) {
            this.netCount = netCount;
            return this;
        }

        /**
         * Setter for netAmount.
         * @param  netAmount  Double value for netAmount.
         * @return Builder
         */
        public Builder netAmount(Double netAmount) {
            this.netAmount = netAmount;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementBatchesTransactionStore} object using the set fields.
         * @return {@link SettlementBatchesTransactionStore}
         */
        public SettlementBatchesTransactionStore build() {
            SettlementBatchesTransactionStore model =
                    new SettlementBatchesTransactionStore(hierarchy, processDate, numberOfBatches,
                            batchCardType, saleCount, saleAmount, returnCount, returnAmount,
                            cashAdvanceCount, cashAdvanceAmount, netCount, netAmount);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
