/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for SettlementRejRealTimeTransaction type.
 */
public class SettlementRejRealTimeTransaction {
    private LocalDate processedDate;
    private LocalDate transactionDate;
    private LocalDate resubmitDate;
    private String accountNumber;
    private String ddaNumber;
    private Double amount;
    private RejectionReason rejectionReason;
    private Hierarchy7 hierarchy;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementRejRealTimeTransaction() {
    }

    /**
     * Initialization constructor.
     * @param  processedDate  LocalDate value for processedDate.
     * @param  transactionDate  LocalDate value for transactionDate.
     * @param  resubmitDate  LocalDate value for resubmitDate.
     * @param  accountNumber  String value for accountNumber.
     * @param  ddaNumber  String value for ddaNumber.
     * @param  amount  Double value for amount.
     * @param  rejectionReason  RejectionReason value for rejectionReason.
     * @param  hierarchy  Hierarchy7 value for hierarchy.
     */
    public SettlementRejRealTimeTransaction(
            LocalDate processedDate,
            LocalDate transactionDate,
            LocalDate resubmitDate,
            String accountNumber,
            String ddaNumber,
            Double amount,
            RejectionReason rejectionReason,
            Hierarchy7 hierarchy) {
        this.processedDate = processedDate;
        this.transactionDate = transactionDate;
        this.resubmitDate = resubmitDate;
        this.accountNumber = accountNumber;
        this.ddaNumber = ddaNumber;
        this.amount = amount;
        this.rejectionReason = rejectionReason;
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for ProcessedDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @return Returns the LocalDate
     */
    @JsonGetter("processedDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getProcessedDate() {
        return processedDate;
    }

    /**
     * Setter for ProcessedDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @param processedDate Value for LocalDate
     */
    @JsonSetter("processedDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setProcessedDate(LocalDate processedDate) {
        this.processedDate = processedDate;
    }

    /**
     * Getter for TransactionDate.
     * The date and time when the bank has settled/rejected the transaction (deposits or withdraws
     * funds).
     * @return Returns the LocalDate
     */
    @JsonGetter("transactionDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    /**
     * Setter for TransactionDate.
     * The date and time when the bank has settled/rejected the transaction (deposits or withdraws
     * funds).
     * @param transactionDate Value for LocalDate
     */
    @JsonSetter("transactionDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * Getter for ResubmitDate.
     * The resubmission date of the transaction.
     * @return Returns the LocalDate
     */
    @JsonGetter("resubmitDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getResubmitDate() {
        return resubmitDate;
    }

    /**
     * Setter for ResubmitDate.
     * The resubmission date of the transaction.
     * @param resubmitDate Value for LocalDate
     */
    @JsonSetter("resubmitDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setResubmitDate(LocalDate resubmitDate) {
        this.resubmitDate = resubmitDate;
    }

    /**
     * Getter for AccountNumber.
     * The account number or card number involved in the rejected transaction.
     * @return Returns the String
     */
    @JsonGetter("accountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * The account number or card number involved in the rejected transaction.
     * @param accountNumber Value for String
     */
    @JsonSetter("accountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for DdaNumber.
     * Demand deposit account is a type of bank account that offers access to money.
     * @return Returns the String
     */
    @JsonGetter("ddaNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDdaNumber() {
        return ddaNumber;
    }

    /**
     * Setter for DdaNumber.
     * Demand deposit account is a type of bank account that offers access to money.
     * @param ddaNumber Value for String
     */
    @JsonSetter("ddaNumber")
    public void setDdaNumber(String ddaNumber) {
        this.ddaNumber = ddaNumber;
    }

    /**
     * Getter for Amount.
     * The rejected transaction amount.
     * @return Returns the Double
     */
    @JsonGetter("amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * The rejected transaction amount.
     * @param amount Value for Double
     */
    @JsonSetter("amount")
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Getter for RejectionReason.
     * @return Returns the RejectionReason
     */
    @JsonGetter("rejectionReason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RejectionReason getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Setter for RejectionReason.
     * @param rejectionReason Value for RejectionReason
     */
    @JsonSetter("rejectionReason")
    public void setRejectionReason(RejectionReason rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy7
     */
    @JsonGetter("hierarchy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Hierarchy7 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy7
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy7 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementRejRealTimeTransaction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementRejRealTimeTransaction [" + "processedDate=" + processedDate
                + ", transactionDate=" + transactionDate + ", resubmitDate=" + resubmitDate
                + ", accountNumber=" + accountNumber + ", ddaNumber=" + ddaNumber + ", amount="
                + amount + ", rejectionReason=" + rejectionReason + ", hierarchy=" + hierarchy
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementRejRealTimeTransaction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementRejRealTimeTransaction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .processedDate(getProcessedDate())
                .transactionDate(getTransactionDate())
                .resubmitDate(getResubmitDate())
                .accountNumber(getAccountNumber())
                .ddaNumber(getDdaNumber())
                .amount(getAmount())
                .rejectionReason(getRejectionReason())
                .hierarchy(getHierarchy());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementRejRealTimeTransaction}.
     */
    public static class Builder {
        private LocalDate processedDate;
        private LocalDate transactionDate;
        private LocalDate resubmitDate;
        private String accountNumber;
        private String ddaNumber;
        private Double amount;
        private RejectionReason rejectionReason;
        private Hierarchy7 hierarchy;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for processedDate.
         * @param  processedDate  LocalDate value for processedDate.
         * @return Builder
         */
        public Builder processedDate(LocalDate processedDate) {
            this.processedDate = processedDate;
            return this;
        }

        /**
         * Setter for transactionDate.
         * @param  transactionDate  LocalDate value for transactionDate.
         * @return Builder
         */
        public Builder transactionDate(LocalDate transactionDate) {
            this.transactionDate = transactionDate;
            return this;
        }

        /**
         * Setter for resubmitDate.
         * @param  resubmitDate  LocalDate value for resubmitDate.
         * @return Builder
         */
        public Builder resubmitDate(LocalDate resubmitDate) {
            this.resubmitDate = resubmitDate;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for ddaNumber.
         * @param  ddaNumber  String value for ddaNumber.
         * @return Builder
         */
        public Builder ddaNumber(String ddaNumber) {
            this.ddaNumber = ddaNumber;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  Double value for amount.
         * @return Builder
         */
        public Builder amount(Double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for rejectionReason.
         * @param  rejectionReason  RejectionReason value for rejectionReason.
         * @return Builder
         */
        public Builder rejectionReason(RejectionReason rejectionReason) {
            this.rejectionReason = rejectionReason;
            return this;
        }

        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy7 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy7 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementRejRealTimeTransaction} object using the set fields.
         * @return {@link SettlementRejRealTimeTransaction}
         */
        public SettlementRejRealTimeTransaction build() {
            SettlementRejRealTimeTransaction model =
                    new SettlementRejRealTimeTransaction(processedDate, transactionDate,
                            resubmitDate, accountNumber, ddaNumber, amount, rejectionReason,
                            hierarchy);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
