/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for SettlementsSearchResponse type.
 */
public class SettlementsSearchResponse {
    private PaginationResponse pagination;
    private List<SearchAuthTransactions> settlements;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementsSearchResponse() {
    }

    /**
     * Initialization constructor.
     * @param  pagination  PaginationResponse value for pagination.
     * @param  settlements  List of SearchAuthTransactions value for settlements.
     */
    public SettlementsSearchResponse(
            PaginationResponse pagination,
            List<SearchAuthTransactions> settlements) {
        this.pagination = pagination;
        this.settlements = settlements;
    }

    /**
     * Getter for Pagination.
     * The format used to display your resources.
     * @return Returns the PaginationResponse
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaginationResponse getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * The format used to display your resources.
     * @param pagination Value for PaginationResponse
     */
    @JsonSetter("pagination")
    public void setPagination(PaginationResponse pagination) {
        this.pagination = pagination;
    }

    /**
     * Getter for Settlements.
     * The details of the settlement transactions.
     * @return Returns the List of SearchAuthTransactions
     */
    @JsonGetter("settlements")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SearchAuthTransactions> getSettlements() {
        return settlements;
    }

    /**
     * Setter for Settlements.
     * The details of the settlement transactions.
     * @param settlements Value for List of SearchAuthTransactions
     */
    @JsonSetter("settlements")
    public void setSettlements(List<SearchAuthTransactions> settlements) {
        this.settlements = settlements;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementsSearchResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementsSearchResponse [" + "pagination=" + pagination + ", settlements="
                + settlements + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementsSearchResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementsSearchResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pagination(getPagination())
                .settlements(getSettlements());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementsSearchResponse}.
     */
    public static class Builder {
        private PaginationResponse pagination;
        private List<SearchAuthTransactions> settlements;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for pagination.
         * @param  pagination  PaginationResponse value for pagination.
         * @return Builder
         */
        public Builder pagination(PaginationResponse pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Setter for settlements.
         * @param  settlements  List of SearchAuthTransactions value for settlements.
         * @return Builder
         */
        public Builder settlements(List<SearchAuthTransactions> settlements) {
            this.settlements = settlements;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementsSearchResponse} object using the set fields.
         * @return {@link SettlementsSearchResponse}
         */
        public SettlementsSearchResponse build() {
            SettlementsSearchResponse model =
                    new SettlementsSearchResponse(pagination, settlements);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
