/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SettlementerrorsSettlementfileerrorsSearchRequest type.
 */
public class SettlementerrorsSettlementfileerrorsSearchRequest {
    private Pagination pagination;
    private Hierarchy6 hierarchy;
    private SortResultsBy4 sortResultsBy;
    private DateRange1 dateRange;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementerrorsSettlementfileerrorsSearchRequest() {
    }

    /**
     * Initialization constructor.
     * @param  hierarchy  Hierarchy6 value for hierarchy.
     * @param  dateRange  DateRange1 value for dateRange.
     * @param  pagination  Pagination value for pagination.
     * @param  sortResultsBy  SortResultsBy4 value for sortResultsBy.
     */
    public SettlementerrorsSettlementfileerrorsSearchRequest(
            Hierarchy6 hierarchy,
            DateRange1 dateRange,
            Pagination pagination,
            SortResultsBy4 sortResultsBy) {
        this.pagination = pagination;
        this.hierarchy = hierarchy;
        this.sortResultsBy = sortResultsBy;
        this.dateRange = dateRange;
    }

    /**
     * Getter for Pagination.
     * @return Returns the Pagination
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * @param pagination Value for Pagination
     */
    @JsonSetter("pagination")
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy6
     */
    @JsonGetter("hierarchy")
    public Hierarchy6 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy6
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy6 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for SortResultsBy.
     * @return Returns the SortResultsBy4
     */
    @JsonGetter("sortResultsBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SortResultsBy4 getSortResultsBy() {
        return sortResultsBy;
    }

    /**
     * Setter for SortResultsBy.
     * @param sortResultsBy Value for SortResultsBy4
     */
    @JsonSetter("sortResultsBy")
    public void setSortResultsBy(SortResultsBy4 sortResultsBy) {
        this.sortResultsBy = sortResultsBy;
    }

    /**
     * Getter for DateRange.
     * @return Returns the DateRange1
     */
    @JsonGetter("dateRange")
    public DateRange1 getDateRange() {
        return dateRange;
    }

    /**
     * Setter for DateRange.
     * @param dateRange Value for DateRange1
     */
    @JsonSetter("dateRange")
    public void setDateRange(DateRange1 dateRange) {
        this.dateRange = dateRange;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementerrorsSettlementfileerrorsSearchRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementerrorsSettlementfileerrorsSearchRequest [" + "hierarchy=" + hierarchy
                + ", dateRange=" + dateRange + ", pagination=" + pagination + ", sortResultsBy="
                + sortResultsBy + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementerrorsSettlementfileerrorsSearchRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementerrorsSettlementfileerrorsSearchRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(hierarchy, dateRange)
                .pagination(getPagination())
                .sortResultsBy(getSortResultsBy());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementerrorsSettlementfileerrorsSearchRequest}.
     */
    public static class Builder {
        private Hierarchy6 hierarchy;
        private DateRange1 dateRange;
        private Pagination pagination;
        private SortResultsBy4 sortResultsBy;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  hierarchy  Hierarchy6 value for hierarchy.
         * @param  dateRange  DateRange1 value for dateRange.
         */
        public Builder(Hierarchy6 hierarchy, DateRange1 dateRange) {
            this.hierarchy = hierarchy;
            this.dateRange = dateRange;
        }

        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy6 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy6 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for dateRange.
         * @param  dateRange  DateRange1 value for dateRange.
         * @return Builder
         */
        public Builder dateRange(DateRange1 dateRange) {
            this.dateRange = dateRange;
            return this;
        }

        /**
         * Setter for pagination.
         * @param  pagination  Pagination value for pagination.
         * @return Builder
         */
        public Builder pagination(Pagination pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Setter for sortResultsBy.
         * @param  sortResultsBy  SortResultsBy4 value for sortResultsBy.
         * @return Builder
         */
        public Builder sortResultsBy(SortResultsBy4 sortResultsBy) {
            this.sortResultsBy = sortResultsBy;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementerrorsSettlementfileerrorsSearchRequest} object using the
         * set fields.
         * @return {@link SettlementerrorsSettlementfileerrorsSearchRequest}
         */
        public SettlementerrorsSettlementfileerrorsSearchRequest build() {
            SettlementerrorsSettlementfileerrorsSearchRequest model =
                    new SettlementerrorsSettlementfileerrorsSearchRequest(hierarchy, dateRange,
                            pagination, sortResultsBy);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
