/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.worldpay.cert.apis.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for SettlementBatchesTransactionDate type.
 */
public class SettlementBatchesTransactionDate {
    private Hierarchy4 hierarchy;
    private LocalDate processDate;
    private Integer batchNumber;
    private String batchCardType;
    private Integer saleCount;
    private Double saleAmount;
    private Integer returnCount;
    private Double returnAmount;
    private Integer cashAdvanceCount;
    private Double cashAdvanceAmount;
    private Integer netCount;
    private Double netAmount;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementBatchesTransactionDate() {
    }

    /**
     * Initialization constructor.
     * @param  hierarchy  Hierarchy4 value for hierarchy.
     * @param  processDate  LocalDate value for processDate.
     * @param  batchNumber  Integer value for batchNumber.
     * @param  batchCardType  String value for batchCardType.
     * @param  saleCount  Integer value for saleCount.
     * @param  saleAmount  Double value for saleAmount.
     * @param  returnCount  Integer value for returnCount.
     * @param  returnAmount  Double value for returnAmount.
     * @param  cashAdvanceCount  Integer value for cashAdvanceCount.
     * @param  cashAdvanceAmount  Double value for cashAdvanceAmount.
     * @param  netCount  Integer value for netCount.
     * @param  netAmount  Double value for netAmount.
     */
    public SettlementBatchesTransactionDate(
            Hierarchy4 hierarchy,
            LocalDate processDate,
            Integer batchNumber,
            String batchCardType,
            Integer saleCount,
            Double saleAmount,
            Integer returnCount,
            Double returnAmount,
            Integer cashAdvanceCount,
            Double cashAdvanceAmount,
            Integer netCount,
            Double netAmount) {
        this.hierarchy = hierarchy;
        this.processDate = processDate;
        this.batchNumber = batchNumber;
        this.batchCardType = batchCardType;
        this.saleCount = saleCount;
        this.saleAmount = saleAmount;
        this.returnCount = returnCount;
        this.returnAmount = returnAmount;
        this.cashAdvanceCount = cashAdvanceCount;
        this.cashAdvanceAmount = cashAdvanceAmount;
        this.netCount = netCount;
        this.netAmount = netAmount;
    }

    /**
     * Getter for Hierarchy.
     * @return Returns the Hierarchy4
     */
    @JsonGetter("hierarchy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Hierarchy4 getHierarchy() {
        return hierarchy;
    }

    /**
     * Setter for Hierarchy.
     * @param hierarchy Value for Hierarchy4
     */
    @JsonSetter("hierarchy")
    public void setHierarchy(Hierarchy4 hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * Getter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @return Returns the LocalDate
     */
    @JsonGetter("processDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getProcessDate() {
        return processDate;
    }

    /**
     * Setter for ProcessDate.
     * The date when the transaction has been processed for settlement between the two parties.
     * @param processDate Value for LocalDate
     */
    @JsonSetter("processDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setProcessDate(LocalDate processDate) {
        this.processDate = processDate;
    }

    /**
     * Getter for BatchNumber.
     * The 11-byte unique identifier assigned to a group of transactions that were handled together
     * as a single unit.
     * @return Returns the Integer
     */
    @JsonGetter("batchNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getBatchNumber() {
        return batchNumber;
    }

    /**
     * Setter for BatchNumber.
     * The 11-byte unique identifier assigned to a group of transactions that were handled together
     * as a single unit.
     * @param batchNumber Value for Integer
     */
    @JsonSetter("batchNumber")
    public void setBatchNumber(Integer batchNumber) {
        this.batchNumber = batchNumber;
    }

    /**
     * Getter for BatchCardType.
     * The category or classification of a payment card based on the issuing network. The type is
     * either Credit or Debit.
     * @return Returns the String
     */
    @JsonGetter("batchCardType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBatchCardType() {
        return batchCardType;
    }

    /**
     * Setter for BatchCardType.
     * The category or classification of a payment card based on the issuing network. The type is
     * either Credit or Debit.
     * @param batchCardType Value for String
     */
    @JsonSetter("batchCardType")
    public void setBatchCardType(String batchCardType) {
        this.batchCardType = batchCardType;
    }

    /**
     * Getter for SaleCount.
     * The number of items sold within a specific batch quantity.
     * @return Returns the Integer
     */
    @JsonGetter("saleCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * Setter for SaleCount.
     * The number of items sold within a specific batch quantity.
     * @param saleCount Value for Integer
     */
    @JsonSetter("saleCount")
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * Getter for SaleAmount.
     * The total revenue generated from selling items within a specific batch.
     * @return Returns the Double
     */
    @JsonGetter("saleAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSaleAmount() {
        return saleAmount;
    }

    /**
     * Setter for SaleAmount.
     * The total revenue generated from selling items within a specific batch.
     * @param saleAmount Value for Double
     */
    @JsonSetter("saleAmount")
    public void setSaleAmount(Double saleAmount) {
        this.saleAmount = saleAmount;
    }

    /**
     * Getter for ReturnCount.
     * The number of items sent back within a batch.
     * @return Returns the Integer
     */
    @JsonGetter("returnCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReturnCount() {
        return returnCount;
    }

    /**
     * Setter for ReturnCount.
     * The number of items sent back within a batch.
     * @param returnCount Value for Integer
     */
    @JsonSetter("returnCount")
    public void setReturnCount(Integer returnCount) {
        this.returnCount = returnCount;
    }

    /**
     * Getter for ReturnAmount.
     * The amount refunded within a batch.
     * @return Returns the Double
     */
    @JsonGetter("returnAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getReturnAmount() {
        return returnAmount;
    }

    /**
     * Setter for ReturnAmount.
     * The amount refunded within a batch.
     * @param returnAmount Value for Double
     */
    @JsonSetter("returnAmount")
    public void setReturnAmount(Double returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * Getter for CashAdvanceCount.
     * The total number of cash advances issued.
     * @return Returns the Integer
     */
    @JsonGetter("cashAdvanceCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCashAdvanceCount() {
        return cashAdvanceCount;
    }

    /**
     * Setter for CashAdvanceCount.
     * The total number of cash advances issued.
     * @param cashAdvanceCount Value for Integer
     */
    @JsonSetter("cashAdvanceCount")
    public void setCashAdvanceCount(Integer cashAdvanceCount) {
        this.cashAdvanceCount = cashAdvanceCount;
    }

    /**
     * Getter for CashAdvanceAmount.
     * The sum of the borrowed funds.
     * @return Returns the Double
     */
    @JsonGetter("cashAdvanceAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getCashAdvanceAmount() {
        return cashAdvanceAmount;
    }

    /**
     * Setter for CashAdvanceAmount.
     * The sum of the borrowed funds.
     * @param cashAdvanceAmount Value for Double
     */
    @JsonSetter("cashAdvanceAmount")
    public void setCashAdvanceAmount(Double cashAdvanceAmount) {
        this.cashAdvanceAmount = cashAdvanceAmount;
    }

    /**
     * Getter for NetCount.
     * The total remaining amount after deductions.
     * @return Returns the Integer
     */
    @JsonGetter("netCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNetCount() {
        return netCount;
    }

    /**
     * Setter for NetCount.
     * The total remaining amount after deductions.
     * @param netCount Value for Integer
     */
    @JsonSetter("netCount")
    public void setNetCount(Integer netCount) {
        this.netCount = netCount;
    }

    /**
     * Getter for NetAmount.
     * The count minus deductions.
     * @return Returns the Double
     */
    @JsonGetter("netAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getNetAmount() {
        return netAmount;
    }

    /**
     * Setter for NetAmount.
     * The count minus deductions.
     * @param netAmount Value for Double
     */
    @JsonSetter("netAmount")
    public void setNetAmount(Double netAmount) {
        this.netAmount = netAmount;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementBatchesTransactionDate into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementBatchesTransactionDate [" + "hierarchy=" + hierarchy + ", processDate="
                + processDate + ", batchNumber=" + batchNumber + ", batchCardType=" + batchCardType
                + ", saleCount=" + saleCount + ", saleAmount=" + saleAmount + ", returnCount="
                + returnCount + ", returnAmount=" + returnAmount + ", cashAdvanceCount="
                + cashAdvanceCount + ", cashAdvanceAmount=" + cashAdvanceAmount + ", netCount="
                + netCount + ", netAmount=" + netAmount + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementBatchesTransactionDate.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementBatchesTransactionDate.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hierarchy(getHierarchy())
                .processDate(getProcessDate())
                .batchNumber(getBatchNumber())
                .batchCardType(getBatchCardType())
                .saleCount(getSaleCount())
                .saleAmount(getSaleAmount())
                .returnCount(getReturnCount())
                .returnAmount(getReturnAmount())
                .cashAdvanceCount(getCashAdvanceCount())
                .cashAdvanceAmount(getCashAdvanceAmount())
                .netCount(getNetCount())
                .netAmount(getNetAmount());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementBatchesTransactionDate}.
     */
    public static class Builder {
        private Hierarchy4 hierarchy;
        private LocalDate processDate;
        private Integer batchNumber;
        private String batchCardType;
        private Integer saleCount;
        private Double saleAmount;
        private Integer returnCount;
        private Double returnAmount;
        private Integer cashAdvanceCount;
        private Double cashAdvanceAmount;
        private Integer netCount;
        private Double netAmount;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for hierarchy.
         * @param  hierarchy  Hierarchy4 value for hierarchy.
         * @return Builder
         */
        public Builder hierarchy(Hierarchy4 hierarchy) {
            this.hierarchy = hierarchy;
            return this;
        }

        /**
         * Setter for processDate.
         * @param  processDate  LocalDate value for processDate.
         * @return Builder
         */
        public Builder processDate(LocalDate processDate) {
            this.processDate = processDate;
            return this;
        }

        /**
         * Setter for batchNumber.
         * @param  batchNumber  Integer value for batchNumber.
         * @return Builder
         */
        public Builder batchNumber(Integer batchNumber) {
            this.batchNumber = batchNumber;
            return this;
        }

        /**
         * Setter for batchCardType.
         * @param  batchCardType  String value for batchCardType.
         * @return Builder
         */
        public Builder batchCardType(String batchCardType) {
            this.batchCardType = batchCardType;
            return this;
        }

        /**
         * Setter for saleCount.
         * @param  saleCount  Integer value for saleCount.
         * @return Builder
         */
        public Builder saleCount(Integer saleCount) {
            this.saleCount = saleCount;
            return this;
        }

        /**
         * Setter for saleAmount.
         * @param  saleAmount  Double value for saleAmount.
         * @return Builder
         */
        public Builder saleAmount(Double saleAmount) {
            this.saleAmount = saleAmount;
            return this;
        }

        /**
         * Setter for returnCount.
         * @param  returnCount  Integer value for returnCount.
         * @return Builder
         */
        public Builder returnCount(Integer returnCount) {
            this.returnCount = returnCount;
            return this;
        }

        /**
         * Setter for returnAmount.
         * @param  returnAmount  Double value for returnAmount.
         * @return Builder
         */
        public Builder returnAmount(Double returnAmount) {
            this.returnAmount = returnAmount;
            return this;
        }

        /**
         * Setter for cashAdvanceCount.
         * @param  cashAdvanceCount  Integer value for cashAdvanceCount.
         * @return Builder
         */
        public Builder cashAdvanceCount(Integer cashAdvanceCount) {
            this.cashAdvanceCount = cashAdvanceCount;
            return this;
        }

        /**
         * Setter for cashAdvanceAmount.
         * @param  cashAdvanceAmount  Double value for cashAdvanceAmount.
         * @return Builder
         */
        public Builder cashAdvanceAmount(Double cashAdvanceAmount) {
            this.cashAdvanceAmount = cashAdvanceAmount;
            return this;
        }

        /**
         * Setter for netCount.
         * @param  netCount  Integer value for netCount.
         * @return Builder
         */
        public Builder netCount(Integer netCount) {
            this.netCount = netCount;
            return this;
        }

        /**
         * Setter for netAmount.
         * @param  netAmount  Double value for netAmount.
         * @return Builder
         */
        public Builder netAmount(Double netAmount) {
            this.netAmount = netAmount;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementBatchesTransactionDate} object using the set fields.
         * @return {@link SettlementBatchesTransactionDate}
         */
        public SettlementBatchesTransactionDate build() {
            SettlementBatchesTransactionDate model =
                    new SettlementBatchesTransactionDate(hierarchy, processDate, batchNumber,
                            batchCardType, saleCount, saleAmount, returnCount, returnAmount,
                            cashAdvanceCount, cashAdvanceAmount, netCount, netAmount);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
