/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for SettlementerrorsPendingsettlementbatchesSearchResponse type.
 */
public class SettlementerrorsPendingsettlementbatchesSearchResponse {
    private Pagination4 pagination;
    private List<BankCardRejRealTimeTransaction> details;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SettlementerrorsPendingsettlementbatchesSearchResponse() {
    }

    /**
     * Initialization constructor.
     * @param  pagination  Pagination4 value for pagination.
     * @param  details  List of BankCardRejRealTimeTransaction value for details.
     */
    public SettlementerrorsPendingsettlementbatchesSearchResponse(
            Pagination4 pagination,
            List<BankCardRejRealTimeTransaction> details) {
        this.pagination = pagination;
        this.details = details;
    }

    /**
     * Getter for Pagination.
     * @return Returns the Pagination4
     */
    @JsonGetter("pagination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Pagination4 getPagination() {
        return pagination;
    }

    /**
     * Setter for Pagination.
     * @param pagination Value for Pagination4
     */
    @JsonSetter("pagination")
    public void setPagination(Pagination4 pagination) {
        this.pagination = pagination;
    }

    /**
     * Getter for Details.
     * Refers to bank card rejection details.
     * @return Returns the List of BankCardRejRealTimeTransaction
     */
    @JsonGetter("details")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<BankCardRejRealTimeTransaction> getDetails() {
        return details;
    }

    /**
     * Setter for Details.
     * Refers to bank card rejection details.
     * @param details Value for List of BankCardRejRealTimeTransaction
     */
    @JsonSetter("details")
    public void setDetails(List<BankCardRejRealTimeTransaction> details) {
        this.details = details;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SettlementerrorsPendingsettlementbatchesSearchResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SettlementerrorsPendingsettlementbatchesSearchResponse [" + "pagination="
                + pagination + ", details=" + details + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SettlementerrorsPendingsettlementbatchesSearchResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SettlementerrorsPendingsettlementbatchesSearchResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pagination(getPagination())
                .details(getDetails());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SettlementerrorsPendingsettlementbatchesSearchResponse}.
     */
    public static class Builder {
        private Pagination4 pagination;
        private List<BankCardRejRealTimeTransaction> details;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for pagination.
         * @param  pagination  Pagination4 value for pagination.
         * @return Builder
         */
        public Builder pagination(Pagination4 pagination) {
            this.pagination = pagination;
            return this;
        }

        /**
         * Setter for details.
         * @param  details  List of BankCardRejRealTimeTransaction value for details.
         * @return Builder
         */
        public Builder details(List<BankCardRejRealTimeTransaction> details) {
            this.details = details;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SettlementerrorsPendingsettlementbatchesSearchResponse} object using
         * the set fields.
         * @return {@link SettlementerrorsPendingsettlementbatchesSearchResponse}
         */
        public SettlementerrorsPendingsettlementbatchesSearchResponse build() {
            SettlementerrorsPendingsettlementbatchesSearchResponse model =
                    new SettlementerrorsPendingsettlementbatchesSearchResponse(pagination, details);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
