/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SignifyDetails type.
 */
public class SignifyDetails {
    private String fraudVendorId;
    private FraudCoverageType fraudCoverageType;
    private FraudDetectionStage fraudDetectionStage;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SignifyDetails() {
    }

    /**
     * Initialization constructor.
     * @param  fraudVendorId  String value for fraudVendorId.
     * @param  fraudCoverageType  FraudCoverageType value for fraudCoverageType.
     * @param  fraudDetectionStage  FraudDetectionStage value for fraudDetectionStage.
     */
    public SignifyDetails(
            String fraudVendorId,
            FraudCoverageType fraudCoverageType,
            FraudDetectionStage fraudDetectionStage) {
        this.fraudVendorId = fraudVendorId;
        this.fraudCoverageType = fraudCoverageType;
        this.fraudDetectionStage = fraudDetectionStage;
    }

    /**
     * Getter for FraudVendorId.
     * An vendor identification used in fraudulent schemes to deceive and exploit unsuspecting
     * individuals or organizations.
     * @return Returns the String
     */
    @JsonGetter("fraudVendorId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFraudVendorId() {
        return fraudVendorId;
    }

    /**
     * Setter for FraudVendorId.
     * An vendor identification used in fraudulent schemes to deceive and exploit unsuspecting
     * individuals or organizations.
     * @param fraudVendorId Value for String
     */
    @JsonSetter("fraudVendorId")
    public void setFraudVendorId(String fraudVendorId) {
        this.fraudVendorId = fraudVendorId;
    }

    /**
     * Getter for FraudCoverageType.
     * @return Returns the FraudCoverageType
     */
    @JsonGetter("fraudCoverageType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudCoverageType getFraudCoverageType() {
        return fraudCoverageType;
    }

    /**
     * Setter for FraudCoverageType.
     * @param fraudCoverageType Value for FraudCoverageType
     */
    @JsonSetter("fraudCoverageType")
    public void setFraudCoverageType(FraudCoverageType fraudCoverageType) {
        this.fraudCoverageType = fraudCoverageType;
    }

    /**
     * Getter for FraudDetectionStage.
     * @return Returns the FraudDetectionStage
     */
    @JsonGetter("fraudDetectionStage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FraudDetectionStage getFraudDetectionStage() {
        return fraudDetectionStage;
    }

    /**
     * Setter for FraudDetectionStage.
     * @param fraudDetectionStage Value for FraudDetectionStage
     */
    @JsonSetter("fraudDetectionStage")
    public void setFraudDetectionStage(FraudDetectionStage fraudDetectionStage) {
        this.fraudDetectionStage = fraudDetectionStage;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SignifyDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SignifyDetails [" + "fraudVendorId=" + fraudVendorId + ", fraudCoverageType="
                + fraudCoverageType + ", fraudDetectionStage=" + fraudDetectionStage
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SignifyDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SignifyDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fraudVendorId(getFraudVendorId())
                .fraudCoverageType(getFraudCoverageType())
                .fraudDetectionStage(getFraudDetectionStage());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SignifyDetails}.
     */
    public static class Builder {
        private String fraudVendorId;
        private FraudCoverageType fraudCoverageType;
        private FraudDetectionStage fraudDetectionStage;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for fraudVendorId.
         * @param  fraudVendorId  String value for fraudVendorId.
         * @return Builder
         */
        public Builder fraudVendorId(String fraudVendorId) {
            this.fraudVendorId = fraudVendorId;
            return this;
        }

        /**
         * Setter for fraudCoverageType.
         * @param  fraudCoverageType  FraudCoverageType value for fraudCoverageType.
         * @return Builder
         */
        public Builder fraudCoverageType(FraudCoverageType fraudCoverageType) {
            this.fraudCoverageType = fraudCoverageType;
            return this;
        }

        /**
         * Setter for fraudDetectionStage.
         * @param  fraudDetectionStage  FraudDetectionStage value for fraudDetectionStage.
         * @return Builder
         */
        public Builder fraudDetectionStage(FraudDetectionStage fraudDetectionStage) {
            this.fraudDetectionStage = fraudDetectionStage;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SignifyDetails} object using the set fields.
         * @return {@link SignifyDetails}
         */
        public SignifyDetails build() {
            SignifyDetails model =
                    new SignifyDetails(fraudVendorId, fraudCoverageType, fraudDetectionStage);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
