/*
 * ReportingSettlementResearchApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.worldpay.cert.apis.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TransactionStatusCode1 to be used.
 */
public enum TransactionStatusCode1 {
    AA,

    AB,

    AV,

    EX,

    F1,

    NC,

    ND,

    NE,

    NL,

    NP,

    NR,

    NS,

    NX,

    N7,

    RE,

    RJ,

    V1,

    V2,

    V3,

    V4,

    V5,

    V6,

    ENUM_000,

    ENUM_001,

    ENUM_002,

    ENUM_003,

    ENUM_004,

    ENUM_005,

    ENUM_006,

    ENUM_007,

    ENUM_008,

    ENUM_009,

    ENUM_011,

    ENUM_012,

    ENUM_013,

    ENUM_014,

    ENUM_015,

    ENUM_016,

    ENUM_017,

    ENUM_018,

    ENUM_019,

    ENUM_020,

    ENUM_021,

    ENUM_022,

    ENUM_023,

    ENUM_024,

    ENUM_025,

    ENUM_026,

    ENUM_027,

    ENUM_028,

    ENUM_029,

    ENUM_030,

    ENUM_031,

    ENUM_032,

    ENUM_033,

    ENUM_034,

    ENUM_035,

    ENUM_036,

    ENUM_037,

    ENUM_038,

    ENUM_039,

    ENUM_040,

    ENUM_041,

    ENUM_042,

    ENUM_043,

    ENUM_044,

    ENUM_045,

    ENUM_046,

    ENUM_047,

    ENUM_048,

    ENUM_049,

    ENUM_050,

    ENUM_051,

    ENUM_052,

    ENUM_053,

    ENUM_054,

    ENUM_055,

    ENUM_056,

    ENUM_057,

    ENUM_058,

    ENUM_059,

    ENUM_060,

    ENUM_061,

    ENUM_062,

    ENUM_063,

    ENUM_064,

    ENUM_065,

    ENUM_066,

    ENUM_067,

    ENUM_068,

    ENUM_069,

    ENUM_070,

    ENUM_071,

    ENUM_072,

    ENUM_073,

    ENUM_074,

    ENUM_075,

    ENUM_076,

    ENUM_077,

    ENUM_078,

    ENUM_079,

    ENUM_080,

    ENUM_081,

    ENUM_082,

    ENUM_083,

    ENUM_084,

    ENUM_085,

    ENUM_086,

    ENUM_087,

    ENUM_088,

    ENUM_089,

    ENUM_090,

    ENUM_091,

    ENUM_092,

    ENUM_093,

    ENUM_094,

    ENUM_095,

    ENUM_096,

    ENUM_097,

    ENUM_098,

    ENUM_099,

    ENUM_100,

    ENUM_101,

    ENUM_102,

    ENUM_103,

    ENUM_104,

    ENUM_105,

    ENUM_106,

    ENUM_107,

    ENUM_108,

    ENUM_109,

    ENUM_110,

    ENUM_111,

    ENUM_112,

    ENUM_113,

    ENUM_114,

    ENUM_115,

    ENUM_116,

    ENUM_117,

    ENUM_118,

    ENUM_119,

    ENUM_120,

    ENUM_121,

    ENUM_122,

    ENUM_123,

    ENUM_124,

    ENUM_125,

    ENUM_126,

    ENUM_127,

    ENUM_128,

    ENUM_129,

    ENUM_130,

    ENUM_131,

    ENUM_132,

    ENUM_133,

    ENUM_134,

    ENUM_135,

    ENUM_136,

    ENUM_137,

    ENUM_138,

    ENUM_139,

    ENUM_140,

    ENUM_141,

    ENUM_142,

    ENUM_143,

    ENUM_144,

    ENUM_145,

    ENUM_146,

    ENUM_147,

    ENUM_148,

    ENUM_149,

    ENUM_150,

    ENUM_151,

    ENUM_152,

    ENUM_153,

    ENUM_154,

    ENUM_155,

    ENUM_156,

    ENUM_157,

    ENUM_158,

    ENUM_159,

    ENUM_160,

    ENUM_161,

    ENUM_162,

    ENUM_163,

    ENUM_164,

    ENUM_165,

    ENUM_166,

    ENUM_167,

    ENUM_168,

    ENUM_169,

    ENUM_170,

    ENUM_171,

    ENUM_172,

    ENUM_173,

    ENUM_174,

    ENUM_175,

    ENUM_176,

    ENUM_177,

    ENUM_178,

    ENUM_179,

    ENUM_180,

    ENUM_181,

    ENUM_182,

    ENUM_183,

    ENUM_184,

    ENUM_185,

    ENUM_186,

    ENUM_187,

    ENUM_188,

    ENUM_189,

    ENUM_190,

    ENUM_191,

    ENUM_192,

    ENUM_193,

    ENUM_194,

    ENUM_195,

    ENUM_196,

    ENUM_197,

    ENUM_198,

    ENUM_199,

    ENUM_200,

    ENUM_201,

    ENUM_202,

    ENUM_203,

    ENUM_204,

    ENUM_205,

    ENUM_206,

    ENUM_207,

    ENUM_208,

    ENUM_209,

    ENUM_210,

    ENUM_222,

    ENUM_227,

    ENUM_244,

    ENUM_254,

    ENUM_255,

    ENUM_300,

    ENUM_301,

    ENUM_302,

    ENUM_303,

    ENUM_304,

    ENUM_305,

    ENUM_306,

    ENUM_307,

    ENUM_308,

    ENUM_309,

    ENUM_310,

    ENUM_311,

    ENUM_312,

    /**
     * Unknown values will be mapped by this enum member
     */
    _UNKNOWN;


    private static TreeMap<String, TransactionStatusCode1> valueMap = new TreeMap<>();
    private String value;

    static {
        AA.value = "AA";
        AB.value = "AB";
        AV.value = "AV";
        EX.value = "EX";
        F1.value = "F1";
        NC.value = "NC";
        ND.value = "ND";
        NE.value = "NE";
        NL.value = "NL";
        NP.value = "NP";
        NR.value = "NR";
        NS.value = "NS";
        NX.value = "NX";
        N7.value = "N7";
        RE.value = "RE";
        RJ.value = "RJ";
        V1.value = "V1";
        V2.value = "V2";
        V3.value = "V3";
        V4.value = "V4";
        V5.value = "V5";
        V6.value = "V6";
        ENUM_000.value = "000";
        ENUM_001.value = "001";
        ENUM_002.value = "002";
        ENUM_003.value = "003";
        ENUM_004.value = "004";
        ENUM_005.value = "005";
        ENUM_006.value = "006";
        ENUM_007.value = "007";
        ENUM_008.value = "008";
        ENUM_009.value = "009";
        ENUM_011.value = "011";
        ENUM_012.value = "012";
        ENUM_013.value = "013";
        ENUM_014.value = "014";
        ENUM_015.value = "015";
        ENUM_016.value = "016";
        ENUM_017.value = "017";
        ENUM_018.value = "018";
        ENUM_019.value = "019";
        ENUM_020.value = "020";
        ENUM_021.value = "021";
        ENUM_022.value = "022";
        ENUM_023.value = "023";
        ENUM_024.value = "024";
        ENUM_025.value = "025";
        ENUM_026.value = "026";
        ENUM_027.value = "027";
        ENUM_028.value = "028";
        ENUM_029.value = "029";
        ENUM_030.value = "030";
        ENUM_031.value = "031";
        ENUM_032.value = "032";
        ENUM_033.value = "033";
        ENUM_034.value = "034";
        ENUM_035.value = "035";
        ENUM_036.value = "036";
        ENUM_037.value = "037";
        ENUM_038.value = "038";
        ENUM_039.value = "039";
        ENUM_040.value = "040";
        ENUM_041.value = "041";
        ENUM_042.value = "042";
        ENUM_043.value = "043";
        ENUM_044.value = "044";
        ENUM_045.value = "045";
        ENUM_046.value = "046";
        ENUM_047.value = "047";
        ENUM_048.value = "048";
        ENUM_049.value = "049";
        ENUM_050.value = "050";
        ENUM_051.value = "051";
        ENUM_052.value = "052";
        ENUM_053.value = "053";
        ENUM_054.value = "054";
        ENUM_055.value = "055";
        ENUM_056.value = "056";
        ENUM_057.value = "057";
        ENUM_058.value = "058";
        ENUM_059.value = "059";
        ENUM_060.value = "060";
        ENUM_061.value = "061";
        ENUM_062.value = "062";
        ENUM_063.value = "063";
        ENUM_064.value = "064";
        ENUM_065.value = "065";
        ENUM_066.value = "066";
        ENUM_067.value = "067";
        ENUM_068.value = "068";
        ENUM_069.value = "069";
        ENUM_070.value = "070";
        ENUM_071.value = "071";
        ENUM_072.value = "072";
        ENUM_073.value = "073";
        ENUM_074.value = "074";
        ENUM_075.value = "075";
        ENUM_076.value = "076";
        ENUM_077.value = "077";
        ENUM_078.value = "078";
        ENUM_079.value = "079";
        ENUM_080.value = "080";
        ENUM_081.value = "081";
        ENUM_082.value = "082";
        ENUM_083.value = "083";
        ENUM_084.value = "084";
        ENUM_085.value = "085";
        ENUM_086.value = "086";
        ENUM_087.value = "087";
        ENUM_088.value = "088";
        ENUM_089.value = "089";
        ENUM_090.value = "090";
        ENUM_091.value = "091";
        ENUM_092.value = "092";
        ENUM_093.value = "093";
        ENUM_094.value = "094";
        ENUM_095.value = "095";
        ENUM_096.value = "096";
        ENUM_097.value = "097";
        ENUM_098.value = "098";
        ENUM_099.value = "099";
        ENUM_100.value = "100";
        ENUM_101.value = "101";
        ENUM_102.value = "102";
        ENUM_103.value = "103";
        ENUM_104.value = "104";
        ENUM_105.value = "105";
        ENUM_106.value = "106";
        ENUM_107.value = "107";
        ENUM_108.value = "108";
        ENUM_109.value = "109";
        ENUM_110.value = "110";
        ENUM_111.value = "111";
        ENUM_112.value = "112";
        ENUM_113.value = "113";
        ENUM_114.value = "114";
        ENUM_115.value = "115";
        ENUM_116.value = "116";
        ENUM_117.value = "117";
        ENUM_118.value = "118";
        ENUM_119.value = "119";
        ENUM_120.value = "120";
        ENUM_121.value = "121";
        ENUM_122.value = "122";
        ENUM_123.value = "123";
        ENUM_124.value = "124";
        ENUM_125.value = "125";
        ENUM_126.value = "126";
        ENUM_127.value = "127";
        ENUM_128.value = "128";
        ENUM_129.value = "129";
        ENUM_130.value = "130";
        ENUM_131.value = "131";
        ENUM_132.value = "132";
        ENUM_133.value = "133";
        ENUM_134.value = "134";
        ENUM_135.value = "135";
        ENUM_136.value = "136";
        ENUM_137.value = "137";
        ENUM_138.value = "138";
        ENUM_139.value = "139";
        ENUM_140.value = "140";
        ENUM_141.value = "141";
        ENUM_142.value = "142";
        ENUM_143.value = "143";
        ENUM_144.value = "144";
        ENUM_145.value = "145";
        ENUM_146.value = "146";
        ENUM_147.value = "147";
        ENUM_148.value = "148";
        ENUM_149.value = "149";
        ENUM_150.value = "150";
        ENUM_151.value = "151";
        ENUM_152.value = "152";
        ENUM_153.value = "153";
        ENUM_154.value = "154";
        ENUM_155.value = "155";
        ENUM_156.value = "156";
        ENUM_157.value = "157";
        ENUM_158.value = "158";
        ENUM_159.value = "159";
        ENUM_160.value = "160";
        ENUM_161.value = "161";
        ENUM_162.value = "162";
        ENUM_163.value = "163";
        ENUM_164.value = "164";
        ENUM_165.value = "165";
        ENUM_166.value = "166";
        ENUM_167.value = "167";
        ENUM_168.value = "168";
        ENUM_169.value = "169";
        ENUM_170.value = "170";
        ENUM_171.value = "171";
        ENUM_172.value = "172";
        ENUM_173.value = "173";
        ENUM_174.value = "174";
        ENUM_175.value = "175";
        ENUM_176.value = "176";
        ENUM_177.value = "177";
        ENUM_178.value = "178";
        ENUM_179.value = "179";
        ENUM_180.value = "180";
        ENUM_181.value = "181";
        ENUM_182.value = "182";
        ENUM_183.value = "183";
        ENUM_184.value = "184";
        ENUM_185.value = "185";
        ENUM_186.value = "186";
        ENUM_187.value = "187";
        ENUM_188.value = "188";
        ENUM_189.value = "189";
        ENUM_190.value = "190";
        ENUM_191.value = "191";
        ENUM_192.value = "192";
        ENUM_193.value = "193";
        ENUM_194.value = "194";
        ENUM_195.value = "195";
        ENUM_196.value = "196";
        ENUM_197.value = "197";
        ENUM_198.value = "198";
        ENUM_199.value = "199";
        ENUM_200.value = "200";
        ENUM_201.value = "201";
        ENUM_202.value = "202";
        ENUM_203.value = "203";
        ENUM_204.value = "204";
        ENUM_205.value = "205";
        ENUM_206.value = "206";
        ENUM_207.value = "207";
        ENUM_208.value = "208";
        ENUM_209.value = "209";
        ENUM_210.value = "210";
        ENUM_222.value = "222";
        ENUM_227.value = "227";
        ENUM_244.value = "244";
        ENUM_254.value = "254";
        ENUM_255.value = "255";
        ENUM_300.value = "300";
        ENUM_301.value = "301";
        ENUM_302.value = "302";
        ENUM_303.value = "303";
        ENUM_304.value = "304";
        ENUM_305.value = "305";
        ENUM_306.value = "306";
        ENUM_307.value = "307";
        ENUM_308.value = "308";
        ENUM_309.value = "309";
        ENUM_310.value = "310";
        ENUM_311.value = "311";
        ENUM_312.value = "312";
        _UNKNOWN.value = null;

        valueMap.put("AA", AA);
        valueMap.put("AB", AB);
        valueMap.put("AV", AV);
        valueMap.put("EX", EX);
        valueMap.put("F1", F1);
        valueMap.put("NC", NC);
        valueMap.put("ND", ND);
        valueMap.put("NE", NE);
        valueMap.put("NL", NL);
        valueMap.put("NP", NP);
        valueMap.put("NR", NR);
        valueMap.put("NS", NS);
        valueMap.put("NX", NX);
        valueMap.put("N7", N7);
        valueMap.put("RE", RE);
        valueMap.put("RJ", RJ);
        valueMap.put("V1", V1);
        valueMap.put("V2", V2);
        valueMap.put("V3", V3);
        valueMap.put("V4", V4);
        valueMap.put("V5", V5);
        valueMap.put("V6", V6);
        valueMap.put("000", ENUM_000);
        valueMap.put("001", ENUM_001);
        valueMap.put("002", ENUM_002);
        valueMap.put("003", ENUM_003);
        valueMap.put("004", ENUM_004);
        valueMap.put("005", ENUM_005);
        valueMap.put("006", ENUM_006);
        valueMap.put("007", ENUM_007);
        valueMap.put("008", ENUM_008);
        valueMap.put("009", ENUM_009);
        valueMap.put("011", ENUM_011);
        valueMap.put("012", ENUM_012);
        valueMap.put("013", ENUM_013);
        valueMap.put("014", ENUM_014);
        valueMap.put("015", ENUM_015);
        valueMap.put("016", ENUM_016);
        valueMap.put("017", ENUM_017);
        valueMap.put("018", ENUM_018);
        valueMap.put("019", ENUM_019);
        valueMap.put("020", ENUM_020);
        valueMap.put("021", ENUM_021);
        valueMap.put("022", ENUM_022);
        valueMap.put("023", ENUM_023);
        valueMap.put("024", ENUM_024);
        valueMap.put("025", ENUM_025);
        valueMap.put("026", ENUM_026);
        valueMap.put("027", ENUM_027);
        valueMap.put("028", ENUM_028);
        valueMap.put("029", ENUM_029);
        valueMap.put("030", ENUM_030);
        valueMap.put("031", ENUM_031);
        valueMap.put("032", ENUM_032);
        valueMap.put("033", ENUM_033);
        valueMap.put("034", ENUM_034);
        valueMap.put("035", ENUM_035);
        valueMap.put("036", ENUM_036);
        valueMap.put("037", ENUM_037);
        valueMap.put("038", ENUM_038);
        valueMap.put("039", ENUM_039);
        valueMap.put("040", ENUM_040);
        valueMap.put("041", ENUM_041);
        valueMap.put("042", ENUM_042);
        valueMap.put("043", ENUM_043);
        valueMap.put("044", ENUM_044);
        valueMap.put("045", ENUM_045);
        valueMap.put("046", ENUM_046);
        valueMap.put("047", ENUM_047);
        valueMap.put("048", ENUM_048);
        valueMap.put("049", ENUM_049);
        valueMap.put("050", ENUM_050);
        valueMap.put("051", ENUM_051);
        valueMap.put("052", ENUM_052);
        valueMap.put("053", ENUM_053);
        valueMap.put("054", ENUM_054);
        valueMap.put("055", ENUM_055);
        valueMap.put("056", ENUM_056);
        valueMap.put("057", ENUM_057);
        valueMap.put("058", ENUM_058);
        valueMap.put("059", ENUM_059);
        valueMap.put("060", ENUM_060);
        valueMap.put("061", ENUM_061);
        valueMap.put("062", ENUM_062);
        valueMap.put("063", ENUM_063);
        valueMap.put("064", ENUM_064);
        valueMap.put("065", ENUM_065);
        valueMap.put("066", ENUM_066);
        valueMap.put("067", ENUM_067);
        valueMap.put("068", ENUM_068);
        valueMap.put("069", ENUM_069);
        valueMap.put("070", ENUM_070);
        valueMap.put("071", ENUM_071);
        valueMap.put("072", ENUM_072);
        valueMap.put("073", ENUM_073);
        valueMap.put("074", ENUM_074);
        valueMap.put("075", ENUM_075);
        valueMap.put("076", ENUM_076);
        valueMap.put("077", ENUM_077);
        valueMap.put("078", ENUM_078);
        valueMap.put("079", ENUM_079);
        valueMap.put("080", ENUM_080);
        valueMap.put("081", ENUM_081);
        valueMap.put("082", ENUM_082);
        valueMap.put("083", ENUM_083);
        valueMap.put("084", ENUM_084);
        valueMap.put("085", ENUM_085);
        valueMap.put("086", ENUM_086);
        valueMap.put("087", ENUM_087);
        valueMap.put("088", ENUM_088);
        valueMap.put("089", ENUM_089);
        valueMap.put("090", ENUM_090);
        valueMap.put("091", ENUM_091);
        valueMap.put("092", ENUM_092);
        valueMap.put("093", ENUM_093);
        valueMap.put("094", ENUM_094);
        valueMap.put("095", ENUM_095);
        valueMap.put("096", ENUM_096);
        valueMap.put("097", ENUM_097);
        valueMap.put("098", ENUM_098);
        valueMap.put("099", ENUM_099);
        valueMap.put("100", ENUM_100);
        valueMap.put("101", ENUM_101);
        valueMap.put("102", ENUM_102);
        valueMap.put("103", ENUM_103);
        valueMap.put("104", ENUM_104);
        valueMap.put("105", ENUM_105);
        valueMap.put("106", ENUM_106);
        valueMap.put("107", ENUM_107);
        valueMap.put("108", ENUM_108);
        valueMap.put("109", ENUM_109);
        valueMap.put("110", ENUM_110);
        valueMap.put("111", ENUM_111);
        valueMap.put("112", ENUM_112);
        valueMap.put("113", ENUM_113);
        valueMap.put("114", ENUM_114);
        valueMap.put("115", ENUM_115);
        valueMap.put("116", ENUM_116);
        valueMap.put("117", ENUM_117);
        valueMap.put("118", ENUM_118);
        valueMap.put("119", ENUM_119);
        valueMap.put("120", ENUM_120);
        valueMap.put("121", ENUM_121);
        valueMap.put("122", ENUM_122);
        valueMap.put("123", ENUM_123);
        valueMap.put("124", ENUM_124);
        valueMap.put("125", ENUM_125);
        valueMap.put("126", ENUM_126);
        valueMap.put("127", ENUM_127);
        valueMap.put("128", ENUM_128);
        valueMap.put("129", ENUM_129);
        valueMap.put("130", ENUM_130);
        valueMap.put("131", ENUM_131);
        valueMap.put("132", ENUM_132);
        valueMap.put("133", ENUM_133);
        valueMap.put("134", ENUM_134);
        valueMap.put("135", ENUM_135);
        valueMap.put("136", ENUM_136);
        valueMap.put("137", ENUM_137);
        valueMap.put("138", ENUM_138);
        valueMap.put("139", ENUM_139);
        valueMap.put("140", ENUM_140);
        valueMap.put("141", ENUM_141);
        valueMap.put("142", ENUM_142);
        valueMap.put("143", ENUM_143);
        valueMap.put("144", ENUM_144);
        valueMap.put("145", ENUM_145);
        valueMap.put("146", ENUM_146);
        valueMap.put("147", ENUM_147);
        valueMap.put("148", ENUM_148);
        valueMap.put("149", ENUM_149);
        valueMap.put("150", ENUM_150);
        valueMap.put("151", ENUM_151);
        valueMap.put("152", ENUM_152);
        valueMap.put("153", ENUM_153);
        valueMap.put("154", ENUM_154);
        valueMap.put("155", ENUM_155);
        valueMap.put("156", ENUM_156);
        valueMap.put("157", ENUM_157);
        valueMap.put("158", ENUM_158);
        valueMap.put("159", ENUM_159);
        valueMap.put("160", ENUM_160);
        valueMap.put("161", ENUM_161);
        valueMap.put("162", ENUM_162);
        valueMap.put("163", ENUM_163);
        valueMap.put("164", ENUM_164);
        valueMap.put("165", ENUM_165);
        valueMap.put("166", ENUM_166);
        valueMap.put("167", ENUM_167);
        valueMap.put("168", ENUM_168);
        valueMap.put("169", ENUM_169);
        valueMap.put("170", ENUM_170);
        valueMap.put("171", ENUM_171);
        valueMap.put("172", ENUM_172);
        valueMap.put("173", ENUM_173);
        valueMap.put("174", ENUM_174);
        valueMap.put("175", ENUM_175);
        valueMap.put("176", ENUM_176);
        valueMap.put("177", ENUM_177);
        valueMap.put("178", ENUM_178);
        valueMap.put("179", ENUM_179);
        valueMap.put("180", ENUM_180);
        valueMap.put("181", ENUM_181);
        valueMap.put("182", ENUM_182);
        valueMap.put("183", ENUM_183);
        valueMap.put("184", ENUM_184);
        valueMap.put("185", ENUM_185);
        valueMap.put("186", ENUM_186);
        valueMap.put("187", ENUM_187);
        valueMap.put("188", ENUM_188);
        valueMap.put("189", ENUM_189);
        valueMap.put("190", ENUM_190);
        valueMap.put("191", ENUM_191);
        valueMap.put("192", ENUM_192);
        valueMap.put("193", ENUM_193);
        valueMap.put("194", ENUM_194);
        valueMap.put("195", ENUM_195);
        valueMap.put("196", ENUM_196);
        valueMap.put("197", ENUM_197);
        valueMap.put("198", ENUM_198);
        valueMap.put("199", ENUM_199);
        valueMap.put("200", ENUM_200);
        valueMap.put("201", ENUM_201);
        valueMap.put("202", ENUM_202);
        valueMap.put("203", ENUM_203);
        valueMap.put("204", ENUM_204);
        valueMap.put("205", ENUM_205);
        valueMap.put("206", ENUM_206);
        valueMap.put("207", ENUM_207);
        valueMap.put("208", ENUM_208);
        valueMap.put("209", ENUM_209);
        valueMap.put("210", ENUM_210);
        valueMap.put("222", ENUM_222);
        valueMap.put("227", ENUM_227);
        valueMap.put("244", ENUM_244);
        valueMap.put("254", ENUM_254);
        valueMap.put("255", ENUM_255);
        valueMap.put("300", ENUM_300);
        valueMap.put("301", ENUM_301);
        valueMap.put("302", ENUM_302);
        valueMap.put("303", ENUM_303);
        valueMap.put("304", ENUM_304);
        valueMap.put("305", ENUM_305);
        valueMap.put("306", ENUM_306);
        valueMap.put("307", ENUM_307);
        valueMap.put("308", ENUM_308);
        valueMap.put("309", ENUM_309);
        valueMap.put("310", ENUM_310);
        valueMap.put("311", ENUM_311);
        valueMap.put("312", ENUM_312);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TransactionStatusCode1 constructFromString(String toConvert) throws IOException {
        TransactionStatusCode1 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TransactionStatusCode1 fromString(String toConvert) {
        if (!valueMap.containsKey(toConvert)) {
            return _UNKNOWN;
        }
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

    /**
     * Convert list of TransactionStatusCode1 values to list of string values.
     * @param toConvert The list of TransactionStatusCode1 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TransactionStatusCode1> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TransactionStatusCode1 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 